ent-SimpleSpaceMobBase = { "" }
    .suffix = AI
    .desc = { "" }
ent-SimpleMobBase = { ent-SimpleSpaceMobBase }
    .suffix = AI
    .desc = { ent-SimpleSpaceMobBase.desc }
ent-SimpleFleshAnomalyBase = { ent-SimpleSpaceMobBase }
    .suffix = AI
    .desc = { ent-SimpleSpaceMobBase.desc }
