ent-MobXeno = Burrower
    .desc = They mostly come at night. Mostly.
    .suffix = { "" }
ent-MobXenoPraetorianNPC = Praetorian
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoDroneNPC = Drone
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoQueenNPC = Queen
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoRavagerNPC = Ravager
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoRunnerNPC = Runner
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoRounyNPC = Rouny
    .desc = { ent-MobXenoRunnerNPC.desc }
    .suffix = { "" }
ent-MobXenoSpitterNPC = Spitter
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoPlayer = Burrower
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoPraetorian = Praetorian
    .desc = { ent-MobXenoPraetorianNPC.desc }
    .suffix = { "" }
ent-MobXenoDrone = Drone
    .desc = { ent-MobXenoDroneNPC.desc }
    .suffix = { "" }
ent-MobXenoQueen = Queen
    .desc = { ent-MobXenoQueenNPC.desc }
    .suffix = { "" }
ent-MobXenoRavager = Ravager
    .desc = { ent-MobXenoRavagerNPC.desc }
    .suffix = { "" }
ent-MobXenoRunner = Runner
    .desc = { ent-MobXenoRunnerNPC.desc }
    .suffix = { "" }
ent-MobXenoRouny = Rouny
    .desc = { ent-MobXenoRunner.desc }
    .suffix = { "" }
ent-MobXenoSpitter = Spitter
    .desc = { ent-MobXenoSpitterNPC.desc }
    .suffix = { "" }
ent-MobPurpleSnake = space adder
    .desc = A menacing purple snake from Kepler-283c.
    .suffix = { "" }
ent-MobSmallPurpleSnake = space adder
    .desc = A smaller version of the menacing purple snake from Kepler-283c.
    .suffix = small
ent-MobPurpleSnakeGhost = { ent-MobPurpleSnake }
    .desc = { ent-MobPurpleSnake.desc }
    .suffix = { "" }
ent-MobSmallPurpleSnakeGhost = { ent-MobSmallPurpleSnake }
    .desc = { ent-MobSmallPurpleSnake.desc }
    .suffix = { "" }
