ent-ClothingHeadHelmetHardsuitAtmos = шлем скафандра атмос-техника
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingHeadHelmetHardsuitCap = шлем скафандра капитана
ent-ClothingHeadHelmetHardsuitDeathsquad = шлем скафандра эскадрона смерти
ent-ClothingHeadHelmetHardsuitEngineering = шлем скафандра инженера
ent-ClothingHeadHelmetHardsuitEngineeringWhite = шлем скафандра старшего инженера
ent-ClothingHeadHelmetIHSVoidHelm = шлем скафандра IHS
ent-ClothingHeadHelmetHardsuitMedical = шлем скафандра главного врача
ent-ClothingHeadHelmetHardsuitRd = экспериментальный шлем исследовательского скафандра
ent-ClothingHeadHelmetHardsuitSalvage = шлем скафандра утилизатора
ent-ClothingHeadHelmetHardsuitSecurity = шлем скафандра службы безопасности
ent-ClothingHeadHelmetHardsuitSecurityRed = шлем скафандра главы службы безопасности
ent-ClothingHeadHelmetHardsuitWarden = шлем скафандра смотрителя
ent-ClothingHeadHelmetHardsuitSyndie = кроваво-красный шлем скафандра
ent-ClothingHeadHelmetHardsuitWizard = шлем скафандра волшебника
ent-ClothingHeadHelmetHardsuitLing = органический космический шлем
ent-ClothingHeadHelmetHardsuitSpatio = шлем лёгкого скафандра утилизатора
ent-ClothingHeadHelmetHardsuitCybersun = шлем джаггернаута Cybersun
ent-ClothingHeadHelmetHardsuitSyndieCommander = шлем командира синдиката
ent-ClothingHeadHelmetHardsuitSyndieElite = шлем элиты синдиката
ent-ClothingHeadHelmetCBURN = шлем отряда РХБЗЗ
ent-ClothingHeadHelmetHardsuitERTLeader = шлем скафандра лидера ОБР
ent-ClothingHeadHelmetHardsuitERTEngineer = шлем скафандра инженера ОБР
ent-ClothingHeadHelmetHardsuitERTMedical = шлем скафандра медика ОБР
ent-ClothingHeadHelmetHardsuitERTSecurity = шлем скафандра офицера безопасности ОБР
ent-ClothingHeadHelmetHardsuitERTJanitor = шлем скафандра уборщика ОБР
