ent-ClothingHeadHatBeaverHat = бобровая шапка
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingHeadHatBeret = берет
ent-ClothingHeadHatBeretEngineering = инженерный берет
ent-ClothingHeadHatBeretHoS = берет главы службы безопасности
ent-ClothingHeadHatBeretWarden = берет смотрителя
ent-ClothingHeadHatBowlerHat = шляпа котелок
ent-ClothingHeadHatCaptain = капитанская каска
ent-ClothingHeadHatCardborg = шлем картонного борга
ent-ClothingHeadHatCentcom = фирменная шапка Центком
ent-ClothingHeadHatChef = поварской колпак
ent-ClothingHeadHatFedoraBrown = коричневая федора
ent-ClothingHeadHatFedoraGrey = серая федора
ent-ClothingHeadHatFez = феска
ent-ClothingHeadHatHopcap = фуражка главы персонала
ent-ClothingHeadHatHoshat = фуражка главы службы безопасности
ent-ClothingHeadHatOutlawHat = шляпа негодяя
ent-ClothingHeadHatWitch1 = ведьмина шляпа
ent-ClothingHeadHatPaper = бумажная шляпа
ent-ClothingHeadHatPirate = пиратская шляпа
ent-ClothingHeadHatPlaguedoctor = шляпа чумного доктора
ent-ClothingHeadHatRedwizard = красная волшебная шляпа
ent-ClothingHeadHatSantahat = колпак Санты
ent-ClothingHeadHatSombrero = сомбреро
ent-ClothingHeadHatSurgcapBlue = хирургическая шапочка
ent-ClothingHeadHatSurgcapGreen = хирургическая шапочка
ent-ClothingHeadHatSurgcapPurple = хирургическая шапочка
ent-ClothingHeadHatTophat = цилиндр
ent-ClothingHeadHatUshanka = ушанка
ent-ClothingHeadHatVioletwizard = фиолетовая волшебная шляпа
ent-ClothingHeadHatWarden = фуражка смотрителя
ent-ClothingHeadHatWitch = ведьмина шляпа
ent-ClothingHeadHatWizardFake = поддельная волшебная шляпа
ent-ClothingHeadHatWizard = волшебная шляпа
ent-ClothingHeadHatXmasCrown = рождественский венец
ent-ClothingHeadHatTrucker = кепка дальнобойщика
ent-ClothingHeadPyjamaSyndicateBlack = синдикатно-чёрная пижамная шапочка
ent-ClothingHeadPyjamaSyndicatePink = синдикатно-розовая пижамная шапочка
ent-ClothingHeadPyjamaSyndicateRed = синдикатно-красная пижамная шапочка
ent-ClothingHeadPaperSack = шапка из бумажного пакета
ent-ClothingHeadPaperSackSmile = улыбающаяся шапка из бумажного пакета
ent-ClothingHeadFishCap = кепка рыбака
ent-ClothingHeadNurseHat = шапочка медсестры
ent-ClothingHeadRastaHat = шапка-растаманка
ent-ClothingHeadSafari = шляпа для сафари
ent-ClothingHeadHatJester = шутовской колпак
ent-ClothingHeadHatJesterAlt = { ent-ClothingHeadHatJester }
ent-ClothingHeadHatBeretCmo = берет главного врача
