ent-ClothingHeadHatBunny = кроличьи ушки
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingHeadHatCake = шляпа с тортом
ent-ClothingHeadHatChickenhead = голова цыплёнка
ent-ClothingHeadHatFlowerCrown = цветочный венок
ent-ClothingHeadHatHairflower = цветок для волос
ent-ClothingHeadHatPumpkin = шляпа из тыквы
ent-ClothingHeadHatPwig = парик
ent-ClothingHeadHatRichard = Ричард
ent-ClothingHeadHatSkub = шапка скуб
ent-ClothingHeadHatShrineMaidenWig = парик святой девы
ent-ClothingHeadHatCone = предупредительный конус
ent-ClothingHeadHatFancyCrown = причудливая корона
ent-ClothingHeadHatCatEars = кошачьи ушки
ent-ClothingHeadHatSquid = кальмар
