ent-ClothingHeadHatBluesoft = синяя кепка
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingHeadHatBluesoftFlipped = перевёрнутая синяя кепка
ent-ClothingHeadHatCargosoft = кепка грузчика
ent-ClothingHeadHatCargosoftFlipped = перевёрнутая кепка грузчика
ent-ClothingHeadHatQMsoft = кепка квартирмейстера
ent-ClothingHeadHatQMsoftFlipped = перевёрнутая кепка квартирмейстера
ent-ClothingHeadHatCorpsoft = корпоративная кепка
ent-ClothingHeadHatCorpsoftFlipped = перевёрнутая корпоративная кепка
ent-ClothingHeadHatGreensoft = зелёная кепка
ent-ClothingHeadHatGreensoftFlipped = перевёрнутая зелёная кепка
ent-ClothingHeadHatGreysoft = серая кепка
ent-ClothingHeadHatGreysoftFlipped = перевёрнутая серая кепка
ent-ClothingHeadHatMimesoft = мимская кепка
ent-ClothingHeadHatMimesoftFlipped = перевёрнутая мимская кепка
ent-ClothingHeadHatOrangesoft = оранжевая кепка
ent-ClothingHeadHatOrangesoftFlipped = перевёрнутая оранжевая кепка
ent-ClothingHeadHatPurplesoft = фиолетовая кепка
ent-ClothingHeadHatPurplesoftFlipped = перевёрнутая фиолетовая кепка
ent-ClothingHeadHatRedsoft = красная кепка
ent-ClothingHeadHatRedsoftFlipped = перевёрнутая красная кепка
ent-ClothingHeadHatSecsoft = кепка СБ
ent-ClothingHeadHatSecsoftFlipped = перевёрнутая кепка СБ
ent-ClothingHeadHatYellowsoft = жёлтая кепка
ent-ClothingHeadHatYellowsoftFlipped = перевёрнутая желтая кепка
ent-ClothingHeadHatBizarreSoft = кепка хулигана
ent-ClothingHeadHatBizarreSoftFlipped = перевёрнутая кепка хулигана
ent-ClothingHeadHatParamedicsoft = шапочка парамедика
ent-ClothingHeadHatParamedicsoftFlipped = перевернутая шапочка парамедика
