job-name-mystagogue = мистагог
job-name-mantis = детектив
job-name-epistemologist = аколит
job-name-mail-carrier = почтальон
job-name-cataloguer = каталогизатор
job-name-salvage-technician = утилизатор
job-name-gladiator = гладиатор
job-name-fugitive = беглец
job-name-prisoner = заключенный
job-name-valet = сервисный работник
job-name-guard = охранник тюрьмы
# Role timers - Make these alphabetical or I cut you
job-name-martialartist = мастер боевых искусств
JobCataloguer = каталогизатор
JobEpistemologist = аколит
JobForensicMantis = детектив
JobMailCarrier = почтальон
JobMystagogue = мистагог
JobPrisoner = заключенный
JobSalvageTechnician = утилизатор
JobValet = сервисный работник
job-name-robot = робот
job-name-medical-robot = медицинский робот
JobRobot = робот
