ent-ClothingShoesColorBlack = чёрные туфли
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingShoesColorBlue = синие туфли
ent-ClothingShoesColorBrown = коричневые туфли
ent-ClothingShoesColorGreen = зелёные туфли
ent-ClothingShoesColorOrange = оранжевые туфли
ent-ClothingShoesColorPurple = фиолетовые туфли
ent-ClothingShoesColorRed = красные туфли
ent-ClothingShoesColorWhite = белые туфли
ent-ClothingShoesColorYellow = жёлтые туфли
