ent-ClothingShoesChef = поварские ботинки
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingShoesClown = клоунские туфли
ent-ClothingShoesBling = блестящие клоунские туфли
ent-ClothingShoesCult = ботинки культа
ent-ClothingShoesGaloshes = галоши
ent-ClothingShoesSpaceNinja = ботинки космического ниндзя
ent-ClothingShoesSwat = ботинки спецназа
ent-ClothingShoesWizard = обувь волшебника
ent-ClothingShoesChameleon = чёрные туфли
ent-ClothingShoesChameleonNoSlips = чёрные туфли
ent-ClothingShoesJester = шутовские туфли
