ent-LockerMystagogueFilled = шкафчик мистагога
    .suffix = Заполненый
    .desc = { ent-LockerResearchDirector.desc }
ent-LockerEpistemicsFilled = шкафчик аколита
    .suffix = Заполненый
    .desc = { ent-LockerScientist.desc }
ent-LockerForensicMantisFilled = { ent-LockerForensicMantis }
    .suffix = Заполненый
    .desc = { ent-LockerForensicMantis.desc }
