ent-PlayerCyborgBase = cyborg
    .desc = { ent-PlayerSiliconBase.desc }
    .suffix = { "" }
ent-PlayerCyborgStandard = standard cyborg
    .desc = { ent-PlayerCyborgBase.desc }
    .suffix = { "" }
ent-PlayerCyborgMedical = medical cyborg
    .desc = { ent-PlayerCyborgBase.desc }
    .suffix = { "" }
