ent-BaseMagazineBoxPistol = коробка патронов (.35 авто)
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-MagazineBoxPistol = коробка патронов (.35 авто)
    .desc = { ent-BaseMagazineBoxPistol.desc }
    .suffix = { "" }
ent-MagazineBoxPistolHighVelocity = коробка патронов (.35 авто высокоскоростные)
    .desc = { ent-BaseMagazineBoxPistol.desc }
    .suffix = { "" }
ent-MagazineBoxPistolUranium = коробка патронов (.35 авто урановые)
    .desc = { ent-BaseMagazineBoxPistol.desc }
    .suffix = { "" }
ent-MagazineBoxPistolPractice = коробка патронов (.35 авто учебные)
    .desc = { ent-BaseMagazineBoxPistol.desc }
    .suffix = { "" }
ent-MagazineBoxPistolRubber = коробка патронов (.35 авто резиновые)
    .desc = { ent-BaseMagazineBoxPistol.desc }
    .suffix = { "" }
