ent-EngineeringCableLv = { ent-CrateEngineeringCableLV }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
ent-EngineeringCableMv = { ent-CrateEngineeringCableMV }
ent-EngineeringCableHv = { ent-CrateEngineeringCableHV }
ent-EngineeringCableBulk = { ent-CrateEngineeringCableBulk }
ent-EngineeringElectricalSupplies = { ent-CrateEngineeringElectricalSupplies }
ent-EngineeringJetpack = { ent-CrateEngineeringJetpack }
ent-EngineeringMiniJetpack = { ent-CrateEngineeringMiniJetpack }
ent-AirlockKit = { ent-CrateAirlockKit }
