ent-MedicalSupplies = { ent-CrateMedicalSupplies }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
ent-MedicalChemistrySupplies = { ent-CrateChemistrySupplies }
ent-EmergencyBurnKit = { ent-CrateEmergencyBurnKit }
ent-EmergencyToxinKit = { ent-CrateEmergencyToxinKit }
ent-EmergencyO2Kit = { ent-CrateEmergencyO2Kit }
ent-EmergencyBruteKit = { ent-CrateEmergencyBruteKit }
ent-EmergencyAdvancedKit = { ent-CrateEmergencyAdvancedKit }
ent-EmergencyRadiationKit = { ent-CrateEmergencyRadiationKit }
