ent-BaseWeaponLauncher = BaseWeaponLauncher
    .desc = Дерзай — налетай, целься и стреляй.
    .suffix = { "" }
ent-WeaponLauncherChinaLake = чайна лэйк
    .desc = БЛУП
    .suffix = { "" }
ent-WeaponLauncherRocket = РПГ-7
    .desc = Древний ручной реактивный гранатомёт.
    .suffix = { "" }
ent-WeaponLauncherMultipleRocket = система залпового пуска
    .desc = Модифицированный древний ручной реактивный гранатомёт.
    .suffix = { "" }
ent-WeaponLauncherPirateCannon = пиратская пушка
    .desc = Кабум!
    .suffix = { "" }
ent-WeaponLauncherAdmemeMeteorLarge = пускатель метеоритов
    .desc = Стреляет большими метеоритами.
    .suffix = Адмемы
ent-WeaponLauncherAdmemeImmovableRodSlow = пускатель неподвижного жезла
    .desc = Стреляет неподвижными жезлами.
    .suffix = Адмемы
ent-WeaponTetherGun = гравитационная пушка
    .desc = Управляет гравитацией вокруг объектов, чтобы швырять их с высокой скоростью.
    .suffix = { "" }
ent-WeaponForceGun = силовая пушка
    .desc = Управляет гравитацией вокруг объектов, чтобы швырять их с высокой скоростью.
    .suffix = { "" }
ent-WeaponGrapplingGun = крюк-кошка
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-WeaponTetherGunAdmin = гравитационная пушка
    .desc = Управляет гравитацией вокруг объектов, чтобы швырять их с высокой скоростью.
    .suffix = admin
ent-WeaponForceGunAdmin = силовая пушка
    .desc = Управляет гравитацией вокруг объектов, чтобы швырять их с высокой скоростью.
    .suffix = Admin
