ent-FoodMealBase = { ent-FoodInjectableBase }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-FoodMealPotatoLoaded = печеный картофель с начинкой
ent-FoodMealFries = космический фри
ent-FoodMealFriesCheesy = сырный фри
ent-FoodMealFriesCarrot = морковка фри
ent-FoodMealNachos = начос
ent-FoodMealNachosCheesy = сырные начос
ent-FoodMealNachosCuban = Кубинские начос
ent-FoodMealMint = мята
ent-FoodMealEggplantParm = баклажан пармиджано
ent-FoodMealPotatoYaki = яки имо
ent-FoodMealCubancarp = карп по-Кубински
ent-FoodMealCornedbeef = солонина с капустой
ent-FoodMealBearsteak = филе-медведьон
ent-FoodMealPigblanket = сосиска в тесте
ent-FoodMealRibs = рёбрышки барбекю
ent-FoodMealEggsbenedict = яйца Бенедикт
ent-FoodMealOmelette = омлет дю фромаж
ent-FoodMealFriedegg = яичница
ent-FoodMealMilkape = молочная обезьяна
ent-FoodMealMemoryleek = лукотечка памяти
ent-DisgustingSweptSoup = солено-сладкий мисо-кольный суп
ent-FoodMealQueso = кесо
ent-FoodMealSashimi = сашими
ent-FoodMealEnchiladas = энчилада
