ent-BaseMagazineUniversalCaselessRifle = Универсальный магазин (.25 безгильзовые)
    .desc = { ent-BaseMagazineCaselessRifle.desc }
    .suffix = { "" }
ent-MagazineUniversalCaselessRifle = Универсальный магазин (.25 безгильзовые)
    .desc = { ent-BaseMagazineUniversalCaselessRifle.desc }
    .suffix = { "" }
ent-MagazineUniversalCaselessRifleHighVelocity = Универсальный магазин (.25 безгильзовые высокоскоростные)
    .desc = { ent-BaseMagazineUniversalCaselessRifle.desc }
    .suffix = { "" }
ent-MagazineUniversalCaselessRiflePractice = Универсальный магазин (.25 безгильзовые учебные)
    .desc = { ent-BaseMagazineUniversalCaselessRifle.desc }
    .suffix = { "" }
ent-MagazineUniversalCaselessRifleRubber = Универсальный магазин (.25 безгильзовые резина)
    .desc = { ent-BaseMagazineUniversalCaselessRifle.desc }
    .suffix = { "" }
