ent-FoodCurdCheese = curd cheese
    .desc = Known by many names throughout cuisine, curd cheese is useful for a wide variety of dishes.
    .suffix = { "" }
ent-FoodCheeseCurds = cheese curds
    .desc = Not to be mistaken for curd cheese. Tasty deep fried.
    .suffix = { "" }
ent-FoodMozzarella = mozzarella cheese
    .desc = Delicious, creamy, and cheesy, all in one simple package.
    .suffix = { "" }
ent-FoodMothHerbyCheese = herby cheese
    .desc = As a staple of mothic cuisine, cheese is often augmented with various flavours to keep variety in their diet.
    .suffix = { "" }
ent-FoodMothSaladBase = mothic salad
    .desc = A basic salad of cabbage, red onion and tomato.
    .suffix = { "" }
ent-BaseFoodMothSauce = sauce bowl
    .desc = A small bowl for condiment. Not reusable.
    .suffix = { "" }
ent-FoodMothTomatoSauce = tomato sauce
    .desc = Tomato with salt and herbs.
    .suffix = { "" }
ent-FoodMothPesto = pesto sauce
    .desc = A combination of salt, herbs, garlic, oil, and pine nuts. Frequently used as a sauce for pasta or pizza, or eaten on bread.
    .suffix = { "" }
ent-FoodMothBechamel = bechamel sauce
    .desc = A classic white sauce common to several European cultures.
    .suffix = { "" }
