ent-FoodMothCapreseSalad = caprese salad
    .desc = A very tasty yet simple to prepare salad.
    .suffix = { "" }
ent-FoodMothFleetSalad = fleet salad
    .desc = The grilled cheese makes it particularly filling, while the croutons provide a crunchy kick.
    .suffix = { "" }
ent-FoodMothCottonSalad = cotton salad
    .desc = A salad with added cotton and a basic dressing. Presumably moths are around.
    .suffix = { "" }
ent-FoodMothKachumbariSalad = kachumbari salad
    .desc = { ent-FoodBowlBase.desc }
    .suffix = { "" }
