ent-FoodMothSqueakingFry = squeaking stir fry
    .desc = A mothic classic made with cheese curds and tofu (amongst other things).
    .suffix = { "" }
ent-FoodMothToastedSeeds = toasted seeds
    .desc = While they're far from filling, toasted seeds are a popular snack amongst the moths. Some more exotic flavours may be added for some extra pep.
    .suffix = { "" }
ent-FoodMothChiliCabbageWrap = sweet chili cabbage wrap
    .desc = Grilled cheese and salad in a cabbage wrap, topped with delicious sweet chili sauce.
    .suffix = { "" }
ent-FoodMothBakedCheese = baked cheese wheel
    .desc = A baked cheese wheel, melty and delicious..
    .suffix = { "" }
ent-FoodMothBakedCheesePlatter = baked cheese platter
    .desc = A favourite for sharing. Usually served with crispy bread slices for dipping, because the only thing better than good cheese is good cheese on bread.
    .suffix = { "" }
ent-FoodBoritoPie = borito pie
    .desc = For when you are bored of normal meals while sitting in brig.
    .suffix = { "" }
