ent-SpawnPointGhostIfrit = Точка спавна роли призрака
    .suffix = Ифрит
    .desc = { ent-MarkerBase.desc }
ent-SpawnPointGhostFugitive = Точка спавна роли призрака
    .suffix = DONTMAP, Сбежавший заключенный
    .desc = { ent-MarkerBase.desc }
ent-SpawnPointLocationMidRoundAntag = Точка спавна роли призрака
    .suffix = Антагонист середины раунда
    .desc = { ent-MarkerBase.desc }
ent-SpawnPointGhostVampSpider = Точка спавна роли призрака
    .suffix = Паук-вампир
    .desc = { ent-MarkerBase.desc }
