ent-SpawnPointGladiator = гладиатор
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointMailCarrier = почтальон
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointForensicMantis = детектив
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointCyborg = киборг
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointMedicalCyborg = медицинский киборг
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointMystagogue = мистагог
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointEpistemologist = аколит
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointCataloguer = каталогизатор
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointSalvageTechnician = утилизатор
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointPrisoner = заключенный
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointValet = сервисный работник
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointPrisonGuard = охранник тюрьмы
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
