ent-CarpSpawnerMundane = NPC спавнер карпов
    .suffix = 100
    .desc = { ent-MarkerBase.desc }
ent-SnakeSpawnerMundane = NPC спавнер змей
    .suffix = 100
    .desc = { ent-MarkerBase.desc }
ent-SnakeMobMundane = Спавнер змей с осколков
    .suffix = 75
    .desc = { ent-MarkerBase.desc }
ent-SnakeMobMundane25 = Спавнер змей с осколков
    .suffix = 25
    .desc = { ent-MarkerBase.desc }
ent-SpaceTickSpawnerNPC = NPC спавнер космического клеща
    .suffix = 100
    .desc = { ent-MarkerBase.desc }
ent-XenoAISpawner = NPC спавнер Xeno
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
