ent-CrateToyBox = коробка игрушек
    .desc = Коробка, переполненная весельем.
    .suffix = Пустая
ent-CrateCoffin = гроб
    .desc = Удобный гроб, прекрасное место для вампиров и трупов.
    .suffix = { "" }
ent-CrateWoodenGrave = могила
    .desc = Здесь кто-то умер...
    .suffix = Деревянная
ent-CrateStoneGrave = могила
    .desc = Здесь кто-то умер...
    .suffix = Каменная
ent-CrateSyndicate = ящик синдиката
    .desc = Ящик из тёмной стали с красными полосами и выбитой на передней части буквой S.
    .suffix = { "" }
