ent-ClothingUniformMailCarrier = mail carrier's uniform
ent-ClothingUniformSkirtMailCarrier = mail carrier's jumpskirt
ent-ClothingUniformJumpsuitMystagogue = mystagogue's turtleneck
ent-ClothingUniformJumpsuitTshirtJeans = white t-shirt and jeans
ent-ClothingUniformJumpsuitTshirtJeansGray = gray t-shirt and jeans
ent-ClothingUniformJumpsuitTshirtJeansPeach = peach t-shirt and jeans
ent-ClothingUniformJumpsuitMantis = forensic mantis' uniform
ent-ClothingUniformSkirtMantis = forensic mantis' jumpskirt
ent-ClothingUniformJumpsuitPrisonGuard = prison guard's uniform
ent-ClothingUniformJumpsuitGalaxyRed = red galaxy suit
ent-ClothingUniformJumpsuitGalaxyBlue = blue galaxy suit
