ent-RegenerativeMesh = регенеративная сетка
    .desc = Используется для лечения даже самых неприятных ожогов. Эффективен также при разъедающих ожогах.
    .suffix = Полный
ent-OintmentAdvanced1 = { ent-RegenerativeMesh }
    .desc = { ent-RegenerativeMesh.desc }
    .suffix = Один
ent-MedicatedSuture = медикаментозный шов
    .desc = Шов, пропитанный медицинским препаратом, эффективно лечит тупые травмы и закрывает раны.
    .suffix = Полный
ent-BrutepackAdvanced1 = { ent-MedicatedSuture }
    .desc = { ent-MedicatedSuture.desc }
    .suffix = Один
ent-PillBicaridine = таблетка бикаридина (10u)
    .desc = { ent-Pill.desc }
    .suffix = { "" }
ent-PillAmbuzol = таблетка амбузола (10u)
    .desc = { ent-Pill.desc }
    .suffix = { "" }
ent-SyringeBicaridine = шприц бикаридина
    .desc = { ent-BaseSyringe.desc }
    .suffix = { "" }
ent-SyringeDermaline = шприц дермалина
    .desc = { ent-BaseSyringe.desc }
    .suffix = { "" }
ent-SyringeHyronalin = шприц хироналина
    .desc = { ent-BaseSyringe.desc }
    .suffix = { "" }
ent-SyringeAmbuzol = шприц амбузола
    .desc = { ent-BaseSyringe.desc }
    .suffix = { "" }
ent-SyringeRomerol = шприц ромерола
    .desc = { ent-BaseSyringe.desc }
    .suffix = { "" }
