technologies-security-technology = Технология СБ
technologies-security-technology-descritpion = Научитесь заменять и пополнять наше текущее оборудование службы безопастности.
technologies-ballistic-technology = Баллистическая технология
technologies-ballistic-technology-description = Боеприпасы для огнестрельного оружия всегда были хорошо известны, но наши техфабы борются с аспектами их производства.
technologies-direct-energy-technology = Технология направленной энергии
technologies-direct-energy-technology-description = Используйте наши достижения в области энергетических технологий в наступательных целях.
technologies-non-lethal-technology = Не-летальная технология
technologies-non-lethal-technology-description = Менее смертоносные варианты для СБ.
technologies-advanced-spray-technology = Продвинутая технология распыления
technologies-advanced-spray-technology-description = Новейшие способы мытья станции.
technologies-bluespace-technology = Блюспейс технология
technologies-bluespace-technology-description = Внепространственное хранилище.
technologies-teleportation-technology = Технология телепортации
technologies-teleportation-technology-description = Возможность мгновенно перемещать материю из одного места в другое.
