ent-ClothingBackpack = рюкзак
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingBackpackClown = хихишкин фон хонкертон
ent-ClothingBackpackSecurity = охранный рюкзак
ent-ClothingBackpackEngineering = инженерный рюкзак
ent-ClothingBackpackMedical = медицинский рюкзак
ent-ClothingBackpackCaptain = капитанский рюкзак
ent-ClothingBackpackMime = мимический рюкзак
ent-ClothingBackpackChemistry = химический рюкзак
ent-ClothingBackpackHydroponics = гидропонный рюкзак
ent-ClothingBackpackScience = научный рюкзак
ent-ClothingBackpackVirology = вирусологический рюкзак
ent-ClothingBackpackSalvage = рюкзак утилизатора
ent-ClothingBackpackERTLeader = рюкзак командира ОБР
ent-ClothingBackpackERTSecurity = рюкзак офицера безопасности ОБР
ent-ClothingBackpackERTMedical = рюкзак медика ОБР
ent-ClothingBackpackERTEngineer = рюкзак инженера ОБР
ent-ClothingBackpackERTJanitor = рюкзак уборщика ОБР
ent-ClothingBackpackERTClown = рюкзак клоуна ОБР
ent-ClothingBackpackHolding = блюспейс рюкзак
