ent-ClothingBackpackDuffel = вещмешок
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingBackpackDuffelEngineering = инженерный вещмешок
ent-ClothingBackpackDuffelMedical = медицинский вещмешок
ent-ClothingBackpackDuffelCaptain = капитанский вещмешок
ent-ClothingBackpackDuffelClown = клоунский вещмешок
ent-ClothingBackpackDuffelSecurity = охранный вещмешок
ent-ClothingBackpackDuffelChemistry = химический вещмешок
ent-ClothingBackpackDuffelVirology = вирусологийский вещмещок
ent-ClothingBackpackDuffelMime = мимский вещмешок
ent-ClothingBackpackDuffelScience = научный вещмешок
ent-ClothingBackpackDuffelHydroponics = гидропонный вещмешок
ent-ClothingBackpackDuffelSalvage = вещмешок утилизатора
ent-ClothingBackpackDuffelSyndicate = вещмешок синдиката
ent-ClothingBackpackDuffelSyndicateBundle = { ent-ClothingBackpackDuffelSyndicate }
ent-ClothingBackpackDuffelSyndicateAmmo = вещмешок синдиката
ent-ClothingBackpackDuffelSyndicateAmmoBundle = { ent-ClothingBackpackDuffelSyndicate }
ent-ClothingBackpackDuffelSyndicateMedical = вещмешок синдиката
ent-ClothingBackpackDuffelSyndicateMedicalBundle = { ent-ClothingBackpackDuffelSyndicate }
ent-ClothingBackpackDuffelHolding = бездонный вещмешок
