ent-BaseScrapDebris = Обломки лома
    .desc = { ent-BaseDebris.desc }
    .suffix = { "" }
ent-ScrapDebrisSmall = Малые обломки лома
    .desc = { ent-BaseScrapDebris.desc }
    .suffix = { "" }
ent-ScrapDebrisMedium = Средние обломки лома
    .desc = { ent-BaseScrapDebris.desc }
    .suffix = { "" }
ent-ScrapDebrisLarge = Большие обломки лома
    .desc = { ent-BaseScrapDebris.desc }
    .suffix = { "" }
