ent-BaseMagazineLightRifle = магазин (.30 винтовочные)
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-MagazineLightRifleBox = короб патронов L6 SAW (.30 винтовочные)
ent-MagazineLightRifle = магазин (.30 винтовочные)
ent-MagazineLightRifleHighVelocity = магазин (.30 винтовочные высокоскоростные)
ent-MagazineLightRiflePractice = магазин (.30 винтовочные учебные)
ent-MagazineLightRifleRubber = магазин (.30 винтовочные резиновые)
ent-MagazineLightRifleMaxim = дисковый магазин (.30 винтовочные)
ent-MagazineLightRiflePkBox = короб патронов ПК (.30 винтовочные)
