ent-SpaceCash = космобаксы
    .desc = Нужно иметь деньги.
    .suffix = { "" }
ent-SpaceCash10 = космобаксов
    .suffix = 10
    .desc = { ent-SpaceCash.desc }
ent-SpaceCash100 = космобаксов
    .suffix = 100
    .desc = { ent-SpaceCash.desc }
ent-SpaceCash500 = космобаксов
    .suffix = 500
    .desc = { ent-SpaceCash.desc }
ent-SpaceCash1000 = космобаксов
    .suffix = 1000
    .desc = { ent-SpaceCash.desc }
ent-SpaceCash1000000 = космобаксов
    .suffix = 1000000
    .desc = { ent-SpaceCash.desc }
ent-SpaceCash2500 = { ent-SpaceCash }
    .suffix = 2500
    .desc = { ent-SpaceCash.desc }
ent-SpaceCash5000 = { ent-SpaceCash }
    .suffix = 5000
    .desc = { ent-SpaceCash.desc }
ent-SpaceCash10000 = { ent-SpaceCash }
    .suffix = 10000
    .desc = { ent-SpaceCash.desc }
