altar-sacrifice-verb = Принести в жертву
soul-entity-name = душа { $trapped }заключена в кристалл
soul-entity-desc = Кристал душ с душой { $trapped } заключенной внутри.
altar-popup = { $user } начинает приносить в жертву { $target }!
altar-failure-reason-self = Вы не можете принести в жертву себя!
altar-failure-reason-user = Вы не псионник и не мистически не обучены!
altar-failure-reason-user-humanoid = Вы не гуманоид!
altar-failure-reason-target = { CAPITALIZE(($target)) } { CONJUGATE-BE($target) } не является псионником!
altar-failure-reason-target-humanoid = { CAPITALIZE(($target)) } { CONJUGATE-BE($target) } не является гуманоидом!
altar-failure-reason-target-ssd = { CAPITALIZE(($target)) } { CONJUGATE-BE($target) } находится в ССД!
