ent-VendingMachine = торговый автомат
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-VendingMachineAmmo = Станция Свободы
ent-VendingMachineBooze = АлкоМат
ent-VendingMachineCart = ПТех
ent-VendingMachineChefvend = ШефВенд
ent-VendingMachineCigs = ШейдиСиг Делюкс
ent-VendingMachineClothing = ОдеждоМат
ent-VendingMachineCoffee = Лучшие горячие напитки Солнечной
ent-VendingMachineCola = Прохладительные напитки Робаст
ent-VendingMachineDinnerware = Кухонно-пластальная поварская утварь
ent-VendingMachineCondiments = станция по продаже приправ
ent-VendingMachineMagivend = МагМазин
ent-VendingMachineDiscount = Дискаунтер Дэна
ent-VendingMachineEngivend = ИнжеМат
ent-VendingMachineMedical = НаноМед Плюс
ent-VendingMachineNutri = БотаМакс
ent-VendingMachineSec = СБТех
ent-VendingMachineSeedsUnlocked = МегаРаздатчик Семян
ent-VendingMachineSeeds = { ent-VendingMachineSeedsUnlocked }
ent-VendingMachineSmartFridge = Умный холодильник
ent-VendingMachineSnack = Гетмор Шоколад Корп
ent-VendingMachineSovietSoda = ВОДА
ent-VendingMachineTheater = ТеатроШкаф
ent-VendingMachineVendomat = Торгомат
ent-VendingMachineYouTool = ТвоИнструменты
ent-VendingMachineGames = Безобидные развлечения
ent-VendingMachineChang = Мистер Чанг
ent-VendingMachineSalvage = Утильмаг
ent-VendingMachineDonut = Пончики Монкинс
ent-VendingMachineWallmount = торговый автомат
ent-VendingMachineWallMedical = НаноМед
ent-VendingMachineHydrobe = ГидроРоб
ent-VendingMachineLawDrobe = ЗаконШкаф
ent-VendingMachineSecDrobe = ОхранШкаф
ent-VendingBarDrobe = БарДероб
ent-VendingMachineChapel = БогоМат
ent-VendingMachineCargoDrobe = КаргоШкаф
ent-VendingMachineMediDrobe = МедШкаф
ent-VendingMachineChemDrobe = ХимШкаф
ent-VendingMachineAtmosDrobe = АтмосШкаф
ent-VendingMachineEngiDrobe = ИнжеШкаф
ent-VendingMachineChefDrobe = ШефШкаф
ent-VendingMachineDetDrobe = ДетекШкаф
ent-VendingMachineJaniDrobe = УборШкаф
ent-VendingMachineSciDrobe = НаучШкаф
ent-VendingMachineRoboDrobe = РобоШкаф
ent-VendingMachineGeneDrobe = ГеноШкаф
ent-VendingMachineViroDrobe = ВироШкаф
ent-VendingMachineHappyHonk = автомат Счастливый Хонк
ent-VendingMachineTankDispenserEVA = Раздатчик Газовых Баллонов
ent-VendingMachineTankDispenserEngineering = Раздатчик Газовых Баллонов
