accent-pirate-replacement-7 = друг сердечный
accent-pirate-replacement-8 = приятель
accent-pirate-replaced-9 = дружище
accent-pirate-replacement-9 = друг сердечный
accent-pirate-replaced-10 = привет
accent-pirate-replacement-10 = ахой
accent-pirate-replaced-11 = эй
accent-pirate-replacement-11 = эйе
accent-pirate-replaced-12 = деньги
accent-pirate-replacement-12 = дублоны
accent-pirate-replaced-13 = денег
accent-pirate-replacement-13 = дублонов
accent-pirate-replaced-14 = ящик
accent-pirate-replacement-14 = сундук
accent-pirate-replaced-15 = здарова
accent-pirate-replacement-15 = ахой
accent-pirate-replaced-16 = сокровище
accent-pirate-replacement-16 = награбленное добро
accent-pirate-replaced-17 = внимание
accent-pirate-replacement-17 = напрягли ракушки
accent-pirate-replaced-18 = тупой
accent-pirate-replacement-18 = попугаяголовый
accent-pirate-replaced-19 = идиот
accent-pirate-replacement-19 = морской пёс
accent-pirate-replaced-20 = твой
accent-pirate-replacement-20 = твйор
accent-pirate-replaced-21 = песня
accent-pirate-replacement-21 = шанти
accent-pirate-replaced-22 = музыка
accent-pirate-replacement-22 = шанти
accent-pirate-replaced-23 = нет
accent-pirate-replacement-23 = нэй
accent-pirate-replaced-24 = вышел
accent-pirate-replacement-24 = за борт
accent-pirate-replaced-25 = ой
accent-pirate-replacement-25 = яррр
accent-pirate-replaced-26 = ауч
accent-pirate-replacement-26 = аррр
accent-pirate-replaced-27 = пассажир
accent-pirate-replacement-27 = сухопутный жук
accent-pirate-replaced-28 = ассистент
accent-pirate-replacement-28 = сухопутный жук
accent-pirate-replaced-29 = капитан
accent-pirate-replacement-29 = кэп'н
accent-pirate-replaced-30 = пистолет
accent-pirate-replacement-30 = пестольный мушкет
accent-pirate-replaced-31 = винтовка
accent-pirate-replacement-31 = мушкет
accent-pirate-replaced-32 = патроны
accent-pirate-replacement-32 = порох
