ent-ClothingEyesTelegnosisSpectacles = strange spectacles
    .desc = A pair of spectacular and strange spectacles with lenses constructed of an unknown material.
    .suffix = { "" }
ent-BedsheetInvisibilityCloak = tattered bedsheet
    .desc = A tattered bedsheet, It looks like its been through hell and back.
    .suffix = { "" }
ent-ClothingHandsDispelGloves = patchwork gloves
    .desc = These leather gloves are heavily worn, however they have been repaired in several places.
    .suffix = { "" }
ent-ClothingHandsGlovesColorYellowUnsulated = unsulated gloves
    .desc = Flimsy synthrubber work gloves styled in a drab yellow color. They are not electrically insulated, and provide no protection against any shocks.
    .suffix = { "" }
