ent-ScienceTechFab = техфаб эпистемики
    .desc = Печатает инструменты для эпистемики.
    .suffix = { "" }
ent-ServiceTechFab = сервисный техфаб
    .desc = Печатает инструменты под нужды сервиса.
    .suffix = { "" }
ent-EngineeringTechFab = инженерный техфаб
    .desc = Печатает инструменты для инженеров.
    .suffix = { "" }
