ent-VendingMachineEpiDrobe = EpiDrobe
    .desc = These white robes have to be cleaned quite a lot, you know.
    .suffix = { "" }
ent-VendingMachineAutomatrobe = Automatrobe
    .desc = Automatically good.
    .suffix = { "" }
ent-VendingMachineRepDrobe = RepDrobe
    .desc = A machine for all your reporting needs, as long as you need clothes.
    .suffix = { "" }
ent-VendingMachineBoxingDrobe = Boxing Drobe
    .desc = Always short on stock.
    .suffix = { "" }
ent-VendingMachineMailDrobe = MailDrobe
    .desc = Neither solar flares nor meteors nor plasma fire nor void of space stays these couriers from the swift completion of their appointed rounds.
    .suffix = { "" }
