ent-BaseHealingItem = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-Ointment = мазь
ent-Brutepack = набор для ушибов
ent-Gauze = марлевый бинт
ent-Gauze1 = { ent-Gauze }
ent-AloeCream = алоэ крем
ent-PillDexalin = таблетка дексалина
ent-PillDylovene = таблетка диловена
ent-PillHyronalin = таблетка хироналина
ent-PillIron = таблетка железа
ent-PillKelotane = таблетка келотана
ent-PillSpaceDrugs = космические наркотики
ent-PillTricordrazine = таблетка трикордразина
ent-PillRomerol = таблетка ромерола
ent-SyringeEphedrine = шприц эфедрина
ent-SyringeInaprovaline = шприц инапровалина
ent-SyringeTranexamicAcid = шприц транексамовой кислоты
ent-SyringeSpaceacillin = шприц космоциллина
ent-SyringeIpecac = шприц ипекака
ent-SyringeCorpium = шприц корпиума
