ent-Hypospray = гипоспрей
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-SyndiHypo = горлекс гипоспрей
ent-ChemicalMedipen = химический медипен
ent-EmergencyMedipen = экстренный медипен
ent-AntiPoisonMedipen = медипен противоядие
ent-SpaceMedipen = космический медипен
ent-Stimpack = инъектор стимуляторов
ent-StimpackMini = микроинъектор стимуляторов
ent-StimpackExperimental = инъектор экспериментальных стимуляторов
ent-Hypopen = ручка
