ent-SpawnPointGhostIfrit = Точка появления роли призрака
    .suffix = Ифрит
    .desc = { ent-MarkerBase.desc }
ent-SpawnPointGhostFugitive = Точка появления роли призрака
    .suffix = DONTMAP, Сбежавший заключенный
    .desc = { ent-MarkerBase.desc }
ent-SpawnPointLocationMidRoundAntag = Точка появления роли призрака
    .suffix = Антагонист середины раунда
    .desc = { ent-MarkerBase.desc }
ent-SpawnPointGhostVampSpider = Точка появления роли призрака
    .suffix = Паук-вампир
    .desc = { ent-MarkerBase.desc }
