ent-BaseMagazineMagnum = Lamia magazine (.45 magnum)
ent-MagazineMagnum = Lamia magazine (.45 magnum)
ent-MagazineMagnumHighVelocity = Lamia magazine (.45 magnum high-velocity)
ent-MagazineMagnumPractice = Lamia magazine (.45 magnum practice)
ent-MagazineMagnumRubber = Lamia magazine (.45 magnum rubber)
