ent-MobSpaceBasic = basic
    .desc = It looks friendly. Why don't you give it a hug?
    .suffix = { "" }
ent-MobKangarooSpace = space kangaroo
    .desc = It looks friendly. Why don't you give it a hug?
    .suffix = { "" }
ent-MobKangarooSpaceSalvage = { ent-MobKangarooSpace }
    .suffix = Salvage Ruleset
    .desc = { ent-MobKangarooSpace.desc }
ent-MobSpiderSpace = space spider
    .desc = It's so glowing, it looks dangerous.
    .suffix = { "" }
ent-MobSpiderSpaceSalvage = { ent-MobSpiderSpace }
    .suffix = Salvage Ruleset
    .desc = { ent-MobSpiderSpace.desc }
