bible-heal-success-self = Вы ударяете { THE($target) } с помощью { THE($bible) }, и его раны закрываются во вспышке святого света!
bible-heal-success-others = { CAPITALIZE(THE($user)) } ударяет { THE($target) } с помощью { THE($bible) }, и его раны закрываются во вспышке святого света!
bible-heal-success-none-self = Вы ударяете { THE($target) } с помощью { THE($bible) }, но раны которые можно излечить отсутствуют!
bible-heal-success-none-others = { CAPITALIZE(THE($user)) } ударяет { THE($target) } с помощью { THE($bible) }!
bible-heal-fail-self = Вы ударяете { THE($target) } с помощью { THE($bible) }, с печальным стуком, оказывает ошеломляющий эффект на { OBJECT($target) }!
bible-heal-fail-others = { CAPITALIZE(THE($user)) } ударяет { THE($target) } с помощью { THE($bible) }, с печальным стуком, оказывает ошеломляющий эффект на { OBJECT($target) }!
bible-sizzle = Книга шипит в ваших руках!
bible-summon-verb = Призвать фамильяра
bible-summon-verb-desc = Призовите фамильяра, который станет помогать вам и обретет человекоподобный интеллект после вселения в него души.
bible-summon-requested = Ваш фамильяр явится, как только появится желающая душа.
bible-summon-respawn-ready = { CAPITALIZE(THE($book)) } наполняется неземной энергией. Обитатель { CAPITALIZE(POSS-ADJ($book)) } вернулся домой.
necro-heal-success-self = Вы ударяете { THE($target) } с помощью { THE($bible) }, и кожа { POSS-ADJ($target) } начинает кукожиться и плавиться!
necro-heal-success-others = { CAPITALIZE(THE($user)) } ударяет { THE($target) } с помощью { THE($bible) }, и кожа { POSS-ADJ($target) } начинает кукожиться и плавиться!
necro-heal-fail-self = Вы ударяете { THE($target) } с помощью { THE($bible) }, но удар отдаётся печальным стуком, не сумев поразить { OBJECT($target) }.
necro-heal-fail-others = { CAPITALIZE(THE($user)) } ударяет { THE($target) } с помощью { THE($bible) }, но удар отдаётся печальным стуком, не сумев поразить { OBJECT($target) }.
