ent-BaseHyperlinkBook = { ent-BaseItem }
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-HyperlinkBookSpaceLaw = космический закон
    .desc = Большая книга законов для космических судов.
    .suffix = { "" }
ent-HyperlinkBookSupernanny = книга несанкционированных космических наказаний
    .desc = Бред сумасшедшего.
    .suffix = { "" }
ent-HyperlinkBookGlimmer = инструкция по глиммеру
    .desc = Путеводитель по явлению, известному как 'глиммер.'
    .suffix = { "" }
ent-HyperlinkBookChemistry = книга химических рецептов
    .desc = Список химических рецептов.
    .suffix = { "" }
ent-HyperlinkBookBartending = гид бармена
    .desc = Список рецептов напитков.
    .suffix = { "" }
ent-HyperlinkBookCooking = кулинарная книга
    .desc = Список рецептов еды.
    .suffix = { "" }
ent-HyperlinkBookBotany = ботанический путеводитель
    .desc = Путеводитель по растениям.
    .suffix = { "" }
ent-HyperlinkBookShuttle = руководство по строительству шаттла
    .desc = Руководство по созданию шаттлов.
    .suffix = { "" }
ent-HyperlinkBookAlerts = процедура кодов
    .desc = Процедура, когда и почему каждый код должн быть введен в действие, и что делать.
    .suffix = { "" }
ent-HyperlinkBookProcedure = стандартные рабочие процедуры
    .desc = Руководство по нормальной работе станции.
    .suffix = { "" }
ent-HyperlinkBookPower = руководство по электроснабжению
    .desc = Руководство по питанию станции.
    .suffix = { "" }
ent-HyperlinkBookMedical = руководство по медицинскому
    .desc = Путеводитель по медицинскому отделению.
    .suffix = { "" }
ent-HyperlinkBookHacking = руководство по взлому
    .desc = Только для экстренного использования.
    .suffix = { "" }
ent-HyperlinkBookAtmos = руководство по атмосфере
    .desc = Как сделать так, чтобы у всех был воздух для дыхания.
    .suffix = { "" }
