ghost-role-information-slimes-name = Слайм
ghost-role-information-slimes-description = Обычная слизь без особых потребностей и интересов. Он просто живет.
ghost-role-information-angry-slimes-description = Все вокруг тебя раздражает твои инстинкты, уничтожь их!
ghost-role-information-xeno-name = Ксенос
ghost-role-information-xeno-description = Вы ксено, сотрудничайте со своим ульем, чтобы убить всех членов экипажа!
ghost-role-information-xeno-rules = Ты антагонист, шлепай, руби и тупи!
ghost-role-information-revenant-name = Ревенант
ghost-role-information-revenant-description = Вы Ревенант. Используйте свои силы, чтобы собирать души и сеять хаос на станции. Разблокируйте новые способности с помощью эссенции, которую вы собираете.
ghost-role-information-revenant-rules = Вы антагонист, собираете души, оскверняете и сводите команду с ума.
ghost-role-information-kangaroo-name = Кенгуру
ghost-role-information-kangaroo-description = Ты кенгуру! Делайте то, что делают кенгуру.
ghost-role-information-monkey-name = Обезьяна
ghost-role-information-monkey-description = ООК ОКО!
ghost-role-information-rat-king-name = Король крыс
ghost-role-information-rat-king-description = Вы - Крысиный король, собирайте еду, чтобы производить крысиных миньонов, которые будут выполнять ваши приказы.
ghost-role-information-rat-king-rules = Вы антагонист, собирайте мусор, атакуйте и накапливайте свои сокровища!
ghost-role-information-rat-servant-name = Крысиный слуга
ghost-role-information-rat-servant-description = Вы крыса-слуга. Вы должны следовать приказам своего короля.
ghost-role-information-rat-servant-rules = Вы антагонист, собирайте мусор, атакуйте и служите своему королю!
ghost-role-information-salvage-carp-name = Космический карп на обломке
ghost-role-information-salvage-carp-description = Защити добычу внутри обломка!
ghost-role-information-sentient-carp-name = Разумный карп
ghost-role-information-sentient-carp-description = Помогите дракону затопить станцию карпами!
ghost-role-information-willow-name = Кенгуру Уиллоу
ghost-role-information-willow-description = Ты кенгуру по имени Уиллоу! Уиллоу любит боксировать.
ghost-role-information-space-tick-name = Космический клещ
ghost-role-information-space-tick-description = Устрой хаос на станции!
ghost-role-information-salvage-tick-name = Космический клещ на обломке
ghost-role-information-salvage-tick-description = Защити добычу внутри обломка!
ghost-role-information-honkbot-name = ХоНкБоТ
ghost-role-information-honkbot-description = Искусственное существо чистого зла.
ghost-role-information-jonkbot-name = Джонкбот
ghost-role-information-jonkbot-description = Искусственное существо чистого зла.
ghost-role-information-mimebot-name = МимБот
ghost-role-information-mimebot-description = Мимбот, действуй как мим, но не как грейтайдер.
ghost-role-information-space-bear-name = Космический медведь
ghost-role-information-space-bear-description = Ты медведь! Делайте медвежьи вещи.
ghost-role-information-salvage-bear-name = Космический медведь на обломке
ghost-role-information-salvage-bear-description = Защити добычу внутри обломка!
ghost-role-information-space-kangaroo-name = Космический кенгуру
ghost-role-information-space-kangaroo-description = Ты кенгуру! Делайте все, как кенгуру.
ghost-role-information-salvage-kangaroo-name = Космический кенгуру на обломке
ghost-role-information-salvage-kangaroo-description = Защити добычу внутри обломка!
ghost-role-information-space-spider-name = Космический паук
ghost-role-information-space-spider-description = Космические пауки так же агрессивны, как и обычные пауки.
ghost-role-information-salvage-spider-name = Космический паук на обломке
ghost-role-information-salvage-spider-description = Защити добычу внутри обломка!
ghost-role-information-guardian-name = Страж
ghost-role-information-guardian-description = Слушай своего хозяина. Не впитывайте урон. Бейте людей сильно.
ghost-role-information-holoparasite-name = Голопаразит
ghost-role-information-holoparasite-description = Слушай своего хозяина. Не впитывайте урон. Бейте людей сильно.
ghost-role-information-ifrit-name = Ифрит
ghost-role-information-ifrit-description = Слушай своего хозяина. Не впитывайте урон. Бейте людей сильно.
ghost-role-information-space-dragon-name = Космический дракон
ghost-role-information-space-dragon-description = Вызовите 3 карповых разлома и захватите эту станцию ! У вас есть только 5 минут между каждым разломом, прежде чем вы исчезнете.
ghost-role-information-cluwne-name = Клувня
ghost-role-information-cluwne-description = Станьте жалким клоуном, ваша единственная цель в жизни — найти сладкое избавление от ваших страданий (обычно через избиение до смерти). Клувня не является антагонистом, но может защищаться. Члены экипажа могут свободно убивать клаунов.
ghost-role-information-skeleton-pirate-name = Скелет-Пират
ghost-role-information-skeleton-pirate-description = Создавайте хаос и грабите станцию в поисках сокровищ.
ghost-role-information-skeleton-biker-name = Скелет-Байкер
ghost-role-information-skeleton-biker-description = Катайся на своем сладком байке.
ghost-role-information-onestar-mecha-name = Онестар меха
ghost-role-information-onestar-mecha-description = Вы — экспериментальный механизм, созданный бог знает кем, все, что вы знаете, это то, что у вас есть оружие, и вы обнаруживаете живые движущиеся цели поблизости...
ghost-role-information-onestar-mecha-rules = Используйте свое оружие, чтобы вызвать хаос. Вы антагонист.
ghost-role-information-remilia-name = Ремилия, фамильяр капеллана
ghost-role-information-remilia-description = Подчиняйся своему мастеру. Пейте кровь.
ghost-role-information-remilia-rules = Вы умная летучая мышь-вампир. Следуйте за капелланом вокруг. Не создавай проблем, если только капеллан не скажет тебе об этом.
ghost-role-information-cerberus-name = Цербер, фамельяр капеллана
ghost-role-information-cerberus-description = Подчиняйся своему мастеру. Пейте кровь.
ghost-role-information-cerberus-rules = Ты умная, демоническая собака. Попробуйте помочь капеллану и любому из его паствы. Как антагонист, вы ничем не ограничены.
ghost-role-information-ert-leader-name = Лидер ОБР
ghost-role-information-ert-leader-description = Возглавьте команду специалистов для решения проблем со станциями.
ghost-role-information-ert-janitor-name = Уборщик ОБР
ghost-role-information-ert-janitor-description = Окажите помощь станции в решении проблем.
ghost-role-information-ert-engineer-name = Инженер ОБР
ghost-role-information-ert-engineer-description = Окажите помощь в инженерных работах по решению проблем на станции.
ghost-role-information-ert-security-name = Офицер безопасности ОБР
ghost-role-information-ert-security-description = Окажите помощь в проблемах безопасности по решению проблем на станции.
ghost-role-information-ert-medical-name = Медик ОБР
ghost-role-information-ert-medical-description = Окажите помощь в медицинских работах по решению проблем на станции.
ghost-role-information-cburn-agent-name = Агент РХБЗЗ
ghost-role-information-cburn-agent-description = Высококвалифицированный агент ЦентКом, способный бороться с различными угрозами.
ghost-role-information-centcom-official-name = Представитель ЦентКом
ghost-role-information-centcom-official-description = Осмотрите станцию, запишите аттестации начальников штабов, поставьте жучок у капитана.
