reverse-engineering-machine-menu-title = машина обратной инженерии
reverse-engineering-machine-server-list-button = Список серверов
reverse-engineering-machine-scan-button = Анализировать
reverse-engineering-machine-scan-tooltip-info = Анализировать выбранный объект в попытке понять как он построен.
reverse-engineering-machine-safety-button = Безопасность
reverse-engineering-machine-safety-tooltip-info = Переключить протоколы безопасности. Выключенная безопасность будет использовать более сильные и более разрушительные методы анализа.
reverse-engineering-machine-autoscan-button = Автоскан
reverse-engineering-machine-autoscan-tooltip-info = Переключите, следует ли автоматически запускать новый скан после завершения предыдущего.
reverse-engineering-machine-stop-button = Стоп
reverse-engineering-machine-stop-tooltip-info = Останавливает текущий процесс.
reverse-engineering-machine-eject-button = Извлечь
reverse-engineering-machine-eject-tooltip-info = Извлечь текущий предмет.
reverse-engineering-status-ready = Вставте предмет для обратной инженерии.
reverse-engineering-current-item = Текущий предмет: { $item }
reverse-engineering-analysis-score = Мощность анализа: { $score }
reverse-engineering-item-difficulty = Сложность: { $difficulty }
reverse-engineering-progress = Прогресс: { $progress }%
reverse-engineering-last-attempt-result = Результат прошлой попытки: { $result }
reverse-engineering-total-progress-label = Текущий
reverse-engineering-failure = { CAPITALIZE(($machine)) } выбрасывает дым и обломки во все стороны!
reverse-engineering-stagnation = Минимальный прогресс
reverse-engineering-minor = Малый прогресс
reverse-engineering-average = Удовлетворительный прогресс
reverse-engineering-major = Хороший прогресс
reverse-engineering-success = Прорыв
reverse-engineering-machine-bonus-upgrade = Мощность анализа
reverse-engineering-machine-aversion-upgrade = Бонус уничтожения
reverse-engineering-examine = [color=yellow]Этот предмет может быть реконструирован. Сложность: { $diff }[/color]
