ent-ClothingCostumeBunnySuit = bunny suit
    .desc = Ready to go with stockings and a bow tie.
    .suffix = { "" }
ent-ClothingCostumeMioSkirt = yellow skirt with rose hoodie
    .desc = Soft and comfortable, it sports bright colors with a neat yellow bow at the neck.
    .suffix = { "" }
ent-ClothingUniformSkirtTurtle = decorated turtle skirt
    .desc = A turtle skirt with yellow straps and soft fabric.
    .suffix = { "" }
ent-ClothingUniformSchoolgirlBase = { ent-ClothingUniformSkirtBase }
    .desc = Ready for school!
    .suffix = { "" }
ent-ClothingKimonoGreen = sea green kimono
    .desc = Colors and textures reminiscent of seaweed.
    .suffix = { "" }
ent-UniformSchoolgirlDusk = dusk schoolgirl uniform
    .desc = Ready for school in modern style.
    .suffix = { "" }
ent-UniformSchoolgirlBlazerTan = tan blazer schoolgirl uniform
    .desc = Ready for school in modern style. This set comes with a tan blazer.
    .suffix = { "" }
