ent-ClothingCostumeBunnySuit = кроличьий костюм
    .desc = Ready to go with stockings and a bow tie.
    .suffix = { "" }
ent-ClothingCostumeMioSkirt = желтая юбка и худи с розой
    .desc = Мягкое и удобное, яркое, с аккуратным желтым бантом на шее.
    .suffix = { "" }
ent-ClothingUniformSkirtTurtle = декоротивная черепашья юбка
    .desc = Юбка-черепаха с желтыми бретельками и мягкой тканью.
    .suffix = { "" }
ent-ClothingUniformSchoolgirlBase = { ent-ClothingUniformSkirtBase }
    .desc = Готова к школе!
    .suffix = { "" }
ent-ClothingKimonoGreen = кимоно цвета морской волны
    .desc = Цвета и текстуры напоминают морские водоросли.
    .suffix = { "" }
ent-UniformSchoolgirlDusk = сумеричная школьная форма
    .desc = Готов к школе в современном стиле.
    .suffix = { "" }
ent-UniformSchoolgirlBlazerTan = школьная форма коричневого блейзера
    .desc = Готова к школе в современном стиле. Этот комплект поставляется с коричневым блейзером.
    .suffix = { "" }
