guide-entry-reverse-engineering = Обратная инженерия
guide-entry-epistemics = Эпистемика
guide-entry-psionics = Псионика
guide-entry-altars-golemancy = Алтари и Големантия
guide-entry-space-law = Космический Закон
guide-entry-jurisdiction = Юрисдикция
guide-entry-trial-prodedure = Судебная процедура
guide-entry-charges-and-times = Обвинения и приговор
guide-entry-chemistry = Химия
guide-entry-shogi = Сёги
guide-entry-chef = Шеф-повар
guide-entry-cookbook = Поваренная книга
guide-entry-burgers = Бургеры
guide-entry-cakes = Торты
guide-entry-pastries = Выпечка
guide-entry-pizzas = Пицца
guide-entry-kebabs = Шашлыки
guide-entry-sandwiches = Хлеб и бутерброды
guide-entry-snacks = Закуски
guide-entry-pasta = Макаронны и рис
guide-entry-soups = Супы
guide-entry-salads = Салаты
guide-entry-sauces = Приправы
guide-entry-cargo = Поставки
