ent-ClothingHandsGlovesColorPurple = фиолетовые перчатки
    .desc = Обычные фиолетовые перчатки, которые не спасут вас от поджаривания.
    .suffix = { "" }
ent-ClothingHandsGlovesColorRed = красные перчатки
    .desc = Обычные красные перчатки, которые не спасут вас от поджаривания.
    .suffix = { "" }
ent-ClothingHandsGlovesColorBlack = чёрные перчатки
    .desc = Обычные чёрные перчатки, которые не спасут вас от поджаривания.
    .suffix = { "" }
ent-ClothingHandsGlovesColorBlue = синие перчатки
    .desc = Обычные синие перчатки, которые не спасут вас от поджаривания.
    .suffix = { "" }
ent-ClothingHandsGlovesColorBrown = коричневые перчатки
    .desc = Обычные коричневые перчатки, которые не спасут вас от поджаривания.
    .suffix = { "" }
ent-ClothingHandsGlovesColorGray = серые перчатки
    .desc = Обычные серые перчатки, которые не спасут вас от поджаривания.
    .suffix = { "" }
ent-ClothingHandsGlovesColorGreen = зелёные перчатки
    .desc = Обычные зелёные перчатки, которые не спасут вас от поджаривания.
    .suffix = { "" }
ent-ClothingHandsGlovesColorLightBrown = светло-коричневые перчатки
    .desc = Обычные светло-коричневые перчатки, которые не спасут вас от поджаривания.
    .suffix = { "" }
ent-ClothingHandsGlovesColorOrange = оранжевые перчатки
    .desc = Обычные оранжевые перчатки, которые не спасут вас от поджаривания.
    .suffix = { "" }
ent-ClothingHandsGlovesColorWhite = белые перчатки
    .desc = Эти перчатки выглядят роскошно.
    .suffix = { "" }
ent-ClothingHandsGlovesColorRainbow = радужные перчатки
    .desc = Эти перчатки выглядят очень роскошно.
    .suffix = { "" }
ent-ClothingHandsGlovesColorYellow = изолированные перчатки
    .desc = Эти перчатки защищают пользователя от поражения электрическим током.
    .suffix = { "" }
ent-ClothingHandsGlovesColorYellowBudget = дешевые изолированные перчатки
    .desc = Всего лишь дешевая подделка заветных перчаток - не может быть, чтобы это плохо кончилось.
    .suffix = { "" }
ent-ClothingHandsGlovesAtmos = атмосферные спасательные перчатки
    .desc = Прочные перчатки для пожарных. Они толстые, негорючие и позволяют тащить людей быстрее.
    .suffix = { "" }
ent-ClothingHandsGlovesCE = продвинутые изолированные перчатки
    .desc = Эти перчатки имеют прекрасную тепловую и электрическую изоляцию. Они такие тонкие, что их почти не чувствуешь.
    .suffix = { "" }
