ent-ChessBoard = шахматная доска
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ChessBoardTabletop = шахматы
ent-BaseChessPiece = { ent-BaseItem }
ent-WhiteKing = белый король
ent-WhiteQueen = белый ферзь
ent-WhiteRook = белая ладья
ent-WhiteBishop = белый слон
ent-WhiteKnight = белый конь
ent-WhitePawn = белая пешка
ent-BlackKing = чёрный король
ent-BlackQueen = чёрный ферзь
ent-BlackRook = чёрная ладья
ent-BlackBishop = чёрный слон
ent-BlackKnight = чёрный конь
ent-BlackPawn = чёрная пешка
