ent-BaseTabletopPiece = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-RedTabletopPiece = красная фишка
ent-GreenTabletopPiece = зелёная фишка
ent-YellowTabletopPiece = жёлая фишка
ent-BlueTabletopPiece = синяя фишка
ent-WhiteTabletopPiece = белая фишка
ent-BlackTabletopPiece = чёрная фишка
