ent-ClothingEyesHudBeer = beer goggles
    .desc = A pair of sunHud outfitted with apparatus to scan reagents, as well as providing an innate understanding of liquid viscosity while in motion.
    .suffix = { "" }
ent-ClothingEyesHudFriedOnion = fried onion goggles
    .desc = Filler
    .suffix = { "" }
ent-ClothingEyesHudOnionBeer = thungerst goggles
    .desc = Filler
    .suffix = { "" }
ent-ClothingEyesHudMedOnion = medonion hud
    .desc = Filler
    .suffix = { "" }
ent-ClothingEyesHudMedOnionBeer = medthungerst hud
    .desc = Filler
    .suffix = { "" }
ent-ClothingEyesHudMedSec = medsec hud
    .desc = Filler
    .suffix = { "" }
ent-ClothingEyesHudMultiversal = multiversal hud
    .desc = Filler
    .suffix = { "" }
ent-ClothingEyesHudOmni = omni hud
    .desc = Filler
    .suffix = { "" }
