action-name-spin-web = Сплести паутину
action-desc-spin-web = Используйте вашу способность чтобы создать паутину. Повышает голод и жажду.
action-name-spin-web-space = Вы не можете плести в космосе!
action-name-spin-web-blocked = Недостаточно места под паутину.
spin-web-action-hungry = Вы слишком голодны для этого!
spin-web-action-thirsty = Вы испытываете сильную жажду для этого!
spin-web-start-second-person = Вы начинаете плести паутину.
spin-web-start-third-person = { CAPITALIZE(($spider)) } начинает плести паутину!
cocoon-start-second-person = Вы заковываете в кокон { ($target) }.
cocoon-start-third-person = { CAPITALIZE(($spider)) } начинает заковывать в кокон { ($target) }.
spun-web-second-person = Вы сплели паутину.
spun-web-third-person = { CAPITALIZE(($spider)) } слел паутину!
rest-on-web = Отдохнуть в паутине
cocoon = Кокон
