ent-CrateFunPlushie = ящик плюшевых игрушек
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-CrateFunInstruments = коллекция музыкальных инструментов
ent-CrateFunBrass = ящик духовых музыкальных инструментов
ent-CrateFunArtSupplies = художественные принадлежности
ent-CrateFunBoardGames = ящик настольных игр
ent-CrateFunATV = ящик с квадроциклом
ent-CrateFunSadTromboneImplants = ящик с имплантатами грустного тромбона
ent-CrateFunLightImplants = ящик с имплантатами света
ent-CrateFunParty = ящик с вечеринкой
ent-CrateFunSyndicateSegway = ящик с сегвеем синдиката
