ent-CrateMaterialGlass = ящик листов стекла
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-CrateMaterialSteel = ящик листов стали
ent-CrateMaterialTextiles = ящик текстиля
ent-CrateMaterialPlastic = ящик листов пластика
ent-CrateMaterialWood = ящик дерева
ent-CrateMaterialPlasteel = ящик листов пластали
ent-CrateMaterialPlasma = ящик твёрдой плазмы
