ent-CrateMedicalDefib = ящик с дефибриллятором
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-CrateMedicalSupplies = ящик медицинских припасов
ent-CrateChemistrySupplies = ящик химического оборудования
ent-CrateMedicalSurgery = ящик хирургических инструментов
ent-CrateMedicalScrubs = ящик медицинских роб
ent-CrateEmergencyBurnKit = аварийный набор лечения физических травм
ent-CrateEmergencyToxinKit = аварийный набор лечения токсинов
ent-CrateEmergencyO2Kit = аварийный набор лечения кислородного голодания
ent-CrateEmergencyBruteKit = аварийный набор лечения механических травм
ent-CrateEmergencyAdvancedKit = продвинутый аварийный набор
ent-CrateEmergencyRadiationKit = аварийный набор выведения радиации
