ent-CrateServiceJanitorialSupplies = ящик с уборочным инвентарем
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-CrateServiceReplacementLights = ящик запасных лампочек
ent-CrateMousetrapBoxes = ящик мышеловок
ent-CrateServiceSmokeables = ящик табачных изделий
ent-CrateServiceCustomSmokable = ящик табачных изделий (собери-сам)
ent-CrateServiceBureaucracy = ящик бюрократических припасов
ent-CrateServicePersonnel = ящик для найма персонала
