ent-Crayon = мелок
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-CrayonWhite = белый мелок
ent-CrayonMime = мимский мелок
ent-CrayonRainbow = радужный мелок
ent-CrayonBlack = чёрный мелок
ent-CrayonRed = красный мелок
ent-CrayonOrange = оранжевый мелок
ent-CrayonYellow = жёлтый мелок
ent-CrayonGreen = зелёный мелок
ent-CrayonBlue = синий мелок
ent-CrayonPurple = фиолетовый мелок
ent-CrayonBox = коробка для мелков
