ent-FoodPizzaCorncob = пицца из кукурузных початков
    .desc = Состряпана как больная шутка. Лучше всего подавать с жидким маслом.
    .suffix = { "" }
ent-FoodPizzaCorncobSlice = кусок пиццы из кукурузного початка
    .desc = Состряпана как больная шутка. Лучше всего подавать с жидким маслом.
    .suffix = { "" }
ent-FoodMothPizzaFirecracker = фейрверковая пицца
    .desc = Они не шутят, когда называют это горячей пиццей.
    .suffix = { "" }
ent-FoodMothPizzaFirecrackerSlice = кусок фейрверковой пиццы
    .desc = Пряный кусочек чего-то довольно приятного.
    .suffix = { "" }
ent-FoodMothPizzaFiveCheese = пицца четыре сыра 
    .desc = На протяжении веков ученые спрашивали; сколько сыра слишком много сыра?
    .suffix = { "" }
ent-FoodMothPizzaFiveCheeseSlice = кусок пиццы четыре сыра
    .desc = Это самый сырный кусок в галактике!
    .suffix = { "" }
ent-FoodMothPizzaPesto = пицца песто
    .desc = Песто — популярная начинка для пиццы молей, вполне возможно, потому, что она является примером их любимых вкусов; сыр, зелень и овощи.
    .suffix = { "" }
ent-FoodMothPizzaPestoSlice = кусок пиццы песто
    .desc = Зеленый, как трава в саду.
    .suffix = { "" }
ent-FoodMothPizzaCotton = хлопковая пицца
    .desc = Для одних преступление, для других вкусная пицца. Хлопок и сыр.
    .suffix = { "" }
ent-FoodMothPizzaCottonSlice = кусок хлопковой пиццы
    .desc = Белый как лист бумаги.
    .suffix = { "" }
