command-description-visualize = Принимает входной список сущностей и помещает их в отдельное окно для удобства просмотра.
command-description-runverbas = Выполняет Вёрб над введёнными сущностями с заданным пользователем.
command-description-acmd-perms = Возвращает права администратора для данной команды, если таковые имеются.
command-description-acmd-caninvoke = Проверяет, может ли данный игрок вызывать заданную команду.
command-description-jobs-jobs = Возвращает все работы, имеющиеся на станции.
command-description-jobs-job = Возвращает заданную работу на станции.
command-description-jobs-isinfinite = Возвращает true, если введённая работа безлимитна, иначе false.
command-description-jobs-adjust = Регулирует количество слотов для заданной работы.
command-description-jobs-set = Устанавливает количество слотов для заданной работы.
command-description-jobs-amount = Возвращает количество слотов для заданной работы.
command-description-stations-list = Возвращает список всех станций.
command-description-stations-get = Получает активную станцию, если и только если она всего одна.
command-description-stations-getowningstation = Получает станцию, которой "принадлежит" (в пределах) данный субъект.
command-description-stations-grids = Возвращает все гриды, связанные с вводом станциии.
command-description-stations-config = Возвращает конфигурацию, связанную c вводом станции, если таковая имеется.
command-description-stations-addgrid = Добавляет грид к заданной станции.
command-description-stations-rmgrid = Удаляет грид с заданной станции.
command-description-stations-rename = Переименовывает заданную станцию.
command-description-stations-largestgrid = Возвращает наибольший грид, который имеет заданная станция, если таковая имеется.
command-description-admins-active = Возвращает список активных администраторов.
command-description-admins-all = Возвращает список ВСЕХ администраторов, включая тех, что в дедмине.
command-description-marked = Возвращает значение $marked в виде Списка<EntityUid>.
command-description-rejuvenate = Реанимирует заданные сущности, восстанавливая их здоровье, снимая статус-эффекты и т.д.
command-description-tag-list = Списки тегов по заданным сущностям.
command-description-tag-add = Добавляет тэг к заданным сущностям.
command-description-tag-rm = Удаляет тэг с заданных сущностей.
command-description-tag-addmany = Добавляет список тегов к заданным сущностям.
command-description-tag-rmmany = Удаляет список тегов с заданных сущностей.
command-description-solution-get = Получает заданный раствор от заданной сущности.
