ent-PartHuman = часть тела человека
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-TorsoHuman = туловище человека
ent-HeadHuman = голова человека
ent-LeftArmHuman = левая рука человека
ent-RightArmHuman = правая рука человека
ent-LeftHandHuman = левая ладонь человека
ent-RightHandHuman = правая ладонь человека
ent-LeftLegHuman = левая нога человека
ent-RightLegHuman = правая нога человека
ent-LeftFootHuman = левая стопа человека
ent-RightFootHuman = правая стопа человека
