ent-PartReptilian = часть тела унатха
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-TorsoReptilian = туловище унатха
ent-HeadReptilian = голова унатха
ent-LeftArmReptilian = левая рука унатха
ent-RightArmReptilian = правая рука унатха
ent-LeftHandReptilian = левая ладонь унатха
ent-RightHandReptilian = правая ладонь унатха
ent-LeftLegReptilian = левая нога унатха
ent-RightLegReptilian = правая нога унатха
ent-LeftFootReptilian = левая стопа унатха
ent-RightFootReptilian = правая стопа унатха
