ent-PartSkeleton = часть тела скелет
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-TorsoSkeleton = туловище скелета
ent-HeadSkeleton = череп
ent-LeftArmSkeleton = левая рука скелета
ent-RightArmSkeleton = правая рука скелета
ent-LeftHandSkeleton = левая кисть скелета
ent-RightHandSkeleton = правая кисть скелета
ent-LeftLegSkeleton = левая нога скелета
ent-RightLegSkeleton = правая нога скелета
ent-LeftFootSkeleton = левая стопа скелета
ent-RightFootSkeleton = правая стопа скелета
