ent-PartSlime = slime body part
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-TorsoSlime = slime torso
ent-HeadSlime = slime head
ent-LeftArmSlime = left slime arm
ent-RightArmSlime = right slime arm
ent-LeftHandSlime = left slime hand
ent-RightHandSlime = right slime hand
ent-LeftLegSlime = left slime leg
ent-RightLegSlime = right slime leg
ent-LeftFootSlime = left slime foot
ent-RightFootSlime = right slime foot
