ent-PartVox = часть тела вокса
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-TorsoVox = туловище вокса
ent-HeadVox = голова вокса
ent-LeftArmVox = левая рука вокса
ent-RightArmVox = правая рука вокса
ent-LeftHandVox = левая ладонь вокса
ent-RightHandVox = правая ладонь вокса
ent-LeftLegVox = левая нога вокса
ent-RightLegVox = правая нога вокса
ent-LeftFootVox = левая стопа вокса
ent-RightFootVox = правая стопа вокса
