ent-BookSpaceEncyclopedia = space encyclopedia
    .desc = An encyclopedia containing all the knowledge. The author of this encyclopedia is unknown.
    .suffix = { "" }
ent-BookTheBookOfControl = the book of control
    .desc = Essential to become robust.
    .suffix = { "" }
ent-BookBartendersManual = bartender's manual
    .desc = This manual is stained with beer.
    .suffix = { "" }
ent-BookChefGaming = chef gaming
    .desc = A book about cooking written by a gamer chef.
    .suffix = { "" }
ent-BookLeafLoversSecret = leaf lover's secret
    .desc = It has a strong weed smell. It motivates you to feed and seed.
    .suffix = { "" }
ent-BookEngineersHandbook = engineer's handbook
    .desc = A handbook about engineering written by Nanotrasen.
    .suffix = { "" }
ent-BookScientistsGuidebook = scientist's guidebook
    .desc = A guidebook about science written by Nanotrasen.
    .suffix = { "" }
ent-BookSecurity = security 101
    .desc = A book about security written by Nanotrasen. The book is stained with blood. It seems to have been used more as a weapon than reading material.
    .suffix = { "" }
ent-BookHowToKeepStationClean = how to keep station clean
    .desc = This book is very clean.
    .suffix = { "" }
ent-BookHowToRockAndStone = how to rock and stone
    .desc = A very detailed guide about salvage written by Karl, a legendary space miner, however he's missing. It motivates you to rock and stone.
    .suffix = { "" }
ent-BookMedicalReferenceBook = medical reference book
    .desc = A reference book about medical written by an old doctor. The handwriting is barely comprehensible.
    .suffix = { "" }
ent-BookHowToSurvive = how to survive
    .desc = Ironically the author of this book is dead.
    .suffix = { "" }
ent-BookChemicalCompendium = chempendium
    .desc = A comprehensive guide written by some old skeleton of a professor about chemical synthesis.
    .suffix = { "" }
