ent-ClosetWall = технический настенный шкаф
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClosetWallEmergency = аварийный настенный шкаф
ent-ClosetWallFire = противопожарный настенный шкаф
ent-ClosetWallBlue = синий настенный шкаф
ent-ClosetWallPink = розовый настенный шкаф
ent-ClosetWallBlack = чёрный настенный шкаф
ent-ClosetWallGreen = зелёный настенный шкаф
ent-ClosetWallOrange = тюремный настенный шкаф
ent-ClosetWallYellow = жёлтый настенный шкаф
ent-ClosetWallWhite = белый настенный шкаф
ent-ClosetWallGrey = серый настенный шкаф
ent-ClosetWallMixed = смешанный настенный шкаф
ent-ClosetWallAtmospherics = атмосферный настенный шкаф
ent-LockerWallMedical = врачебный настенный шкаф
