reagent-desc-soju = Алкогольный напиток, приготовленный путем перегонки полированного риса.
reagent-name-orange-creamcicle = апельсиновый крем
reagent-desc-orange-creamcicle = Оранжевое, сливочное совершенство.
reagent-name-silverjack = Сильверджек
reagent-desc-silverjack = Напоминает вам о семье.
reagent-name-brainbomb = мозговая бомба
reagent-desc-brainbomb = Токсично для всего живого, особенно для вашей печени.
reagent-name-clownblood = кровь клоуна
reagent-desc-clownblood = Любимый напиток сотрудников службы безопасности после долгого дня.
reagent-name-circusjuice = цирковой сок
reagent-desc-circusjuice = Хонкмать будет рада.
reagent-name-sapopicante = Сапо Пиканте
reagent-desc-sapopicante = Вкус никак не похож на жабу.
reagent-name-graveyard = кладбище
reagent-desc-graveyard = Для тех смен, которые никогда не заканчиваются.
