ent-DrinkCanBaseFull = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-DrinkColaCan = космическая кола
ent-DrinkIcedTeaCan = банка холодного чая
ent-DrinkLemonLimeCan = банка лимон-лайма
ent-DrinkGrapeCan = банка виноградной газировки
ent-DrinkRootBeerCan = банка рутбира
ent-DrinkSodaWaterCan = банка газированной воды
ent-DrinkSpaceMountainWindCan = банка космического маунтин винда
ent-DrinkSpaceUpCan = банка спейс-ап
ent-DrinkStarkistCan = банка старкист
ent-DrinkTonicWaterCan = банка тоника
ent-DrinkFourteenLokoCan = банка Фоуртин Локо
ent-DrinkChangelingStingCan = банка Жала генокрада
ent-DrinkDrGibbCan = банка доктора Гибба
ent-DrinkEnergyDrinkCan = банка энергетика Ред Булеан
ent-DrinkCanPack = 6штук
