ent-DrinkBaseCup = base cup
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-DrinkGoldenCup = золотая чаша
ent-DrinkBaseMug = mug
ent-DrinkMug = кружка
ent-DrinkMugBlack = чёрная кружка
ent-DrinkMugBlue = синяя кружка
ent-DrinkMugGreen = зелёная кружка
ent-DrinkMugDog = кружка со смешной собакой
ent-DrinkMugHeart = кружка с сердцем
ent-DrinkMugMetal = металлическая кружка
ent-DrinkMugMoebius = кружка мёбиус
ent-DrinkMugOne = кружка #1
ent-DrinkMugRainbow = радужная кружка
ent-DrinkMugRed = красная кружка
ent-DrinkHotCoco = кружка горячего шоколада
ent-DrinkHotCoffee = кружка кофе
ent-DrinkTeacup = чашка чая
ent-DrinkLean = лин
ent-DrinkWaterCup = стаканчик воды
