ent-DrinkBottleBaseEmpty = base empty bottle
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-DrinkBottleAbsinthe = бутылка от Джейлбрейк Верте
ent-DrinkBottleAlcoClear = бутылка от спиртного
ent-DrinkBottleAle = бутылка от эля
ent-DrinkBottleBeer = пивная бутылка
ent-DrinkBottleCognac = бутылка от коньяка
ent-DrinkBottleGin = бутылка от джина Гриффитер
ent-DrinkBottleGoldschlager = бутылка от гольдшлягера
ent-DrinkBottleCoffeeLiqueur = бутылка от кофейного ликёра
ent-DrinkBottleNTCahors = бутылка от кагора
ent-DrinkBottlePatron = бутылка от покровителя
ent-DrinkBottlePoisonWine = бутылка от ядовитого вина
ent-DrinkBottleRum = бутылка от рома
ent-DrinkBottleTequila = бутылка от текилы
ent-DrinkBottleVermouth = бутылка от вермута
ent-DrinkBottleVodka = бутылка от водки
ent-DrinkBottleWhiskey = бутылка от виски
ent-DrinkBottleWine = бутылка от вина
