ent-Haycutters = сенорез
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-Moodriver = коровёртка
ent-Wronch = коровий ключ
ent-Cowbar = монтикоровка
ent-Mooltitool = муультитул
ent-Cowelder = коровочный аппарат
ent-Milkalyzer = молокоанализатор
ent-CowToolbox = коровий ящик для инструментов
ent-CowToolboxFilled = коровий ящик для инструментов
