ent-GlowstickBase = зелёный химсвет
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-GlowstickRed = красный химсвет
ent-GlowstickPurple = фиолетовый химсвет
ent-GlowstickYellow = жёлтый химсвет
ent-GlowstickBlue = синий химсвет
ent-LightBehaviourTest1 = light pulse test
ent-LightBehaviourTest2 = color cycle test
ent-LightBehaviourTest3 = multi-behaviour light test
ent-LightBehaviourTest4 = light fade in test
ent-LightBehaviourTest5 = light pulse radius test
ent-LightBehaviourTest6 = light randomize radius test
