ent-ToolboxBase = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ToolboxEmergency = аварийный ящик для инструментов
ent-ToolboxMechanical = технический ящик для инструментов
ent-ToolboxElectrical = электротехнический ящик для инструментов
ent-ToolboxArtistic = художественный ящик для инструментов
ent-ToolboxSyndicate = подозрительный ящик для инструментов
ent-ToolboxGolden = золотой ящик для инструментов
