ent-ShogiBoard = shogi board
    .desc = A board for playing the game Shogi, Japanese chess.
    .suffix = { "" }
ent-ShogiBoardTabletop = shogi board
    .desc = { "" }
    .suffix = { "" }
ent-BaseShogiPiece = { ent-BaseItem }
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-ShogiBishop = bishop
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiGold = gold general
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiKing = king
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiKingJeweled = king
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiKnight = knight
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiLance = lance
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiPawn = pawn
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiRook = rook
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiSilver = silver general
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiBishopPromoted = bishop
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiKnightPromoted = knight
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiLancePromoted = lance
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiPawnPromoted = pawn
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiRookPromoted = rook
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiSilverPromoted = silver general
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
