ent-AmeController = AME controller
    .desc = It's a controller for the antimatter engine.
    .suffix = { "" }
ent-AmeControllerUnanchored = { ent-AmeController }
    .suffix = Unanchored
    .desc = { ent-AmeController.desc }
ent-AmeShielding = AME shielding
    .desc = Keeps the antimatter in and the matter out.
    .suffix = { "" }
