ent-TableFrame = каркас стола
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-CounterWoodFrame = деревянный каркас стойки
ent-CounterMetalFrame = металлический каркас стойки
ent-Table = стол
ent-TableReinforced = укреплённый стол
ent-TableGlass = стеклянный стол
ent-TableReinforcedGlass = стол из бронестекла
ent-TablePlasmaGlass = стол из плазменного стекла
ent-TableWood = деревянный стол
ent-TableCarpet = игорный стол
ent-TableStone = каменный стол
ent-TableDebug = table
ent-TableCounterWood = деревянная стойка
ent-TableCounterMetal = металлическая стойка
