ent-FoodCannabisButter = stick of cannabis butter
ent-FoodCurdCheese = curd cheese
ent-FoodCheeseCurds = cheese curds
ent-FoodMozzarella = mozzarella cheese
ent-FoodMothHerbyCheese = herby cheese
ent-FoodMothSaladBase = mothic salad
ent-BaseFoodMothSauce = sauce bowl
ent-FoodMothTomatoSauce = tomato sauce
ent-FoodMothPesto = pesto sauce
ent-FoodMothBechamel = bechamel sauce
