ent-FoodPSBTrash = psb wrapper
ent-FoodPSB = prepacked sustenance bar
ent-FoodPSBBase = { ent-FoodSnackBase }
ent-FoodPSBBarSoy = soy sustenance bar
ent-FoodPSBBarNeapolitan = neapolitan sustenance bar
ent-FoodPSBBarBrownie = brownie sustenance bar
ent-FoodPSBBarCheese = cheese sustenance bar
ent-FoodPSBBarMeat = meat sustenance bar
ent-FoodPSBBarVegetable = vegetable sustenance bar
ent-FoodPSBBarMint = mint sustenance bar
ent-FoodPSBBarBanana = banana sustenance bar
ent-FoodPSBBarWonka = wonka sustenance bar
