ent-FoodMothCottonSoup = cotton soup
ent-FoodMothCheeseSoup = cheese soup
ent-FoodMothSeedSoup = seed soup
ent-FoodMothEyeballSoup = moth eyeball soup
ent-FoodMothBeanStew = bean stew
ent-FoodMothOatStew = oat stew
ent-FoodMothHeartburnSoup = heartburn soup
ent-FoodMothHuaMulanCongee = mulan congee
ent-FoodMothCornmealPorridge = cornmeal porridge
ent-FoodMothCheesyPorridge = cheesy porridge
ent-FoodMothEggplantPolenta = fried eggplant and polenta
ent-FoodMothVegetarianChili = vegetarian chili
