ent-BaseSpellbook = книга заклинаний
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-SpawnSpellbook = книга заклинания призыв
ent-ForceWallSpellbook = книга заклинания силовой барьер
ent-BlinkBook = книга заклинания прыжок
ent-SmiteBook = книга заклинания кара
ent-KnockSpellbook = книга заклинания стук
ent-FireballSpellbook = книга заклинания огненный шар
ent-ScrollRunes = свиток рун
