marking-FelinidEarsDefault = Кошачьи ушки
marking-FelinidEarsDefault-ears_default_outer = Внешняя часть
marking-FelinidEarsDefault-ears_default_inner = Внутренняя часть
marking-FelinidEarsStatic = Кошачьи ушки (Статичные)
marking-FelinidEarsStatic-ears_static_outer = Внешняя часть
marking-FelinidEarsStatic-ears_static_inner = Внутренняя часть
marking-FelinidTailStatic = Кошачий хвост (Статичный)
marking-FelinidTailStatic-tail_static = Хвост
marking-FelinidTailDefault = Кошачий хвост (Классический)
marking-FelinidTailDefault-tail_default = Хвост
marking-FelinidTailResprite = Кошачий хвост
marking-FelinidTailResprite-tail_resprite = Хвост
