ent-ClothingUniformJumpsuitRecruitNT = recruit jumpsuit
    .desc = A classy grey jumpsuit with blue trims. Perfect for the dignified helper.
    .suffix = { "" }
ent-ClothingUniformJumpsuitRecruitSyndie = syndicate recuit jumpsuit
    .desc = A dubious,, dark-grey jumpsuit. As if passengers weren't dubious enough already.
    .suffix = { "" }
ent-ClothingUniformJumpsuitRepairmanNT = repairman jumpsuit
    .desc = A jumpsuit that reminds you of a certain crew-sector work position. Hopefully, you won't have to do the same job as THOSE freaks.
    .suffix = { "" }
ent-ClothingUniformJumpsuitRepairmanSyndie = syndicate repairman jumpsuit
    .desc = Functional, fashionable, and badass. Nanotrasen's engineers wish they could look as good as this.
    .suffix = { "" }
ent-ClothingUniformJumpsuitParamedicNT = paramedic jumpsuit
    .desc = A basic white & blue jumpsuit made for Nanotrasen paramedics stationed in combat sectors.
    .suffix = { "" }
ent-ClothingUniformJumpsuitParamedicSyndie = syndicate paramedic jumpsuit
    .desc = For some reason, wearing this makes you feel like you're awfully close to violating the Geneva Convention.
    .suffix = { "" }
ent-ClothingUniformJumpsuitChiefEngineerNT = chief engineer jumpsuit
    .desc = It is often joked that the role of the combat-sector Chief Engineer is where the actual, logistically-minded engineers are promoted to. Good luck.
    .suffix = { "" }
ent-ClothingUniformJumpsuitChiefEngineerSyndie = syndicate chief engineer jumpsuit
    .desc = An evil-looking jumpsuit with a reflective vest & red undershirt.
    .suffix = { "" }
