ent-MobGolemBase = golem
    .desc = An artificial construct imitating life. This one has no soul installed yet.
    .suffix = { "" }
ent-MobGolemCult = golem
    .suffix = shell
    .desc = { ent-MobGolemBase.desc }
ent-MobGolemWood = wood golem
    .desc = An artificial construct imitating life. This one has no soul installed yet.
    .suffix = { "" }
