ent-ClothingCostumeNaota = бирюзовые худи и шорты
    .desc = Толстовка с маленьким мешочком-кенгуру.
    .suffix = { "" }
ent-ClothingUniformRat = наряд фаната крысиного короля
    .desc = Заявите о своей верности монарху грызунов, а также о своем желании увидеть, как станция горит *одновременно!*
    .suffix = { "" }
ent-ClothingUniformDressRed = красное платье
    .desc = Объемное нарядное красное платье.
    .suffix = { "" }
ent-ClothingUniformSwimsuitBlue = синий купальник
    .desc = Облегающий гидродинамичный синий купальник.
    .suffix = { "" }
ent-ClothingUniformSchoolGakuranBlack = форма гакуран
    .desc = Шикарная школьная форма.
    .suffix = { "" }
