ent-ClothingUniformJumpsuitExplorer = униформа исследователя
    .desc = Прочный комбинезон для путешествий по звездам.
    .suffix = { "" }
ent-ClothingOuterExplorerCoat = лабораторный халат исследователя
    .desc = Похоже, он повидал немало пыльных троп.
    .suffix = { "" }
ent-ClothingUniformTShirtKhakiPants = серая футболка и брюки цвета хаки
    .desc = Какая-то серая, но функциональная одежда.
    .suffix = { "" }
