ent-WeaponTetherGun = гравитационная пушка
    .desc = Управляет гравитацией вокруг объектов, чтобы швырять их с высокой скоростью.
    .suffix = { "" }
ent-WeaponForceGun = силовая пушка
    .desc = Управляет гравитацией вокруг объектов, чтобы швырять их с высокой скоростью.
    .suffix = { "" }
ent-WeaponGrapplingGun = крюк-кошка
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-WeaponTetherGunAdmin = гравитационная пушка
    .desc = Управляет гравитацией вокруг объектов, чтобы швырять их с высокой скоростью.
    .suffix = admin
ent-WeaponForceGunAdmin = силовая пушка
    .desc = Управляет гравитацией вокруг объектов, чтобы швырять их с высокой скоростью.
    .suffix = Admin
