ent-ForensicMantisIDCard = ID карта детектива
    .desc = { ent-IDCardStandard.desc }
    .suffix = { "" }
ent-EpistemicsIDCard = ID карта аколита
    .desc = { ent-IDCardStandard.desc }
    .suffix = { "" }
ent-MystaIDCard = ID карта мистагога
    .desc = { ent-IDCardStandard.desc }
    .suffix = { "" }
ent-SalvageTechIDCard = { ent-EngineeringIDCard }
    .desc = { ent-EngineeringIDCard.desc }
    .suffix = { "" }
ent-MailCarrierIDCard = ID карта почтальона
    .desc = { ent-IDCardStandard.desc }
    .suffix = { "" }
ent-PrisonerIDCard = ID карта заключенного
    .desc = { ent-IDCardStandard.desc }
    .suffix = { "" }
ent-GladiatorIDCard = ID карта гладиатора
    .desc = { ent-IDCardStandard.desc }
    .suffix = { "" }
ent-ValetIDCard = ID карта сервисного работника
    .desc = { ent-IDCardStandard.desc }
    .suffix = { "" }
ent-CataloguerIDCard = ID карта каталогизатора
    .desc = { ent-IDCardStandard.desc }
    .suffix = { "" }
ent-GuardIDCard = ID карта охранника
    .desc = { ent-IDCardStandard.desc }
    .suffix = { "" }
ent-MartialArtistIDCard = ID карта мастера боевых искусств
    .desc = { ent-IDCardStandard.desc }
    .suffix = { "" }
ent-UnaffiliatedIDCard = неаффилированная ID карта
    .desc = Карточка с именем и другими идентификационными данными.
    .suffix = { "" }
ent-ExplorerIDCard = ID исследователя
    .desc = { ent-UnaffiliatedIDCard.desc }
    .suffix = { "" }
ent-StudentIDCard = ID карта студента
    .desc = { ent-UnaffiliatedIDCard.desc }
    .suffix = { "" }
ent-FreelancerIDCard = ID карта фрилансера
    .desc = { ent-UnaffiliatedIDCard.desc }
    .suffix = { "" }
