ent-BaseGateway = врата
    .desc = Загадочные врата, неизвестно кем созданные, позволяют путешествовать в самые отдалённые места галактики со сверхсветовой скоростью.
    .suffix = { "" }
ent-Gateway = { ent-BaseGateway }
    .desc = { ent-BaseGateway.desc }
    .suffix = { "" }
ent-GatewayDestination = { ent-BaseGateway }
    .suffix = Пункт назначения
    .desc = { ent-BaseGateway.desc }
