research-discipline-none = None
research-discipline-industrial = Промышленность
research-discipline-biochemical = Биохимическая
research-discipline-arsenal = Арсенал
research-discipline-experimental = Экспериментальный
research-discipline-civilian-services = Гражданские службы
research-technology-salvage-equipment = Утилизационное оборудование
research-technology-advanced-powercells = Продвинутые элементы питания
research-technology-compact-power = Компактная энергия
research-technology-industrial-engineering = Примышленная инженерия
research-technology-power-generation = Выработка энергии
research-technology-atmospheric-tech = Атмосфера
research-technology-rapid-construction = Быстрое строительство
research-technology-shuttlecraft = Строительство шаттла
research-technology-ripley-aplu = РИПЛИ
research-technology-advanced-atmospherics = Продвинутая атмосфера
research-technology-advanced-tools = Продвинутые инструенты
research-technology-super-powercells = Супер элементы питания
research-technology-bluespace-storage = Блюспейс хранение
research-technology-chemistry = Химия
research-technology-surgical-tools = Хирургия
research-technology-biochemical-stasis = Биохимический стазис
research-technology-virology = Вирусология
research-technology-cryogenics = Криогеника
research-technology-chemical-dispensary = Раздатчик химикатов
research-technology-crew-monitoring = Монитор экипажа
research-technology-cloning = Кланирование
research-technology-salvage-weapons = Оружие утилизаторов
research-technology-draconic-munitions = Драконьи боеприпасы
research-technology-explosive-technology = Технология взравчатки
research-technology-advanced-laser-manipulation = Продвинутый лазерный манипулятор
research-technology-nonlethal-ammunition = Нелетальные боеприпасы
research-technology-optimized-ballistics = Оптимизированная баллистика
research-technology-concentrated-laser-weaponry = Концентрированное лазерное оружие
research-technology-wave-particle-harnessing = Использование волновых частиц
research-technology-handheld-electrical-propulsion = Портативный электрический привод
research-technology-basic-robotics = Базовая робототехника
research-technology-basic-anomalous-research = Базовое исследование аномалий
research-technology-basic-xenoarcheology = Базовая ксеноархеология
research-technology-alternative-research = Альтернативные исследования
research-technology-magnets-tech = Локализованный магнетизм
research-technology-advanced-parts = Продвинутые части
research-technology-grappling = Крюк
research-technology-abnormal-artifact-manipulation = Манипуляции с аномальными артефактами
research-technology-gravity-manipulation = Управление гравитацией
research-technology-mobile-anomaly-tech = Технология мобильных аномалий
research-technology-rped = Быстрая замена деталей
research-technology-super-parts = Супер части
research-technology-janitorial-equipment = Уборочное оборудование
research-technology-laundry-tech = Прачечная
research-technology-basic-hydroponics = Базовая гидропоника
research-technology-food-service = Общественное питание
research-technology-advanced-entertainment = Продвинутые развлечения
research-technology-audio-visual-communication = Звуковые/Видео коммуникации
research-technology-advanced-cleaning = Продвинутая чистка
research-technology-meat-manipulation = Манипуляции с мясом
research-technology-honk-mech = Х.О.Н.К. мех
research-technology-advanced-spray = Продвинутый спрей
research-technology-bluespace-cargo-transport = Блюспейс карго транспорт
