ent-DoorRemoteDefault = пульт от дверей
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-DoorRemoteCommand = пульт от дверей командования
ent-DoorRemoteSecurity = пульт от дверей отдела СБ
ent-DoorRemoteArmory = пульт от дверей оружейной
ent-DoorRemoteService = пульт от дверей отделов сервиса
ent-DoorRemoteResearch = пульт от дверей научного отдела
ent-DoorRemoteCargo = пульт от дверей карго
ent-DoorRemoteMedical = пульт от дверей медотсека
ent-DoorRemoteEngineering = пульт от дверей инженерного отдела
