ent-EncryptionKey = ключ шифрования
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-EncryptionKeyCommon = ключ шифрования общий
ent-EncryptionKeyCargo = ключ шифрования карго
ent-EncryptionKeyCentCom = ключ шифрования ЦентКом
ent-EncryptionKeyStationMaster = station master encryption key
ent-EncryptionKeyCommand = ключ шифрования командования
ent-EncryptionKeyEngineering = ключ шифрования инженерии
ent-EncryptionKeyMedical = ключ шифрования медицинского отдела
ent-EncryptionKeyMedicalScience = ключ шифрования науч-мед отдела
ent-EncryptionKeyScience = ключ шифрования научного отдела
ent-EncryptionKeyRobo = ключ шифрования отдела робототехники
ent-EncryptionKeySecurity = ключ шифрования службы безопасности
ent-EncryptionKeyService = ключ шифрования сервиса
ent-EncryptionKeySyndie = кроваво-красный ключ шифрования
