ent-ClothingNeckScarfStripedBlack = striped black scarf
    .desc = A stylish striped black scarf. The perfect winter accessory for those with a keen fashion sense, and those who just can't handle a cold breeze on their necks.
    .suffix = { "" }
ent-ClothingNeckScarfStripedBrown = striped brown scarf
    .desc = A stylish striped brown scarf. The perfect winter accessory for those with a keen fashion sense, and those who just can't handle a cold breeze on their necks.
    .suffix = { "" }
ent-ClothingNeckScarfStripedLightBlue = striped light blue scarf
    .desc = A stylish striped light blue scarf. The perfect winter accessory for those with a keen fashion sense, and those who just can't handle a cold breeze on their necks.
    .suffix = { "" }
ent-ClothingNeckScarfStripedOrange = striped orange scarf
    .desc = A stylish striped orange scarf. The perfect winter accessory for those with a keen fashion sense, and those who just can't handle a cold breeze on their necks.
    .suffix = { "" }
ent-ClothingNeckScarfStripedPurple = striped purple scarf
    .desc = A stylish striped purple scarf. The perfect winter accessory for those with a keen fashion sense, and those who just can't handle a cold breeze on their necks.
    .suffix = { "" }
ent-ClothingNeckScarfStripedSyndieGreen = striped syndicate green scarf
    .desc = A stylish striped syndicate green scarf. The perfect winter accessory for those with a keen fashion sense, and those who are in the mood to steal something.
    .suffix = { "" }
ent-ClothingNeckScarfStripedSyndieRed = striped syndicate red scarf
    .desc = A stylish striped syndicate red scarf. The perfect winter accessory for those with a keen fashion sense, and those who are in the mood to steal something.
    .suffix = { "" }
ent-ClothingNeckScarfStripedCentcom = striped CentCom scarf
    .desc = A stylish striped centcom colored scarf. The perfect winter accessory for those with a keen fashion sense, and those who need to do paperwork in the cold.
    .suffix = { "" }
