ent-ClothingBackpackDuffelSurgeryFilled = хирургический вещмешок
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingBackpackDuffelCBURN = вещмешок отряда РХБЗЗ
ent-ClothingBackpackDuffelSyndicateFilledMedical = хирургический вещмешок синдиката
ent-ClothingBackpackDuffelSyndicateFilledShotgun = набор "Бульдог"
ent-ClothingBackpackDuffelSyndicateFilledSMG = набор "C-20r"
ent-ClothingBackpackDuffelSyndicateFilledRevolver = набор "Питон"
ent-ClothingBackpackDuffelSyndicateFilledLMG = набор "L6 Saw"
ent-ClothingBackpackDuffelSyndicateFilledGrenadeLauncher = набор "Чайна-Лэйк"
ent-ClothingBackpackDuffelSyndicateFilledCarbine = набор "М-90gl"
ent-ClothingBackpackDuffelSyndicateCostumeCentcom = вещмешок с костюмом представителя Центкома
ent-ClothingBackpackDuffelSyndicateCostumeClown = { ent-ClothingBackpackDuffelClown }
ent-ClothingBackpackDuffelSyndicatePyjamaBundle = вещмешок пижам синдиката
ent-ClothingBackpackDuffelSyndicateC4tBundle = набор C-4 синдиката
ent-ClothingBackpackChameleonFill = { ent-ClothingBackpackChameleon }
ent-ClothingBackpackDuffelSyndicateEVABundle = набор EVA синдиката
ent-ClothingBackpackDuffelSyndicateHardsuitBundle = набор скафандров синдиката
ent-ClothingBackpackDuffelZombieBundle = зомби набор синдиката
ent-ClothingBackpackDuffelSyndicateOperative = вещмешок оперативника
ent-ClothingBackpackDuffelSyndicateOperativeMedic = вещмешок оперативника-медика
