ent-Smoke = smoke
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-Foam = foam
ent-IronMetalFoam = железная металлическая пена
ent-AluminiumMetalFoam = алюминиевая металлическая пена
ent-BaseFoamedMetal = base foamed metal
ent-FoamedIronMetal = вспененное железо
ent-FoamedAluminiumMetal = вспененный алюминий
