ent-PuddleBase = { "" }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-EvaporatingPuddle = { ent-PuddleBase }
ent-PuddleGibblet = потроха
ent-PuddleSmear = лужа
ent-PuddleSplatter = лужа
ent-PuddleBlood = кровь
ent-PuddleVomit = рвота
ent-PuddleVomitToxin = рвотные токсины
ent-PuddleWriting = пишущий
