ent-PosterLegitDejaVu = Deja Vu
    .desc = Это твой первый раз здесь. Если эта станция кажется знакомой, немедленно сообщите сотруднику Нянотрайзен.
    .suffix = { "" }
ent-PosterLegitDontPanic = Без паники!
    .desc = Если все было достаточно спокойно, чтобы у меня нету паники. Это зеленый сгусток слизи с руками? Светящийся красный язык? Летающие зубы?
    .suffix = { "" }
ent-PosterContrabandSaucerNumberOne = Saucer #1!
    .desc = Out of every station in the NyanoTrasen jurisdiction, Saucer was rated #1 out of 5! Congratulations!
    .suffix = { "" }
ent-PosterLegitBarDrinks = Барный постер
    .desc = Бармен всегда готов выслушать и поддержать вас. Заходи!
    .suffix = { "" }
ent-PosterLegitBotanyFood = Фруктовая тарелка
    .desc = Ботаники всегда упорно трудятся! Остановись и попробуй что они предлагают!
    .suffix = { "" }
ent-PosterContrabandBreadLies = Хлеб врет!
    .desc = Вам врут. Нет никакого "Большого хлеба". ЕГО НЕТ! Перестаньте искать его.
    .suffix = { "" }
ent-PosterLegitHotDonkExplosion = Donk!
    .desc = Почувствуйте взрыв вкуса в каждом кусочке нашей продукции! DONK!
    .suffix = { "" }
ent-PosterLegitEatMeat = Ешь мясо!
    .desc = Кому нужны фрукты или овощи? ЕШЬ МЯСО! Отрасти мышцы, которыми можно свергнуть гиганта!
    .suffix = { "" }
ent-PosterLegitMoreBread = Больше хлеба!
    .desc = Никогда не достаточно хлеба! ДЕЛАЙ БОЛЬШЕ!
    .suffix = { "" }
ent-PosterLegitPieSlice = Пирог
    .desc = Пироги вкусные и полезные! Уговори повора сделать несколько.
    .suffix = { "" }
ent-PosterLegitPizzaHope = Надежда пиццы
    .desc = В темные времена есть лишь одна надежда, ПИЦЦА! Немедленно уговори квартермейстера заказать несколько коробок!
    .suffix = { "" }
ent-PosterLegitMedicate = Прими лекарства!
    .desc = Возможные побочные эффекты: амнезия, несварение желудка, анемия, зуд, температура, головные боли, тошнота и многие другие.
ent-PosterLegitNoTouching = Не трогать!
    .desc = Сказали же, не трогать!
    .suffix = { "" }
