cargo-gifts-event-announcement = Поздравляем! { $sender } решил отправить на станцию { $description } в { $dest }. Вы сможете это найти в следующей партии груза на карго шаттле.
cargo-gift-default-description = Набор подарков
cargo-gift-default-sender = NanoTrasen
cargo-gift-default-dest = отдел Карго.
cargo-gift-dest-bar = Бар
cargo-gift-dest-eng = Инженерный отдел
cargo-gift-dest-supp = отдел Карго
cargo-gift-dest-janitor = Сервисный отдел
cargo-gift-dest-med = Медицинской отдел
cargo-gift-dest-sec = отдел Службы безопасности
cargo-gift-pizza-small = Небольшую пицца-вечеринку
cargo-gift-pizza-large = Большую пицца-вечеринку
cargo-gift-eng = Ремонтные материалы
cargo-gift-vending = Пополнение торгоматов
cargo-gift-cleaning = Уборочное оборудование
cargo-gift-medical-supply = Медицинские принадлежности
cargo-gift-space-protection = Защиту от космической угрозы
cargo-gift-fire-protection = Противопожарную защиту
cargo-gift-security-guns = Летальное оружие
cargo-gift-security-riot = Защитное снаряжение
