ent-ClothingHeadHatBeretMerc = mercenary beret
    .desc = Olive beret, the badge depicts a jackal on a rock.
    .suffix = { "" }
ent-ClothingHeadHatSyndie = syndicate hat
    .desc = A souvenir hat from "Syndieland", their production has already been closed.
    .suffix = { "" }
ent-ClothingHeadHatSyndieMAA = master at arms hat
    .desc = Master at arms hat, looks intimidating, I doubt that you will like to communicate with its owner...
    .suffix = { "" }
ent-ClothingHeadHatTacticalMaidHeadband = tactical maid headband
    .desc = A red headband - don't imagine yourself a Rambo and don't pick up a few machine guns.
    .suffix = { "" }
ent-ClothingHeadHatMagician = magician's top hat.
    .desc = A magician's top hat.
    .suffix = { "" }
ent-ClothingHeadHatCapcap = cap cap
    .desc = A grand, stylish captain cap.
    .suffix = { "" }
