ent-ClothingHeadHelmetBasic = helmet
    .desc = Standard security gear. Protects the head from impacts.
    .suffix = { "" }
ent-ClothingHeadHelmetMerc = mercenary helmet
    .desc = The combat helmet is commonly used by mercenaries, is strong, light and smells like gunpowder and the jungle.
    .suffix = { "" }
ent-ClothingHeadHelmetSwat = SWAT helmet
    .desc = An extremely robust helmet, commonly used by paramilitary forces. This one has the Nanotrasen logo emblazoned on the top.
    .suffix = { "" }
ent-ClothingHeadHelmetSwatSyndicate = SWAT helmet
    .desc = An extremely robust helmet, commonly used by paramilitary forces. It is adorned in a nefarious red and black stripe pattern.
    .suffix = Syndicate
ent-ClothingHeadHelmetERTLeader = ERT leader helmet
    .desc = An in-atmosphere helmet worn by the leader of a Nanotrasen Emergency Response Team. Has blue highlights.
    .suffix = { "" }
ent-ClothingHeadHelmetERTSecurity = ERT security helmet
    .desc = An in-atmosphere helmet worn by security members of the Nanotrasen Emergency Response Team. Has red highlights.
    .suffix = { "" }
ent-ClothingHeadHelmetERTMedic = ERT medic helmet
    .desc = An in-atmosphere helmet worn by medical members of the Nanotrasen Emergency Response Team. Has white highlights.
    .suffix = { "" }
ent-ClothingHeadHelmetERTEngineer = ERT engineer helmet
    .desc = An in-atmosphere helmet worn by engineering members of the Nanotrasen Emergency Response Team. Has orange highlights.
    .suffix = { "" }
ent-ClothingHeadHelmetERTJanitor = ERT janitor helmet
    .desc = An in-atmosphere helmet worn by janitorial members of the Nanotrasen Emergency Response Team. Has dark purple highlights.
    .suffix = { "" }
