ent-FoodBoxDonut = коробка пончиков
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-FoodContainerEgg = картонная упаковка яиц
ent-EggBoxBroken = { ent-FoodContainerEgg }
ent-FoodBoxPizza = коробка пиццы
ent-FoodBoxPizzaFilled = коробка пиццы
ent-FoodBoxNugget = куриные наггетсы
ent-FoodBoxDonkpocket = коробка донк-покетов
ent-FoodBoxDonkpocketSpicy = коробка острых донк-покетов
ent-FoodBoxDonkpocketTeriyaki = коробка донк-покетов со вкусом терияки
ent-FoodBoxDonkpocketPizza = коробка донк-покетов со вкусом пиццы
ent-FoodBoxDonkpocketGondola = коробка донк-покетов со вкусом гондолы
ent-FoodBoxDonkpocketBerry = коробка донк-покетов со вкусом ягод
ent-FoodBoxDonkpocketHonk = коробка донк-покетов со вкусом банана
ent-FoodBoxDonkpocketDink = коробка динк-покетов
ent-HappyHonk = счастливый хонк
ent-HappyHonkMime = { ent-HappyHonk }
ent-HappyHonkNukie = ядерная еда
ent-HappyHonkCluwne = убогое блюдо из клаунов
ent-FoodMealHappyHonkClown = { ent-HappyHonk }
