ent-BaseFoodCondimentPacket = пакетик приправы
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-FoodCondimentPacket = { ent-BaseFoodCondimentPacket }
ent-FoodCondimentPacketAstrotame = Астротем
ent-FoodCondimentPacketBbq = соус барбекю
ent-FoodCondimentPacketFrostoil = холодный соус
ent-FoodCondimentPacketHorseradish = хрен
ent-FoodCondimentPacketHotsauce = острый соус
ent-FoodCondimentPacketKetchup = кетчуп
ent-FoodCondimentPacketPepper = чёрный перец
ent-FoodCondimentPacketSalt = соль
ent-FoodCondimentPacketSoy = соевый соус
ent-FoodCondimentPacketSugar = сахар
ent-BaseFoodCondimentBottle = бутылка приправы
ent-FoodCondimentBottle = { ent-BaseFoodCondimentBottle }
ent-FoodCondimentBottleColdsauce = бутылка холодного соуса
ent-FoodCondimentBottleEnzyme = универсальный фермент
ent-FoodCondimentBottleHotsauce = бутылка острого соуса
ent-FoodCondimentBottleKetchup = бутылка кетчупа
ent-FoodCondimentBottleBBQ = бутылка cоуса барбекю
ent-BaseFoodCondimentBottleSmall = маленькая бутылка приправы
ent-FoodCondimentBottleSmall = { ent-BaseFoodCondimentBottleSmall }
ent-FoodCondimentBottleSmallColdsauce = маленькая бутылка холодного соуса
ent-FoodCondimentBottleSmallHotsauce = маленькая бутылка острого соуса
ent-FoodCondimentBottleSmallKetchup = маленькая бутылка кетчупа
ent-FoodCondimentBottleSmallVinegar = маленькая бутылка уксуса
ent-FoodCondimentPacketTrash = пустой пакетик приправы
