ent-FoodPlate = большая тарелка
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-FoodPlateTrash = разбитая тарелка
ent-FoodPlateSmall = маленькая тарелка
ent-FoodPlateSmallTrash = разбитая тарелка
ent-FoodPlatePlastic = пластиковая тарелка
ent-FoodPlateSmallPlastic = пластиковая тарелка
ent-FoodPlateTin = формочка для пирога
