ent-FoodBakedCannabisBrownieBatch = special brownies
    .desc = A pan of "special" brownies.
    .suffix = { "" }
ent-FoodBakedCannabisBrownie = special brownie
    .desc = A "special" brownie.
    .suffix = { "" }
ent-FoodMothCheesecakeBalls = cheesecake balls
    .desc = Made of soft cheese, powdered sugar and flour, rolled into balls, battered and then deep fried. They're often served with honey.
    .suffix = { "" }
ent-FoodMothMothmallow = mothmallow tray
    .desc = A light and fluffy vegan marshmallow flavoured with vanilla and rum. These are known to the moths as cloud squares.
    .suffix = { "" }
ent-FoodMothMothmallowSlice = mothmallow slice
    .desc = Fluffy little clouds of joy- in a strangely moth-like form and colour.
    .suffix = { "" }
ent-FoodMothMoffin = moffin
    .desc = A delicious, spongy and dusty little cake.
    .suffix = { "" }
