ent-ClothingUniformKendoHakama = hakama
    .desc = An elegant black and blue hakama that could be worn for kendo or formal events.
    .suffix = { "" }
ent-ClothingUniformMartialGi = gi
    .desc = A white top and bottom traditionally used in martial arts, often paired with a belt.
    .suffix = { "" }
ent-ClothingKimonoBlue = blue kimono
    .desc = I'm blue da ba dee da ba da-ee!
    .suffix = { "" }
ent-ClothingKimonoPink = pink kimono
    .desc = Pretty in pink, isn't she?
    .suffix = { "" }
ent-ClothingKimonoPurple = purple kimono
    .desc = You definitely won't look like a maroon in this.
    .suffix = { "" }
ent-ClothingKimonoSky = sky blue kimono
    .desc = Reminds you of natsu matsuri.
    .suffix = { "" }
