ent-ClothingUniformKendoHakama = хакама
    .desc = Элегантная черно-синяя хакама, которую можно носить для кендо или официальных мероприятий.
    .suffix = { "" }
ent-ClothingUniformMartialGi = ги
    .desc = Белый верх и низ, традиционно используемые в боевых искусствах, часто сочетаются с поясом.
    .suffix = { "" }
ent-ClothingKimonoBlue = синее кимоно
    .desc = Я синий да ба ди да ба да-и!
    .suffix = { "" }
ent-ClothingKimonoPink = розовое кимоно
    .desc = Красотка в розовом, не так ли?
    .suffix = { "" }
ent-ClothingKimonoPurple = фиолетовое кимоно
    .desc = В этом ты точно не будешь выглядеть темно-бордовой.
    .suffix = { "" }
ent-ClothingKimonoSky = кимоно небесно-голубого цвета
    .desc = Напоминает Нацу Мацури.
    .suffix = { "" }
