ent-MaterialBase = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-MaterialCloth = ткань
ent-MaterialCloth1 = { ent-MaterialCloth }
ent-MaterialDurathread = дюраткань
ent-MaterialDurathread1 = { ent-MaterialDurathread }
ent-MaterialWoodPlank = древесина
ent-MaterialWoodPlank1 = { ent-MaterialWoodPlank }
ent-MaterialBiomass = биомасса
ent-MaterialBiomass1 = { ent-MaterialBiomass }
ent-MaterialHideBear = медвежья шкура
ent-MaterialDiamond = очищенный бриллиант
ent-MaterialDiamond1 = { ent-MaterialDiamond }
ent-MaterialCotton = хлопок
ent-MaterialCotton1 = { ent-MaterialCotton }
