ent-OreBase = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-GoldOre = золотоносная руда
ent-GoldOre1 = { ent-GoldOre }
ent-SteelOre = сталеносная руда
ent-SteelOre1 = { ent-SteelOre }
ent-PlasmaOre = плазменная руда
ent-PlasmaOre1 = { ent-PlasmaOre }
ent-SilverOre = серебряная руда
ent-SilverOre1 = { ent-SilverOre }
ent-SpaceQuartz = космический кварц
ent-SpaceQuartz1 = { ent-SpaceQuartz }
ent-UraniumOre = урановая руда
ent-UraniumOre1 = { ent-UraniumOre }
