ent-FoodPSBTrash = psb wrapper
    .desc = { ent-FoodPacketTrash.desc }
    .suffix = { "" }
ent-FoodPSB = prepacked sustenance bar
    .desc = The PSB is a densely packed, nutrient rich, artificially flavored and colored food bar specifically made to accomodate all morphotypes during food shortages.
    .suffix = { "" }
ent-FoodPSBBase = { ent-FoodSnackBase }
    .desc = { ent-FoodSnackBase.desc }
    .suffix = { "" }
ent-FoodPSBBarSoy = soy sustenance bar
    .desc = A densely packed, nutrient rich sustenance bar. This one is mixed-herb flavoured.
    .suffix = { "" }
ent-FoodPSBBarNeapolitan = neapolitan sustenance bar
    .desc = A densely packed, nutrient rich sustenance bar. This one is neapolitan flavoured- strawberry, vanilla, and chocolate.
    .suffix = { "" }
ent-FoodPSBBarBrownie = brownie sustenance bar
    .desc = A densely packed, nutrient rich sustenance bar. This one is brownie flavored.
    .suffix = { "" }
ent-FoodPSBBarCheese = cheese sustenance bar
    .desc = A densely packed, nutrient rich sustenance bar. This one is three-cheese flavoured- parmesan, mozzarella, and cheddar.
    .suffix = { "" }
ent-FoodPSBBarMeat = meat sustenance bar
    .desc = A densely packed, nutrient rich sustenance bar. This one is meat and pepper flavored.
    .suffix = { "" }
ent-FoodPSBBarVegetable = vegetable sustenance bar
    .desc = A densely packed, nutrient rich sustenance bar. This one is vegetable flavoured- lettuce, carrots and potato.
    .suffix = { "" }
ent-FoodPSBBarMint = mint sustenance bar
    .desc = A densely packed, nutrient rich sustenance bar. This one is mint choc chip flavoured- peppermint, dark chocolate, and potato chips.
    .suffix = { "" }
ent-FoodPSBBarBanana = banana sustenance bar
    .desc = A densely packed, nutrient rich sustenance bar. This one is banana milkshake flavoured- banana and milk.
    .suffix = { "" }
ent-FoodPSBBarWonka = wonka sustenance bar
    .desc = A densely packed, nutrient rich sustenance bar. This one is split into three flavours, making up a typical meal- tomato soup, roast pumpkin, and blueberry pie.
    .suffix = { "" }
