ent-ClothingMaskClownBase = маска и парик клоуна
    .desc = Лицевой атрибут настоящего приколиста. Клоун неполноценен без своих парика и маски.
    .suffix = { "" }
ent-ClothingMaskGasMerc = противогаз наёмника
    .desc = Немного устаревший, но надёжный противогаз военного образца.
    .suffix = { "" }
ent-ClothingMaskRat = маска крысы
    .desc = Маска крысы, которая выглядит как крыса. Возможно, они примут Вас за крысу.
    .suffix = { "" }
ent-ClothingMaskFox = маска лисы
    .desc = Как говорит лиса?
    .suffix = { "" }
ent-ClothingMaskBee = маска пчелы
    .desc = Для королевы!
    .suffix = { "" }
ent-ClothingMaskBear = маска медведя
    .desc = Я тучка, тучка, тучка, я вовсе не медведь.
    .suffix = { "" }
ent-ClothingMaskRaven = маска ворона
    .desc = Там, где я - смерть... или блеск.
    .suffix = { "" }
ent-ClothingMaskJackal = маска шакала
    .desc = Лучше не поворачиваться боком к владельцу маски, он может укусить.
    .suffix = { "" }
ent-ClothingMaskBat = маска летучей мыши
    .desc = Ночью - кровопийца, а днем - милый, слепой зверек.
    .suffix = { "" }
ent-ClothingMaskNeckGaiter = гетр для шеи
    .desc = Стильный гетр для шеи, способный защитить от космического ветра?...
    .suffix = { "" }
