ent-WindoorSecureArmoryLocked = { ent-WindoorSecureSecurityLocked }
    .suffix = Armory, Locked
    .desc = { ent-WindoorSecureSecurityLocked.desc }
ent-WindoorSecureBrigLocked = { ent-WindoorSecureSecurityLocked }
    .suffix = Brig, Locked
    .desc = { ent-WindoorSecureSecurityLocked.desc }
ent-WindoorSecureChemistryLocked = { ent-WindoorSecure }
    .suffix = Chemistry, Locked
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureCommandLocked = { ent-WindoorSecure }
    .suffix = Command, Locked
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureEngineeringLocked = { ent-WindoorSecure }
    .suffix = Engineering, Locked
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureExternalLocked = { ent-WindoorSecure }
    .suffix = External, Locked
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureMedicalLocked = { ent-WindoorSecure }
    .suffix = Medical, Locked
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureSecurityLocked = { ent-WindoorSecure }
    .suffix = Security, Locked
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureScienceLocked = { ent-WindoorSecure }
    .suffix = Science, Locked
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureHeadOfPersonnelLocked = { ent-WindoorSecure }
    .suffix = HeadOfPersonnel, Locked
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureAtmosphericsLocked = { ent-WindoorSecure }
    .suffix = Atmospherics, Locked
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureParamedicLocked = { ent-WindoorSecure }
    .suffix = Paramedic, Locked
    .desc = { ent-WindoorSecure.desc }
