ent-ToyFigurineHeadOfPersonnel = head of personnel figure
    .desc = A figurine depicting the glorious head of all personnel, away from their office as usual.
    .suffix = { "" }
ent-ToyFigurinePassenger = passenger figure
    .desc = A figurine depicting an every day, run-of-the-mill passenger. No funny business here.
    .suffix = { "" }
ent-ToyFigurineGreytider = greytider figure
    .desc = A figurine depicting a dubious-looking passenger. Greytide worldwide!
    .suffix = { "" }
ent-ToyFigurineClown = clown figure
    .desc = A figurine depicting a clown. You shudder to think of what people have probably done to this figurine before.
    .suffix = { "" }
ent-ToyFigurineMime = mime figure
    .desc = A figurine depicting that silent bastard you are all too familiar with.
    .suffix = { "" }
ent-ToyFigurineMusician = musician figure
    .desc = A figurine depicting a Musician, his music was electrifying.
    .suffix = { "" }
ent-ToyFigurineBoxer = boxer figure
    .desc = A figurine depicting a Boxer holding their red gloves.
    .suffix = { "" }
ent-ToyFigurineCaptain = captain figure
    .desc = A figurine depicting the standard outfit of a captain belonging to a civilian-sector Nanotrasen vessel.
    .suffix = { "" }
ent-ToyFigurineHeadOfSecurity = head of security figure
    .desc = A figurine depicting the glorious head of the Security department.
    .suffix = { "" }
ent-ToyFigurineWarden = warden figure
    .desc = A figurine depicting a Warden, ready to jail someone at any moment.
    .suffix = { "" }
ent-ToyFigurineDetective = detective figure
    .desc = A figurine depicting a Detective wearing their iconic trench coat.
    .suffix = { "" }
ent-ToyFigurineSecurity = security officer figure
    .desc = A figurine depicting a Security Officer holding a stunbaton, ready to defend the station.
    .suffix = { "" }
ent-ToyFigurineLawyer = lawyer figure
    .desc = A figurine depicting a Lawyer sporting a freshly tailored suit.
    .suffix = { "" }
ent-ToyFigurineCargoTech = cargo technican figure
    .desc = A figurine depicting a reptillian Cargo Technican.
    .suffix = { "" }
ent-ToyFigurineSalvage = salvage technican figure
    .desc = A figurine depicting a Salvage Technician holding a survival knife.
    .suffix = { "" }
ent-ToyFigurineQuartermaster = quartermaster figure
    .desc = A figurine depicting the glorious head of the Cargo department.
    .suffix = { "" }
ent-ToyFigurineChiefEngineer = chief engineer figure
    .desc = A figurine depicting the glorious head of the Engineering department.
    .suffix = { "" }
ent-ToyFigurineEngineer = station engineer figure
    .desc = A figurine depicting a Station Engineer holding a crowbar at-ready.
    .suffix = { "" }
ent-ToyFigurineAtmosTech = atmospheric technician figure
    .desc = A figurine depicting an Atmos Tech holding an unlit welder.
    .suffix = { "" }
ent-ToyFigurineResearchDirector = research director figure
    .desc = A figurine depicting the glorious head of the Science department.
    .suffix = { "" }
ent-ToyFigurineScientist = scientist figurine
    .desc = A figurine depicting a Scienist donning a labcoat.
    .suffix = { "" }
ent-ToyFigurineChiefMedicalOfficer = chief medical officer figure
    .desc = A figurine depicting the glorious head of the Medical department.
    .suffix = { "" }
ent-ToyFigurineChemist = chemist figure
    .desc = A figurine depicting a Chemist probably planning to make meth.
    .suffix = { "" }
ent-ToyFigurineParamedic = paramedic figure
    .desc = A figurine depicting a Paramedic wearing their void suit.
    .suffix = { "" }
ent-ToyFigurineMedicalDoctor = medical doctor figure
    .desc = A figurine depicting a Medical Doctor, donning a labcoat & syringe.
    .suffix = { "" }
ent-ToyFigurineLibrarian = librarian figure
    .desc = A figurine depicting the one-and-only librarian.
    .suffix = { "" }
ent-ToyFigurineChaplain = chaplain figure
    .desc = A figurine depicting a Chaplain hopefully praying for good things.
    .suffix = { "" }
ent-ToyFigurineChef = chef figure
    .desc = A figurine depicting a chef, master of the culinary arts!.. most of the time.
    .suffix = { "" }
ent-ToyFigurineBartender = bartender figure
    .desc = A figurine depicting a Bartender looking stylish with their rockin shades and tophat.
    .suffix = { "" }
ent-ToyFigurineBotanist = botanist figure
    .desc = A figurine depicting a Botanist that surely won't let kudzu get out of control.
    .suffix = { "" }
ent-ToyFigurineJanitor = janitor figure
    .desc = A figurine depicting a Janitor with their galoshes.
    .suffix = { "" }
ent-ToyFigurineNukie = syndicate operative figure
    .desc = A figurine depicting someone in a blood-red hardsuit, similar to what someone on a nuclear operative team might wear.
    .suffix = { "" }
ent-ToyFigurineNukieElite = elite syndicate operative figure
    .desc = A figurine depicting someone in an elite blood-red hardsuit, similar to what the medic of a nuclear operative team might wear.
    .suffix = { "" }
ent-ToyFigurineNukieCommander = syndicate operative commander figure
    .desc = A figurine depicting someone in a beefed-up blood-red hardsuit, similar to what the commander of a nuclear operative team might wear.
    .suffix = { "" }
ent-ToyFigurineFootsoldier = syndicate footsoldier figure
    .desc = A figurine depicting the outfit of a syndicate footsoldier.
    .suffix = { "" }
ent-ToyFigurineWizard = wizard figure
    .desc = A figurine depicting someone with a long, silky beard wearing a wizard outfit. Warlocks wish they had anything on this.
    .suffix = { "" }
ent-ToyFigurineWizardFake = fake wizard figure
    .desc = A figurine depicting someone in a fake-ass wizard costume. What a ripoff!
    .suffix = { "" }
ent-ToyFigurineSpaceDragon = space dragon figure
    .desc = A large figurine depicting a space dragon, its red eyes on gazing on its prey.
    .suffix = { "" }
ent-ToyFigurineQueen = xeno queen figure
    .desc = A large figurine depicting a xeno queen, ready to attack.
    .suffix = { "" }
ent-ToyFigurineRatKing = rat king figure
    .desc = A large figurine depicting a rat king, prepared to make its nest.
    .suffix = { "" }
ent-ToyFigurineRatServant = rat servant figure
    .desc = A figurine depicting a rat serving the king of rats!
    .suffix = { "" }
ent-ToyFigurineMouse = mouse figure
    .desc = A figurine depicting a mouse scuttling away to the nearest piece of food.
    .suffix = { "" }
ent-ToyFigurineSlime = slime figure
    .desc = A figurine depicting a translucent blue slime.
    .suffix = { "" }
ent-ToyFigurineHamlet = hamlet figure
    .desc = A figurine depicting Hamlet, microwave not included.
    .suffix = { "" }
