ent-PlushieHampter = hampter plushie
    .desc = A cute stuffed toy that resembles a hamster. Its face looks squished.
    .suffix = { "" }
ent-PlushieDiona = diona plushie
    .desc = An adorable stuffed toy that resembles a diona. Love water and cuddles. Do not wet!
    .suffix = { "" }
ent-PlushieXeno = xeno plushie
    .desc = An adorable stuffed toy that resembles a scary xenomorf. You're lucky it's just a toy.
    .suffix = { "" }
ent-BaseFigurineCheapo = figurine
    .desc = A small miniature.
    .suffix = { "" }
ent-BeachBall = beach ball
    .desc = The simple beach ball is one of Nanotrasen's most popular products. 'Why do we make beach balls? Because we can! (TM)' - Nanotrasen
    .suffix = { "" }
ent-ToyHammer = rubber hammer
    .desc = A brightly colored hammer made of rubber.
    .suffix = { "" }
ent-WhoopieCushion = whoopie cushion
    .desc = A practical joke device involving flatulence humour.
    .suffix = { "" }
ent-PlasticBanana = banana
    .desc = A plastic banana.
    .suffix = Plastic
ent-CrazyGlue = crazy glue
    .desc = A bottle of crazy glue manufactured by Honk! Co.
    .suffix = { "" }
