ent-ClothingOuterRobeWhite = white robe
    .desc = This doesn't look creepy at all.
    .suffix = { "" }
ent-ClothingOuterRobeBrown = Brown Robe
    .desc = This doesn't look creepy at all.
    .suffix = { "" }
ent-ClothingOuterRobeMystic = mystic robe
    .desc = The mystagogue's flashy robe.
    .suffix = { "" }
ent-ClothingOuterRobeTechPriest = automaturge robe
    .desc = Robots are basically bulls when you think about it, so best to wear red.
    .suffix = { "" }
