ent-PoweredlightColoredRed = { ent-Poweredlight }
    .desc = Источник света. Потребляет энергию и производит свет с помощью лампочки-трубки.
    .suffix = Красный
ent-PoweredlightColoredFrostyBlue = { ent-Poweredlight }
    .desc = Источник света. Потребляет энергию и производит свет с помощью лампочки-трубки.
    .suffix = Морозный
ent-PoweredlightColoredBlack = { ent-Poweredlight }
    .desc = Источник света. Потребляет энергию и производит свет с помощью лампочки-трубки.
    .suffix = Черный
ent-PoweredLightPostSmallRed = почтовый фонарь
    .desc = Источник света. Потребляет энергию и производит свет с помощью лампочки-трубки.
    .suffix = Красный
ent-AlwaysPoweredlightColoredRed = { ent-AlwaysPoweredWallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении световой трубкой.
    .suffix = Всегда запитан, красный
ent-AlwaysPoweredlightColoredFrostyBlue = { ent-AlwaysPoweredWallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении световой трубкой.
    .suffix = Всегда запитан, морозный
ent-AlwaysPoweredlightColoredBlack = { ent-AlwaysPoweredWallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении световой трубкой.
    .suffix = Всегда запитан, чёрный
ent-AlwaysPoweredLightPostSmallRed = почтовый светильник
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении световой трубкой.
    .suffix = Всегда запитан, красный
