ent-AirlockFreezer = { ent-Airlock }
.suffix = { "" }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
ent-AirlockEngineering = { ent-Airlock }
ent-AirlockAtmospherics = { ent-Airlock }
ent-AirlockCargo = { ent-Airlock }
ent-AirlockMedical = { ent-Airlock }
ent-AirlockVirology = { ent-Airlock }
ent-AirlockChemistry = { ent-Airlock }
ent-AirlockScience = { ent-Airlock }
ent-AirlockCommand = { ent-Airlock }
ent-AirlockSecurity = { ent-Airlock }
ent-AirlockMaint = технический шлюз
ent-AirlockGlass = стеклянный шлюз
ent-AirlockEngineeringGlass = { ent-AirlockGlass }
ent-AirlockMaintGlass = { ent-AirlockGlass }
ent-AirlockAtmosphericsGlass = { ent-AirlockGlass }
ent-AirlockCargoGlass = { ent-AirlockGlass }
ent-AirlockMedicalGlass = { ent-AirlockGlass }
ent-AirlockVirologyGlass = { ent-AirlockGlass }
ent-AirlockScienceGlass = { ent-AirlockGlass }
ent-AirlockCommandGlass = { ent-AirlockGlass }
ent-AirlockSecurityGlass = { ent-AirlockGlass }
