reagent-name-gunmetal = бронза
reagent-desc-gunmetal = Спорный напиток, созданный печально известным Solus Cream, первым барменом, который подал сварочное топливо, не потеряв лицензию на продажу спиртных напитков.
reagent-name-lemondrop = лимонный леденец
reagent-desc-lemondrop = Простой, острый и вкусный напиток, состоящий из лимона, водки и сахарного сиропа. Освежающий!
reagent-name-greengrass = зеленая трава
reagent-desc-greengrass = Зеленая трава, или grüne wiese, — своеобразный зеленый коктейль родом из ныне распавшейся ГДР. Популярен как среди разочарованных, так и простодушных.
reagent-name-daiquiri = классический дайкири
reagent-desc-daiquiri = Сладкая смесь рома и лайма, любимая писателями и политиками.
reagent-name-arsonistsbrew = отвар поджигателя
reagent-desc-arsonistsbrew = Сделайте глоток и смейтесь, пока вы смотрите, как горит ваш мир.
reagent-name-dulleavene = унылость
reagent-desc-dulleavene = Якобы это коктейль. Мотив предупреждающего конуса кажется уместным.
