ent-MachineParticleAcceleratorEndCapCircuitboard = торцевая заглушка УЧ
    .desc = { ent-BaseMachineCircuitboard.desc }
    .suffix = { "" }
ent-MachineParticleAcceleratorFuelChamberCircuitboard = топливная камера УЧ
    .desc = { ent-BaseMachineCircuitboard.desc }
    .suffix = { "" }
ent-MachineParticleAcceleratorPowerBoxCircuitboard = блок питания УЧ
    .desc = { ent-BaseMachineCircuitboard.desc }
    .suffix = { "" }
ent-MachineParticleAcceleratorEmitterLeftCircuitboard = левый эмиттер УЧ
    .desc = { ent-BaseMachineCircuitboard.desc }
    .suffix = { "" }
ent-MachineParticleAcceleratorEmitterCenterCircuitboard = центральный эмиттер УЧ
    .desc = { ent-BaseMachineCircuitboard.desc }
    .suffix = { "" }
ent-MachineParticleAcceleratorEmitterRightCircuitboard = правый эмиттер УЧ
    .desc = { ent-BaseMachineCircuitboard.desc }
    .suffix = { "" }
ent-MachineParticleAcceleratorEmitterStarboardCircuitboard = правый эмиттер УЧ (машинная плата)
    .desc = Машинная плата для правого эмиттера ускорителя частиц
    .suffix = { "" }
ent-MachineParticleAcceleratorEmitterForeCircuitboard = центральный эмиттер УЧ (машинная плата)
    .desc = Машинная плата для центрального эмиттера ускорителя частиц
    .suffix = { "" }
ent-MachineParticleAcceleratorEmitterPortCircuitboard = левый эмиттер УЧ (машинная плата)
    .desc = Машинная плата для левого эмиттера ускорителя частиц
    .suffix = { "" }
