ent-ClothingUniformJumpsuitAncient = старинный комбинезон
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingUniformJumpsuitBartender = униформа бармена
ent-ClothingUniformJumpsuitBartenderPurple = фиолетовая униформа бармена
ent-ClothingUniformJumpsuitCaptain = комбинезон капитана
ent-ClothingUniformJumpsuitCargo = комбинезон грузчика
ent-ClothingUniformJumpsuitSalvageSpecialist = комбинезон специалиста по утилизации
ent-ClothingUniformJumpsuitChiefEngineer = комбинезон старшего инженера
ent-ClothingUniformJumpsuitChaplain = комбинезон священника
ent-ClothingUniformJumpsuitCentcomOfficial = костюм офицера Центком
ent-ClothingUniformJumpsuitCentcomOfficer = водолазка Центком
ent-ClothingUniformJumpsuitChef = униформа шеф-повара
ent-ClothingUniformJumpsuitChemistry = комбинезон химика
ent-ClothingUniformJumpsuitClown = костюм клоуна
ent-ClothingUniformJumpsuitJester = костюм шута
ent-ClothingUniformJumpsuitJesterAlt = { ent-ClothingUniformJumpsuitJester }
ent-ClothingUniformJumpsuitCMO = комбинезон главного врача
ent-ClothingUniformJumpsuitDetective = поношенный костюм
ent-ClothingUniformJumpsuitDetectiveGrey = нуарный костюм
ent-ClothingUniformJumpsuitEngineering = инженерный комбинезон
ent-ClothingUniformJumpsuitEngineeringHazard = защитный комбинезон
ent-ClothingUniformJumpsuitHoP = комбинезон главы персонала
ent-ClothingUniformJumpsuitHoS = комбинезон главы службы безопасности
ent-ClothingUniformJumpsuitHoSAlt = водолазка главы службы безопасности
ent-ClothingUniformJumpsuitHoSBlue = синий комбинезон главы службы безопасности
ent-ClothingUniformJumpsuitHoSGrey = серый комбинезон главы службы безопасности
ent-ClothingUniformJumpsuitHoSParadeMale = парадная форма главы службы безопасности
ent-ClothingUniformJumpsuitHydroponics = комбинезон ботаника
ent-ClothingUniformJumpsuitJanitor = комбинезон уборщика
ent-ClothingUniformJumpsuitMedicalDoctor = комбинезон врача
ent-ClothingUniformJumpsuitMime = костюм мима
ent-ClothingUniformJumpsuitParamedic = комбинезон парамедика
ent-ClothingUniformJumpsuitPrisoner = комбинезон заключенного
ent-ClothingUniformJumpsuitQM = комбинезон квартирмейстера
ent-ClothingUniformJumpsuitResearchDirector = водолазка научного руководителя
ent-ClothingUniformJumpsuitScientist = комбинезон ученого
ent-ClothingUniformJumpsuitSec = комбинезон службы безопасности
ent-ClothingUniformJumpsuitSecBlue = голубая рубашка и галстук
ent-ClothingUniformJumpsuitSecGrey = серый комбинезон службы безопасности
ent-ClothingUniformJumpsuitWarden = униформа смотрителя
ent-ClothingUniformJumpsuitColorGrey = серый комбинезон
ent-ClothingUniformJumpsuitColorBlack = чёрный комбинезон
ent-ClothingUniformJumpsuitColorBlue = синий комбинезон
ent-ClothingUniformJumpsuitColorGreen = зелёный комбинезон
ent-ClothingUniformJumpsuitColorOrange = оранжевый комбинезон
ent-ClothingUniformJumpsuitColorPink = розовый комбинезон
ent-ClothingUniformJumpsuitColorRed = красный комбинезон
ent-ClothingUniformJumpsuitColorWhite = белый комбинезон
ent-ClothingUniformJumpsuitColorYellow = жёлтый комбинезон
ent-ClothingUniformJumpsuitColorDarkBlue = тёмно-синий комбинезон
ent-ClothingUniformJumpsuitColorTeal = аквамариновый комбинезон
ent-ClothingUniformJumpsuitColorPurple = фиолетовый комбинезон
ent-ClothingUniformJumpsuitColorDarkGreen = тёмно-зелёный комбинезон
ent-ClothingUniformJumpsuitColorLightBrown = светло-коричневый комбинезон
ent-ClothingUniformJumpsuitColorBrown = коричневый комбинезон
ent-ClothingUniformJumpsuitColorMaroon = бордовый комбинезон
ent-ClothingUniformColorRainbow = радужный комбинезон
ent-ClothingUniformOveralls = комбинезон на лямках
ent-ClothingUniformJumpsuitLibrarian = практичный костюм
ent-ClothingUniformJumpsuitLawyerRed = красный адвокатский костюм
ent-ClothingUniformJumpsuitLawyerBlue = синий адвокатский костюм
ent-ClothingUniformJumpsuitLawyerBlack = чёрный адвокатский костюм
ent-ClothingUniformJumpsuitLawyerPurple = фиолетовый адвокатский костюм
ent-ClothingUniformJumpsuitLawyerGood = хороший адвокатский костюм
ent-ClothingUniformJumpsuitPyjamaSyndicateBlack = чёрная пижама синдиката
ent-ClothingUniformJumpsuitPyjamaSyndicatePink = розовая пижама синдиката
ent-ClothingUniformJumpsuitPyjamaSyndicateRed = красная пижама синдиката
ent-ClothingUniformJumpsuitNanotrasen = комбинезон NanoTrasen
ent-ClothingUniformJumpsuitCapFormal = торжественный костюм капитана
ent-ClothingUniformJumpsuitCentcomFormal = торжественный костюм Центком
ent-ClothingUniformJumpsuitHosFormal = торжественный костюм главы службы безопасности
ent-ClothingUniformJumpsuitOperative = комбинезон оперативника
ent-ClothingUniformJumpsuitAtmos = комбинезон атмосферного техника
ent-ClothingUniformJumpsuitPsychologist = костюм психолога
ent-ClothingUniformJumpsuitReporter = костюм репортёра
ent-ClothingUniformJumpsuitSafari = костюм для сафари
ent-ClothingUniformJumpsuitJournalist = костюм журналиста
ent-ClothingUniformJumpsuitMonasticRobeDark = тёмная монашеская ряса
ent-ClothingUniformJumpsuitMonasticRobeLight = светлая монашеская ряса
ent-ClothingUniformJumpsuitMusician = костюм из карпокожи
ent-ClothingUniformJumpsuitERTEngineer = инженерная униформа ОБР
ent-ClothingUniformJumpsuitERTJanitor = униформа уборщика ОБР
ent-ClothingUniformJumpsuitERTLeader = униформа лидера ОБР
ent-ClothingUniformJumpsuitERTMedic = медицинская униформа ОБР
ent-ClothingUniformJumpsuitERTSecurity = униформа службы безопасности ОБР
ent-ClothingUniformJumpsuitDameDane = якудза костюм
