ent-WeaponWaterGunBase = { ent-BaseItem }
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-WeaponWaterPistol = водяной пистолет
    .desc = Самое изящное оружие на водной основе. Вы клянетесь, что спуск ничего не делает.
    .suffix = { "" }
ent-WeaponWaterBlaster = водяной бластер
    .desc = С этим плохишом ты будешь самым крутым парнем на летнем барбекю.
    .suffix = { "" }
