ent-BaseMagazineBoxCaselessRifle = коробка патронов (.25 безгильзовые)
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-MagazineBoxCaselessRifle10x24 = ящик патронов (.25 безгильзовые)
ent-MagazineBoxCaselessRifleBig = ящик патронов (.25 безгильзовые)
ent-MagazineBoxCaselessRifleBigRubber = ящик патронов (.25 безгильзовые резиновые)
ent-MagazineBoxCaselessRifle = коробка патронов (.25 безгильзовые)
ent-MagazineBoxCaselessRifleHighVelocity = коробка патронов (.25 безгильзовые высокоскоростные)
ent-MagazineBoxCaselessRiflePractice = коробка патронов (.25 безгильзовые учебные)
ent-MagazineBoxCaselessRifleRubber = коробка патронов (.25 безгильзовые резиновые)
