ent-BaseMagazineBoxRifle = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-MagazineBoxRifleBig = ящик патронов (.20 винтовочные)
ent-MagazineBoxRifleBigRubber = ящик патронов (.20 винтовочные резиновые)
ent-MagazineBoxRifle = коробка патронов (.20 винтовочные)
ent-MagazineBoxRifleHighVelocity = коробка патронов (.20 винтовочные высокоскоростные)
ent-MagazineBoxRiflePractice = коробка патронов (.20 винтовочные учебные)
ent-MagazineBoxRifleRubber = коробка патронов (.20 винтовочные резиновые)
