ent-PelletShotgunSlug = дробина (.50 пуля)
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-PelletShotgunBeanbag = дробина (.50)
ent-PelletShotgun = дробина (.50)
ent-PelletShotgunIncendiary = дробина (.50 зажигательная)
ent-PelletShotgunPractice = дробина (.50 учебная)
ent-PelletShotgunTranquilizer = дробина (.50 транквилизатор)
ent-PelletShotgunFlare = дробина (.50 фальшфейер)
