ent-ClothingNeckTieWhite = белый галстук
    .desc = Галстук цвета слоновой кости.
    .suffix = { "" }
ent-ClothingNeckTieBlack = чёрный галстук
    .desc = Угольно-черный галстук.
    .suffix = { "" }
ent-ClothingNeckTieBrown = коричнивый галстук
    .desc = Шоколадно-коричневый галстук.
    .suffix = { "" }
ent-ClothingNeckTieBlue = синий галстук
    .desc = Лазурно-голубой галстук.
    .suffix = { "" }
ent-ClothingNeckTieGreen = зелёный галстук
    .desc = Галстук цвета травы.
    .suffix = { "" }
