ent-ArachneWeb = паутина
    .desc = Огромная паутина.
    .suffix = { "" }
ent-CocoonedHumanoid = кокон с гуманойдом
    .desc = Неудачно получилось.
    .suffix = { "" }
ent-CocoonSmall = кокон
    .desc = Что бы могло быть внутри...?
    .suffix = { "" }
