ent-SalvagePartsSpawnerLow = Спавнер частей утилизации
    .suffix = Low
    .desc = { ent-MarkerBase.desc }
ent-SalvagePartsSpawnerMid = Спавнер частей утилизации
    .suffix = High
    .desc = { ent-MarkerBase.desc }
ent-SalvagePartsSpawnerSubSpace = Спавнер частей утилизации
    .suffix = Subspace
    .desc = { ent-MarkerBase.desc }
