ent-ClothingOuterHardsuitSyndieReverseEngineered = SA-122 боевой скафандр
    .suffix = реконструированный
    .desc = { ent-ClothingOuterHardsuitSyndie.desc }
ent-ClothingOuterHardsuitJuggernautReverseEngineered = штурмовой скафандр SA-126
    .desc = Гиперэластичный костюм, изготовленный отделом специальных закупок «Нанотрасен».
    .suffix = реконструированный
ent-ClothingOuterHardsuitERTCentcomm = скафандр ЦентКом
    .desc = { ent-ClothingOuterHardsuitERTLeader.desc }
    .suffix = { "" }
