ent-ClothingOuterCoatHyenhSweater = удобный свитер
    .desc = Это удобно.
    .suffix = { "" }
ent-ClothingOuterWinterCoatLong = длинное зимнее пальто
    .desc = В этом стильном пальто даже вашим ногам будет тепло.
    .suffix = { "" }
ent-ClothingOuterWinterCoatPlaid = клетчатое зимнее пальто
    .desc = Он может быть сделан из настоящей шерсти.
    .suffix = { "" }
ent-ClothingOuterWinterCoatMail = зимнее пальто почтальона
    .desc = Он убережет от холода, но не от собак.
    .suffix = { "" }
ent-ClothingOuterWinterCoatMantis = зимнее пальто детектива
    .desc = Стильно решайте нераскрытые дела.
    .suffix = { "" }
ent-ClothingOuterWinterMystagogue = зимнее пальто мистагога
    .desc = { ent-ClothingOuterWinterRD.desc }
    .suffix = { "" }
