ent-WallRockArtifactFragment = { ent-WallRock }
    .desc = A rock wall. What's that sticking out of it?
    .suffix = Artifact Fragment
ent-WallRockBasalt = { ent-WallRock }
    .desc = { ent-WallRock.desc }
    .suffix = { "" }
ent-WallRockBasaltGold = { ent-WallRockBasalt }
    .desc = An ore vein rich with gold.
    .suffix = Gold
ent-WallRockBasaltPlasma = { ent-WallRockBasalt }
    .desc = An ore vein rich with plasma.
    .suffix = Plasma
ent-WallRockBasaltQuartz = { ent-WallRockBasalt }
    .desc = An ore vein rich with quartz.
    .suffix = Quartz
ent-WallRockBasaltSilver = { ent-WallRockBasalt }
    .desc = An ore vein rich with silver.
    .suffix = Silver
ent-WallRockBasaltTin = { ent-WallRockBasalt }
    .desc = An ore vein rich with steel.
    .suffix = Steel
ent-WallRockBasaltUranium = { ent-WallRockBasalt }
    .desc = An ore vein rich with uranium.
    .suffix = Uranium
ent-WallRockBasaltArtifactFragment = { ent-WallRockBasalt }
    .desc = A rock wall. What's that sticking out of it?
    .suffix = Artifact Fragment
ent-WallRockSnow = { ent-WallRock }
    .desc = { ent-WallRock.desc }
    .suffix = { "" }
ent-WallRockSnowGold = { ent-WallRockSnow }
    .desc = An ore vein rich with gold.
    .suffix = Gold
ent-WallRockSnowPlasma = { ent-WallRockSnow }
    .desc = An ore vein rich with plasma.
    .suffix = Plasma
ent-WallRockSnowQuartz = { ent-WallRockSnow }
    .desc = An ore vein rich with quartz.
    .suffix = Quartz
ent-WallRockSnowSilver = { ent-WallRockSnow }
    .desc = An ore vein rich with silver.
    .suffix = Silver
ent-WallRockSnowTin = { ent-WallRockSnow }
    .desc = An ore vein rich with steel.
    .suffix = Steel
ent-WallRockSnowUranium = { ent-WallRockSnow }
    .desc = An ore vein rich with uranium.
    .suffix = Uranium
ent-WallRockSnowArtifactFragment = { ent-WallRockSnow }
    .desc = A rock wall. What's that sticking out of it?
    .suffix = Artifact Fragment
