ent-ClothingEyesHudBeer = пивные очки
    .desc = Пара солнцезащитных очков, оснащенных сканером реагентов, а также дающих понимание вязкости жидкости во время движения.
    .suffix = { "" }
ent-ClothingEyesHudFriedOnion = очки из жареного лука
    .desc = Заполнитель
    .suffix = { "" }
ent-ClothingEyesHudOnionBeer = жолодные очки
    .desc = Заполнитель
    .suffix = { "" }
ent-ClothingEyesHudMedOnion = медлуковой визор
    .desc = Заполнитель
    .suffix = { "" }
ent-ClothingEyesHudMedOnionBeer = меджолодный визор
    .desc = Заполнитель
    .suffix = { "" }
ent-ClothingEyesHudMedSec = медико-охранный визор
    .desc = Заполнитель
    .suffix = { "" }
ent-ClothingEyesHudMultiversal = мультиверсальный визор
    .desc = Заполнитель
    .suffix = { "" }
ent-ClothingEyesHudOmni = омни визор
    .desc = Заполнитель
    .suffix = { "" }
