ent-BaseTreePalmLarge = { ent-BaseTree }
    .desc = { ent-BaseTree.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge01 = большая пальма
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge02 = большая пальма
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge03 = большая пальма
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge04 = большая пальма
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge05 = большая пальма
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge06 = большая пальма
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-BaseTreePalm = { ent-BaseTree }
    .desc = { ent-BaseTree.desc }
    .suffix = { "" }
ent-FloraTreePalm01 = пальма
    .desc = { ent-BaseTreePalm.desc }
    .suffix = { "" }
ent-FloraTreePalm02 = пальма
    .desc = { ent-BaseTreePalm.desc }
    .suffix = { "" }
ent-FloraTreePalm03 = пальма
    .desc = { ent-BaseTreePalm.desc }
    .suffix = { "" }
ent-FloraTreePalm04 = пальма
    .desc = { ent-BaseTreePalm.desc }
    .suffix = { "" }
