ent-ArachneWeb = web
    .desc = A huge spider web.
    .suffix = { "" }
ent-CocoonedHumanoid = cocooned humanoid
    .desc = Unlucky.
    .suffix = { "" }
ent-CocoonSmall = cocoon
    .desc = What could be inside...?
    .suffix = { "" }
