ent-Jug = кувшин
    .desc = Используется для хранения очень большого количества химических веществ или растворов. Пить залпом крайне не рекомендуется.
    .suffix = { "" }
ent-JugCarbon = кувшин (углерод)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugIodine = кувшин (йод)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugFluorine = кувшин (фтор)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugChlorine = кувшин (хлор)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugAluminium = кувшин (алюминий)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugPhosphorus = кувшин (фосфор)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugSulfur = кувшин (сера)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugSilicon = кувшин (кремний)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugHydrogen = кувшин (водород)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugLithium = кувшин (литий)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugSodium = кувшин (натрий)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugPotassium = кувшин (калий)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugRadium = кувшин (радий)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugIron = кувшин (железо)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugCopper = кувшин (медь)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugGold = кувшин (золото)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugMercury = кувшин (ртуть)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugSilver = кувшин (серебро)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugEthanol = кувшин (этанол)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugSugar = кувшин (сахар)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugNitrogen = кувшин (азот)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
ent-JugOxygen = кувшин (кислород)
    .desc = { ent-Jug.desc }
    .suffix = { "" }
