advertisement-boozeomat-1 = Надеюсь никому не нужна чертова чашка чая...
advertisement-boozeomat-2 = Алкоголь лучший друг любого живого существа. Неужели вы бросите друга?
advertisement-boozeomat-3 = Это честь оказывать вам сервис!
advertisement-boozeomat-4 = Неужели никто не хочет выпить на этой станции?
advertisement-boozeomat-5 = Поднять бокалы!
advertisement-boozeomat-6 = Алкоголь лечит, вы знали это?
advertisement-boozeomat-7 = Алкоголь лучший друг любого живого существа.
advertisement-boozeomat-8 =Не хотите хорошего вкуснейшего пива?
advertisement-boozeomat-9 = Ничего так не лечит как алкоголь!
advertisement-boozeomat-10 = Присядь и попей!
advertisement-boozeomat-11 = Давай выпьем!
advertisement-boozeomat-12 = Пивка для рывка!
advertisement-boozeomat-13 = Всегда есть время для пива!
advertisement-boozeomat-14 = Только лучший алкоголь!
advertisement-boozeomat-15 = Алкоголь высшего качества с 2053!
advertisement-boozeomat-16 = Вино с множеством наград!
advertisement-boozeomat-17 = Максимум алкоголя!
advertisement-boozeomat-18 = Мужчины любят пиво.
advertisement-boozeomat-19 = У меня тост! За технологии!
