advertisement-magivend-1 = Кастуйте вашу магию со стилем вместе с MagiVend!
advertisement-magivend-2 = Стань как Гудини! Используй MagiVend!
advertisement-magivend-3 = Абракадабра!
advertisement-magivend-4 = Скидадл-скадудл!
advertisement-magivend-5 = Вжух!
advertisement-magivend-6 = ХОНК!
advertisement-magivend-7 = Кавабанга!
advertisement-magivend-8 = Сожги эту станцию!
advertisement-magivend-9 = Время отделить пространство от времени!
advertisement-magivend-10 = Наколдуй что нибудь!
