ent-SheetUGlass = uranium glass
    .desc = A sheet of uranium glass.
    .suffix = Full
ent-SheetUGlass1 = uranium glass
    .suffix = Single
    .desc = { ent-SheetUGlass.desc }
ent-SheetRUGlass = reinforced uranium glass
    .desc = A reinforced sheet of uranium.
    .suffix = Full
ent-SheetRUGlass1 = reinforced uranium glass
    .suffix = Single
    .desc = { ent-SheetRUGlass.desc }
