ent-PoweredLightBlueInterior = { ent-PoweredlightExterior }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении лампочкой-трубкой.
    .suffix = Blue Interior
ent-AlwaysPoweredLightBlueInterior = { ent-AlwaysPoweredWallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении лампочкой-трубкой.
    .suffix = Always Powered, Blue Interior
ent-PoweredSmallLightMaintenance = { ent-PoweredSmallLight }
    .desc = Светильник. Потребляет энергию и излучает свет, если оснащен лампочкой.
    .suffix = Maintenance
ent-AlwaysPoweredSmallLightMaintenance = { ent-SmallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении лампочкой-трубкой.
    .suffix = Always Powered, Maintenance
ent-PoweredLightColoredRed = { ent-Poweredlight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении лампочкой-трубкой.
    .suffix = Red
ent-AlwaysPoweredLightColoredRed = { ent-AlwaysPoweredWallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении лампочкой-трубкой.
    .suffix = Always Powered, Red
ent-PoweredLightColoredFrostyBlue = { ent-Poweredlight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении лампочкой-трубкой.
    .suffix = Frosty
ent-AlwaysPoweredLightColoredFrostyBlue = { ent-AlwaysPoweredWallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении лампочкой-трубкой.
    .suffix = Always Powered, Frosty
ent-PoweredLightColoredBlack = { ent-Poweredlight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении лампочкой-трубкой.
    .suffix = Black
ent-AlwaysPoweredLightColoredBlack = { ent-AlwaysPoweredWallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении лампочкой-трубкой.
    .suffix = Always Powered, Black
ent-PoweredSmallLightMaintenanceRed = { ent-PoweredSmallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении лампочкой-трубкой.
    .suffix = Maintenance, Red
ent-AlwaysPoweredSmallLightMaintenanceRed = { ent-SmallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении лампочкой-трубкой.
    .suffix = Always Powered, Maintenance, Red
