ent-FoodCartBase = Food Cart
    .desc = A cart for food.
    .suffix = { "" }
ent-FoodCartHot = Hot Food Cart
    .desc = Get out there and slang some dogs.
    .suffix = { "" }
ent-FoodCartCold = Cold Food Cart
    .desc = It's the Ice Cream Man! It's the Ice Cream Man!
    .suffix = { "" }
