ent-BaseWeaponShotgunNonLethal = { ent-BaseWeaponShotgun }
    .suffix = Beanbag
    .desc = { ent-BaseWeaponShotgun.desc }
ent-WeaponShotgunDoubleBarreledNonLethal = двуствольное ружье
    .desc = Бессмертная классика. Использует патроны .50.
    .suffix = { "" }
ent-WeaponShotgunEnforcerNonLethal = Силовик
    .desc = Дробовик нового поколения. Использует патроны .50.
    .suffix = { "" }
ent-WeaponShotgunKammererNonLethal = Каммер
    .desc = Когда старый дизайн Remington сочетается с современными материалами. Любимое оружие ополченцев во многих мирах. Использует патроны .50.
    .suffix = { "" }
