ent-ClothingHeadBandBlack = black bandana
    .desc = A black bandana to make you look cool.
    .suffix = { "" }
ent-ClothingHeadBandBlue = blue bandana
    .desc = A blue bandana to make you look cool.
    .suffix = { "" }
ent-ClothingHeadBandBotany = botany bandana
    .desc = A botany bandana to make you look cool, made from natural fibers.
    .suffix = { "" }
ent-ClothingHeadBandGold = gold bandana
    .desc = A gold bandana to make you look cool.
    .suffix = { "" }
ent-ClothingHeadBandGreen = green bandana
    .desc = A green bandana to make you look cool.
    .suffix = { "" }
ent-ClothingHeadBandGrey = grey bandana
    .desc = A grey bandana to make you look cool.
    .suffix = { "" }
ent-ClothingHeadBandRed = red bandana
    .desc = A red bandana to make you look cool.
    .suffix = { "" }
ent-ClothingHeadBandSkull = skull bandana
    .desc = A bandana with a skull to make you look even cooler.
    .suffix = { "" }
ent-ClothingHeadBandBrown = brown bandana
    .desc = A brown bandana to make you look cool.
    .suffix = { "" }
