ent-SpawnMobMonkeyPunpun = спавнер Пан Пана
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobMonkey = спавнер обезьяны
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobPurpleSnake = спавнер пурпурной змеи
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobSmallPurpleSnake = спавнер маленькой пурпурной змеи
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobSlug = спавнер слизняка
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobLizard = спавнер ящерицы
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobCrab = спавнер краба
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobGoat = спавнер козы
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobFrog = спавнер лягушки
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobBee = спавнер пчелы
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobParrot = спавнер попугая
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobButterfly = спавнер бабочки
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobCow = спавнер коровы
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobGorilla = спавнер гориллы
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobPenguin = спавнер пингвина
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
