ent-ClothingUniformMNKOfficeSkirt = офисная юбка MNK
    .desc = Наряд MNK в рамках офисного дресс-кода.
    .suffix = { "" }
ent-ClothingUniformMNKUnderGarment = нижнее белье MNK
    .desc = MNK обеспечил комфорт для важных мест.
    .suffix = { "" }
ent-ClothingUniformMNKGymBra = спортивный бюстгальтер MNK
    .desc = Максимальная производительность благодаря блокаторам пота MNK.
    .suffix = { "" }
ent-ClothingUniformMNKDressBlack = черное платье MNK
    .desc = Элегантное черное спортивное платье MNK.
    .suffix = { "" }
ent-ClothingUniformMNKBlackOveralls = черный комбинезон MNK
    .desc = Удобная майка и плотный черный комбинезон MNK.
    .suffix = { "" }
ent-ClothingUniformMNKBlackShoulder = наряд MNK с открытыми плечами
    .desc = Наряд MNK с открытыми плечами.
    .suffix = { "" }
ent-ClothingUniformMNKTracksuitBlack = черный спортивный костюм MNK
    .desc = Комплект легкой спортивной одежды MNK.
    .suffix = { "" }
