ent-ClothingBackpackDuffelFilled = { ent-ClothingBackpackDuffel }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingBackpackDuffelClownFilled = { ent-ClothingBackpackDuffelClown }
ent-ClothingBackpackDuffelSecurityFilled = { ent-ClothingBackpackDuffelSecurity }
ent-ClothingBackpackDuffelMedicalFilled = { ent-ClothingBackpackDuffelMedical }
ent-ClothingBackpackDuffelCaptainFilled = { ent-ClothingBackpackDuffelCaptain }
ent-ClothingBackpackDuffelEngineeringFilled = { ent-ClothingBackpackDuffelEngineering }
ent-ClothingBackpackDuffelScienceFilled = { ent-ClothingBackpackDuffelScience }
ent-ClothingBackpackDuffelHydroponicsFilled = { ent-ClothingBackpackDuffelHydroponics }
ent-ClothingBackpackDuffelMimeFilled = { ent-ClothingBackpackDuffelMime }
ent-ClothingBackpackDuffelChemistryFilled = { ent-ClothingBackpackDuffelChemistry }
ent-ClothingBackpackDuffelChaplainFilled = { ent-ClothingBackpackDuffel }
ent-ClothingBackpackDuffelMusicianFilled = { ent-ClothingBackpackDuffel }
ent-ClothingBackpackDuffelDetectiveFilled = { ent-ClothingBackpackDuffel }
ent-ClothingBackpackDuffelSalvageFilled = { ent-ClothingBackpackDuffelSalvage }
