ent-ClothingBackpackSatchelFilled = { ent-ClothingBackpackSatchel }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingBackpackSatchelSecurityFilled = { ent-ClothingBackpackSatchelSecurity }
ent-ClothingBackpackSatchelMedicalFilled = { ent-ClothingBackpackSatchelMedical }
ent-ClothingBackpackSatchelCaptainFilled = { ent-ClothingBackpackSatchelCaptain }
ent-ClothingBackpackSatchelEngineeringFilled = { ent-ClothingBackpackSatchelEngineering }
ent-ClothingBackpackSatchelScienceFilled = { ent-ClothingBackpackSatchelScience }
ent-ClothingBackpackSatchelHydroponicsFilled = { ent-ClothingBackpackSatchelHydroponics }
ent-ClothingBackpackSatchelChemistryFilled = { ent-ClothingBackpackSatchelChemistry }
ent-ClothingBackpackSatchelChaplainFilled = { ent-ClothingBackpackSatchel }
ent-ClothingBackpackSatchelMusicianFilled = { ent-ClothingBackpackSatchel }
ent-ClothingBackpackSatchelDetectiveFilled = { ent-ClothingBackpackSatchel }
ent-ClothingBackpackSatchelSalvageFilled = { ent-ClothingBackpackSatchelSalvage }
ent-ClothingBackpackSatchelDrone = { ent-ClothingBackpackSatchel }
