ent-UnaffiliatedIDCard = unaffiliated ID card
    .desc = A card displaying a name and other identifying details.
    .suffix = { "" }
ent-ExplorerIDCard = explorer ID card
    .desc = { ent-UnaffiliatedIDCard.desc }
    .suffix = { "" }
ent-StudentIDCard = student ID card
    .desc = { ent-UnaffiliatedIDCard.desc }
    .suffix = { "" }
ent-FreelancerIDCard = freelancer ID card
    .desc = { ent-UnaffiliatedIDCard.desc }
    .suffix = { "" }
