ent-UnaffiliatedIDCard = неаффилированная ID карта
    .desc = Карточка с именем и другими идентификационными данными.
    .suffix = { "" }
ent-ExplorerIDCard = ID исследователя
    .desc = { ent-UnaffiliatedIDCard.desc }
    .suffix = { "" }
ent-StudentIDCard = ID карта студента
    .desc = { ent-UnaffiliatedIDCard.desc }
    .suffix = { "" }
ent-FreelancerIDCard = ID карта фрилансера
    .desc = { ent-UnaffiliatedIDCard.desc }
    .suffix = { "" }
