ent-PosterLegitDejaVu = Deja Vu Area
ent-PosterLegitDontPanic = Don't Panic
ent-PosterContrabandSaucerNumberOne = Saucer #1!
ent-PosterLegitBarDrinks = Bar Poster
ent-PosterLegitBotanyFood = Fruit Basket
ent-PosterContrabandBreadLies = Bread Lies
ent-PosterLegitHotDonkExplosion = Donk!
ent-PosterLegitEatMeat = Eat Meat!
ent-PosterLegitMoreBread = More Bread!
ent-PosterLegitPieSlice = Pie Poster
ent-PosterLegitPizzaHope = Pizza Hope
ent-PosterLegitMedicate = Take Your Meds
ent-PosterLegitNoTouching = No Touching
ent-PosterMapArena = Arena Map
ent-PosterMapGlacier = Glacier Map
ent-PosterMapShoukou = Shōkō Map
ent-PosterLegitShoukou = Shōkō poster
ent-PosterContrabandSMSyndie = Syndie Moth - Nuclear Operation
ent-PosterLegitSMPoisoning = Safety Moth - Poisoning
ent-PosterLegitSMBoH = Safety Moth - Bag of Holding
ent-PosterLegitSMHardhats = Safety Moth - Hard hats
ent-PosterLegitSMFires = Safety Moth - Fires
ent-PosterLegitSMPiping = Safety Moth - Piping
ent-PosterLegitSMMeth = Safety Moth - Methamphetamine
ent-PosterLegitSMEpi = Safety Moth - Epinephrine
ent-PosterLegitSMPills = Safety Moth - Pill Bottles
ent-PosterLegitSMAnomalies = Safety Moth - Anomalies
ent-PosterLegitSMGlimmer = Safety Moth - Glimmer Safety Precautions
