ent-MailCarrierPDA = mail carrier PDA
    .desc = Hope this doesn't have any... JUNK MAIL.
    .suffix = { "" }
ent-SalvageTechPDA = { ent-EngineerPDA }
    .desc = { ent-EngineerPDA.desc }
    .suffix = { "" }
ent-ForensicMantisPDA = forensic mantis PDA
    .desc = Smells like tobacco, and justice.
    .suffix = { "" }
ent-EpistemicsPDA = acolyte PDA
    .desc = Preinstalled with plenty of brain teasers and religious conversion booklets.
    .suffix = { "" }
ent-MystaPDA = mystagogue PDA
    .desc = Practically radiating psychic energies... They actually have the Pope on speed dial!
    .suffix = { "" }
ent-ParamedicPDA = paramedic PDA
    .desc = Sweaty. Whoever uses this must be noided. Has a built-in health analyzer.
    .suffix = { "" }
ent-PrisonerPDA = prisoner PDA
    .desc = Clear, so you can make sure there's nothing being smuggled inside.
    .suffix = { "" }
ent-GladiatorPDA = gladiator PDA
    .desc = { ent-PrisonerPDA.desc }
    .suffix = { "" }
ent-ValetPDA = valet PDA
    .desc = Why isn't it gray?
    .suffix = { "" }
ent-CataloguerPDA = cataloguer PDA
    .desc = Probably the person most likely to use an antiquated note taking device. Placeholder sprite.
    .suffix = { "" }
ent-GuardPDA = guard PDA
    .desc = Red to hide the stains of prisoner blood.
    .suffix = { "" }
