ent-ClothingHeadMailCarrier = шляпа почтальона
    .desc = Пахнет хорошей пенсией.
    .suffix = { "" }
ent-ClothingHeadHoodMystic = мистический капюшон
    .desc = Чтобы содержать очень мудрую голову.
    .suffix = { "" }
ent-ClothingHeadHoodBrown = коричневый капюшон
    .desc = Жуткий.
    .suffix = { "" }
ent-ClothingHeadAreopagite = шляпа ареопагита
    .desc = Пугающий.
    .suffix = { "" }
ent-ClothingHeadTechPriest = шляпа автоматурга
    .desc = Защищает разум, создающий искусственный разум.
    .suffix = { "" }
ent-ClothingHeadTinfoil = шапочка из фольги
    .desc = Защищает вас от всех видов псионических атак.
    .suffix = { "" }
ent-ClothingHeadHatBellhop = кепка сервисника
    .desc = Все неудобства и унижения фески без какого-либо стиля!
    .suffix = { "" }
ent-ClothingHeadCage = изоляционная головная клетка
    .desc = Псионически изолирует голову того, кто находится внутри него. Требуется время для сопротивления.
    .suffix = { "" }
ent-ClothingHeadHelmetInsulated = изоляционная тюбетейка
    .desc = Псионически изолирует голову того, кто находится внутри него. Имеет некоторую защиту от физического урона.
    .suffix = { "" }
ent-ClothingHeadHatFezMantis = феска детектива
    .desc = Прекрасная красная феска с золотой кисточкой.
    .suffix = { "" }
ent-ClothingHeadPrisonGuard = шляпа тюремщика
    .desc = Предоставляет имунитет от отказа базовых человеческих прав, достоинства, или уважения.
    .suffix = { "" }
