ent-DisposalPipeBase = { "" }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-DisposalHolder = держатель утилизационного блока
ent-DisposalPipeBroken = поврежденная утилизационная труба
ent-DisposalPipe = участок утилизационной трубы
ent-DisposalTagger = маркировщик утилизационной трубы
ent-DisposalTrunk = ствол утилизационной трубы
ent-DisposalRouter = маршрутизатор утилизационной трубы
ent-DisposalRouterFlipped = { ent-DisposalRouter }
ent-DisposalJunction = развязка утилизационной трубы
ent-DisposalJunctionFlipped = { ent-DisposalJunction }
ent-DisposalYJunction = Y-развязка утилизационной трубы
ent-DisposalBend = изгиб утилизационной трубы
