ent-LockerMedicineFilled = { ent-LockerMedicine }
    .suffix = Заполненный
    .desc = { ent-LockerMedicine.desc }
ent-LockerWallMedicalFilled = настенный шкафчик для медикаментов
    .suffix = Заполненный
    .desc = { ent-LockerWallMedical.desc }
ent-LockerMedicalFilled = { ent-LockerMedical }
    .suffix = Заполненный
    .desc = { ent-LockerMedical.desc }
ent-LockerChemistryFilled = { ent-LockerChemistry }
    .suffix = Заполненный
    .desc = { ent-LockerChemistry.desc }
