ent-BaseBarSign = вывеска бара
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-BarSign = вывеска бара
ent-BarSignComboCafe = Комбо Кафе
ent-BarSignEmergencyRumParty = Чрезвычайная вечеринка с ромом
ent-BarSignLV426 = LV426
ent-BarSignMaidCafe = Мэйдо-кафе
ent-BarSignMalteseFalcon = Мальтийский сокол
ent-BarSignOfficerBeersky = Офицер Пивски
ent-BarSignRobustaCafe = Кафе Робуста
ent-BarSignTheAleNath = Эль'натх
ent-BarSignTheBirdCage = Вольер
ent-BarSignTheCoderbus = Кодербас
ent-BarSignTheDrunkCarp = Пьяный карп
ent-BarSignEngineChange = Замена двигателя
ent-BarSignTheHarmbaton = Хармбатон
ent-BarSignTheLightbulb = Лампочка
ent-BarSignTheLooseGoose = Весёлый гусь
ent-BarSignTheNet = Сеть
ent-BarSignTheOuterSpess = Открытый космос
ent-BarSignTheSingulo = Сингуло
ent-BarSignTheSun = Солнце
ent-BarSignWiggleRoom = Пространство для манёвра
ent-BarSignZocalo = Сокало
ent-BarSignEmprah = За Империю
