ent-PaintingBase = { ent-BaseSign }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-PaintingEmpty = пустая рама
ent-PaintingMoony = Абстракция №1
ent-PaintingPersistenceOfMemory = Постоянство памяти
ent-PaintingTheSonOfMan = Сын человеческий
ent-PaintingTheKiss = Поцелуй
ent-PaintingTheScream = Крик
ent-PaintingTheGreatWave = Большая волна в Канагаве
ent-PaintingCafeTerraceAtNight = Ночная терраса кафе
ent-PaintingNightHawks = Полуночники
ent-PaintingSkeletonCigarette = Череп скелета с зажжённой сигаретой
ent-PaintingSkeletonBoof = Череп MLG скелета с толстым косяком
ent-PaintingPrayerHands = Руки молящегося
ent-PaintingOldGuitarist = Старый гитарист
ent-PaintingOlympia = Олимпия
ent-PaintingSaturn = Сатурн, пожирающий своего сына
ent-PaintingSleepingGypsy = Спящая цыганка
ent-PaintingRedBlueYellow = Композиция с красным, синим и жёлтым
ent-PaintingAmogusTriptych = Триптих Амогус (Безымянный)
ent-PaintingHelloWorld = Здравствуй мир
