ent-BaseMobMalfunctioningRobot = сломанный робот
    .suffix = AI
    .desc = { ent-MobSiliconBase.desc }
ent-MobMalfunctioningRobotCutter = { ent-BaseMobMalfunctioningRobot }
    .desc = Небольшой робот, который кружит вокруг головокружительно. Он размахивает пилой.
    .suffix = { "" }
ent-MobMalfunctioningRobotPoisoner = { ent-BaseMobMalfunctioningRobot }
    .desc = Робот беспорядочно парит. Изнутри доносится вязкий булькающий звук.
    .suffix = { "" }
ent-MobMalfunctioningRobotTank = { ent-BaseMobMalfunctioningRobot }
    .desc = Робот на гусеницах, который искрит и шипит. Из его помятого бронированного шасси торчат потертые провода. Он таскает за собой пакет запуска.
    .suffix = { "" }
