ent-BlastDoorExterior1 = { ent-BlastDoor }
.suffix = { "" }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
ent-BlastDoorExterior1Open = { ent-BlastDoorOpen }
ent-BlastDoorExterior2 = { ent-BlastDoor }
ent-BlastDoorExterior2Open = { ent-BlastDoorOpen }
ent-BlastDoorExterior3 = { ent-BlastDoor }
ent-BlastDoorExterior3Open = { ent-BlastDoorOpen }
ent-BlastDoorBridge = { ent-BlastDoor }
ent-BlastDoorBridgeOpen = { ent-BlastDoorOpen }
ent-BlastDoorWindows = { ent-BlastDoor }
ent-BlastDoorWindowsOpen = { ent-BlastDoorOpen }
