rat-king-raise-army-name = Поднять армию
rat-king-raise-army-description = Потратьте некоторое количество голода, чтобы призвать дружественную крысу для вашей защиты.
rat-king-domain-name = Крысиное королевство
rat-king-domain-description = Потратьте некоторое количество голода, чтобы выпустить в воздух облако миазм.
rat-king-domain-popup = Потратьте некоторое количество голода, чтобы выпустить в воздух облако миазм.
rat-king-toggle-faction-name = Приказать крысам атаковать
rat-king-toggle-faction-description = Делает ваших крыс агрессивными или нейтральными.
rat-king-toggle-action-popup = Ваши крысы будут атаковать!
rat-king-toggle-action-popup-enabled = Ваши крысы теперь нейтральны.
rat-king-too-hungry = Вы слишком голодны, чтобы использовать эту способность!
