.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingNeckCloakCap = плащ капитана
ent-ClothingNeckCloakHos = плащ главы службы безопасности
ent-ClothingNeckCloakCe = плащ старшего инженера
ent-ClothingCloakCmo = плащ главного врача
ent-ClothingNeckCloakRd = плащ научного руководителя
ent-ClothingNeckCloakQm = плащ квартирмейстера
ent-ClothingNeckCloakHop = плащ главы персонала
ent-ClothingNeckCloakHerald = плащ герольда
ent-ClothingNeckCloakNanotrasen = плащ NanoTrasen
ent-ClothingNeckCloakCapFormal = торжественный плащ капитана
ent-ClothingNeckCloakAdmin = плащ админа
ent-ClothingNeckCloakMiner = плащ шахтёра
ent-ClothingNeckCloakTrans = вампирский плащ
ent-ClothingNeckCloakGoliathCloak = плащ голиафа
