ent-BaseAsteroidDebris = Обломки астероида
    .desc = { ent-BaseDebris.desc }
    .suffix = { "" }
ent-AsteroidDebrisSmall = Маленькие обломки астероида
    .desc = { ent-BaseAsteroidDebris.desc }
    .suffix = { "" }
ent-AsteroidDebrisMedium = Средние обломки астероида
    .desc = { ent-BaseAsteroidDebris.desc }
    .suffix = { "" }
ent-AsteroidDebrisLarge = Большие обломки астероида
    .desc = { ent-BaseAsteroidDebris.desc }
    .suffix = { "" }
ent-AsteroidDebrisLarger = Очень большие обломки астероида
    .desc = { ent-BaseAsteroidDebris.desc }
    .suffix = { "" }
