ent-MobXenoPraetorianNPC = Преторианец
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoDroneNPC = Дрон
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoQueenNPC = Королева
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoRavagerNPC = Опустошитель
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoRunnerNPC = Бегун
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoRounyNPC = Руни
    .desc = { ent-MobXenoRunnerNPC.desc }
    .suffix = { "" }
ent-MobXenoSpitterNPC = Спиттер
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobXenoPlayer = Рыльщик
    .desc = { ent-MobXeno.desc }
    .suffix = { "" }
ent-MobPurpleSnakeGhost = { ent-MobPurpleSnake }
    .desc = { ent-MobPurpleSnake.desc }
    .suffix = { "" }
ent-MobSmallPurpleSnakeGhost = { ent-MobSmallPurpleSnake }
    .desc = { ent-MobSmallPurpleSnake.desc }
    .suffix = { "" }
