ent-ClothingBeltUtility = пояс для инструментов
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingBeltChiefEngineer = пояс старшего инженера
ent-ClothingBeltAssault = штурмовой пояс
ent-ClothingBeltJanitor = пояс уборщика
ent-ClothingBeltMedical = пояс медика
ent-ClothingBeltPlant = пояс ботаника
ent-ClothingBeltSecurity = пояс охраны
ent-ClothingBeltSheath = сабельные ножны
ent-ClothingBeltBandolier = бандольер
ent-ClothingBeltChampion = пояс чемпиона
ent-ClothingBeltHolster = плечевая кобура
ent-ClothingBeltSyndieHolster = плечевая кобура синдиката
ent-ClothingBeltSecurityWebbing = РПС охраны
ent-ClothingBeltMilitaryWebbing = армейская РПС
ent-ClothingBeltMilitaryWebbingMed = армейская РПС медика
ent-ClothingBeltSuspenders = подтяжки
ent-ClothingBeltWand = пояс для палочек
