ent-ComputerAlert = консоль оповещений
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ComputerEmergencyShuttle = консоль аварийного шаттла
ent-BaseComputerShuttle = консоль управления шаттлом
ent-ComputerShuttle = консоль управления шаттлом
ent-ComputerShuttleSyndie = консоль управления шаттлом синдиката
ent-ComputerShuttleCargo = консоль управления грузовым шаттлом
ent-ComputerIFF = консоль системы опознования
ent-ComputerIFFSyndicate = консоль системы опознования
ent-ComputerPowerMonitoring = консоль контроля питания
ent-ComputerMedicalRecords = консоль медицинских карт
ent-ComputerCriminalRecords = консоль криминальных записей
ent-ComputerStationRecords = консоль станционного учёта
ent-ComputerCrewMonitoring = консоль мониторинга экипажа
ent-ComputerResearchAndDevelopment = исследовательская консоль
ent-ComputerAnalysisConsole = аналитическая консоль
ent-ComputerId = консоль ID карт
ent-computerBodyScanner = сканер тела
ent-ComputerComms = коммуникационная консоль
ent-SyndicateComputerComms = коммуникационная консоль синдиката
ent-ComputerSolarControl = консоль контроля солнечных батарей
ent-ComputerRadar = консоль сканера массы
ent-ComputerCargoShuttle = консоль вызова грузового шаттла
ent-ComputerCargoOrders = консоль заказа грузов
ent-ComputerCloningConsole = консоль клонирования
ent-ComputerSurveillanceCameraMonitor = монитор камер
ent-ComputerSurveillanceWirelessCameraMonitor = монитор беспроводных камер
ent-ComputerPalletConsole = компьютер продажи груза
