ent-SpawnMobShiva = спавнер Шивы
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobKangarooWillow = спавнер Уиллоу
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobKangaroo = спавнер космического кенгуру
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobBoxingKangaroo = спавнер кенгуру-боксера
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobSpaceSpider = спавнер космического паука
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesBlue = спавнер слизня (синий)
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesBlueAngry = спавнер слизня (синий, злой)
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesGreen = спавнер слизня (зеленый)
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesGreenAngry = спавнер слизня (зеленый, злой)
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesYellow = спавнер слизня (жёлтый)
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesYellowAngry = спавнер слизня (жёлтый, злой)
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobSmile = спавнер слизня
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
