ent-CratePartsT3 = tier 3 parts crate
    .desc = Contains 5 random tier 3 parts for upgrading machines.
    .suffix = { "" }
ent-CratePartsT3T4 = tier 3/4 parts crate
    .desc = Contains 5 random tier 3 or 4 parts for upgrading machines.
    .suffix = { "" }
ent-CratePartsT4 = tier 4 parts crate
    .desc = Contains 5 random tier 4 parts for upgrading machines.
    .suffix = { "" }
