ent-PartGolem = часть тела голема
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-TorsoGolemCult = торс голема
    .desc = { ent-PartGolem.desc }
    .suffix = { "" }
ent-HeadGolemCult = голова голема
    .desc = { ent-PartGolem.desc }
    .suffix = { "" }
ent-LeftArmGolemCult = левая рука голема
    .desc = { ent-PartGolem.desc }
    .suffix = { "" }
ent-RightArmGolemCult = правая рука голема
    .desc = { ent-PartGolem.desc }
    .suffix = { "" }
ent-LeftHandGolemCult = левая ладонь голема
    .desc = { ent-PartGolem.desc }
    .suffix = { "" }
ent-RightHandGolemCult = правая ладонь голема
    .desc = { ent-PartGolem.desc }
    .suffix = { "" }
ent-LeftLegGolemCult = левая нога голема
    .desc = { ent-PartGolem.desc }
    .suffix = { "" }
ent-RightLegGolemCult = правая нога голема
    .desc = { ent-PartGolem.desc }
    .suffix = { "" }
