ent-FoodDonkpocketBase = { ent-FoodInjectableBase }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-FoodDonkpocket = донк-покет
ent-FoodDonkpocketWarm = теплый донк-покет
ent-FoodDonkpocketDank = данк-покет
ent-FoodDonkpocketDankWarm = теплый данк-покет
ent-FoodDonkpocketSpicy = спайси-покет
ent-FoodDonkpocketSpicyWarm = теплый спайси-покет
ent-FoodDonkpocketTeriyaki = терияки-покет
ent-FoodDonkpocketTeriyakiWarm = теплый терияки-покет
ent-FoodDonkpocketPizza = пицца-покет
ent-FoodDonkpocketPizzaWarm = теплый пицца-покет
ent-FoodDonkpocketHonk = хонк-покет
ent-FoodDonkpocketHonkWarm = теплый хонк-покет
ent-FoodDonkpocketBerry = ягодный покет
ent-FoodDonkpocketBerryWarm = теплый ягодный покет
ent-FoodDonkpocketGondola = гондола-покет
ent-FoodDonkpocketGondolaWarm = теплый гондола-покет
ent-FoodDonkpocketDink = динк-покет
