ent-FoodDonutBase = { ent-FoodInjectableBase }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-FoodDonutPlain = обычный пончик
ent-FoodDonutJellyPlain = обычный желейный пончик
ent-FoodDonutHomer = пончик
ent-FoodDonutChaos = пончик хаоса
ent-FoodDonutMeat = мясной пончик
ent-FoodDonutPink = розовый пончик
ent-FoodDonutSpaceman = космонавтский пончик
ent-FoodDonutApple = яблочный пончик
ent-FoodDonutCaramel = карамельный пончик
ent-FoodDonutChocolate = шоколадный пончик
ent-FoodDonutBlumpkin = синетыквенный пончик
ent-FoodDonutBungo = бунго пончик
ent-FoodDonut = матча пончик
ent-FoodDonutSweetpea = пончик из душистого горошка
ent-FoodDonutJellyHomer = желейный пончик
ent-FoodDonutJellyPink = розовый желейный пончик
ent-FoodDonutJellySpaceman = космонавтский желейный пончик
ent-FoodDonutJellyApple = яблочный желейный пончик
ent-FoodDonutJellyCaramel = карамельный желейный пончик
ent-FoodDonutJellyChocolate = шоколадный желейный пончик
ent-FoodDonutJellyBlumpkin = синетыквенный желейный пончик
ent-FoodDonutJellyBungo = бунго желейный пончик
ent-FoodDonutJelly = матча желейный пончик
ent-FoodDonutJellySweetpea = желейный пончик из душистого горошка
ent-FoodDonutJellySlugcat = слизнекотовый желейный пончик
ent-FoodDonutPoison = { ent-FoodDonutPink }
