ent-FoodBakedBase = { ent-FoodInjectableBase }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-FoodBakedMuffin = маффин
ent-FoodBakedMuffinBerry = ягодный маффин
ent-FoodBakedMuffinCherry = вишнёвый маффин
ent-FoodBakedMuffinBluecherry = маффин с голубой вишней
ent-FoodBakedBunHoney = медовая булочка
ent-FoodBakedBunHotX = булочка хоткросс
ent-FoodBakedBunMeat = мясная булочка
ent-FoodBakedCookie = печенье
ent-FoodBakedCookieFortune = печенье с предсказаниями
ent-FoodBakedCookieOatmeal = овсяное печенье
ent-FoodBakedCookieRaisin = печенье с изюмом
ent-FoodBakedCookieSugar = сахарное печенье
ent-FoodBakedNugget = куриный наггетс
ent-FoodBakedPancake = блинчик
ent-FoodBakedPancakeBb = блинчик с черникой
ent-FoodBakedPancakeCc = блинчик с шоколадной крошкой
ent-FoodBakedWaffle = вафли
ent-FoodBakedWaffleSoy = соевые вафли
ent-FoodBakedWaffleSoylent = сойлент вафли
ent-FoodBakedWaffleRoffle = roffle-вафли
ent-FoodBakedPretzel = крендель с маком
ent-FoodBakedCannoli = канноли
