ent-FoodPieBase = { ent-FoodInjectableBase }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-FoodPieSliceBase = { ent-FoodInjectableBase }
ent-FoodPieApple = яблочный пирог
ent-FoodPieAppleSlice = кусок яблочного пирога
ent-FoodPieBaklava = пахлава
ent-FoodPieBaklavaSlice = кусок пахлавы
ent-FoodPieBananaCream = кремовый банановый пирог
ent-FoodPieClafoutis = ягодный клафути
ent-FoodPieClafoutisSlice = кусок ягодного клафути
ent-FoodPieCherry = вишнёвый пирог
ent-FoodPieCherrySlice = кусок вишнёвого пирога
ent-FoodPieMeat = мясной пирог
ent-FoodPieMeatSlice = кусок мясного пирога
ent-FoodPieXeno = ксено-пирог
ent-FoodPieXenoSlice = кусок ксено-пирога
ent-FoodPieFrosty = морозный пирог
ent-FoodPieFrostySlice = кусок морозного пирога
ent-FoodPieAmanita = пирог из мухоморов
ent-FoodPiePlump = пирог из толстошлемника
ent-FoodTartGrape = виноградный тарт
ent-FoodTartMime = мимский тарт
ent-FoodTartGapple = тарт из золотых яблок с крошкой
ent-FoodTartCoco = шоколадный тарт с лавой
