ent-FoodPizzaBase = { ent-FoodInjectableBase }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-FoodPizzaSliceBase = { ent-FoodInjectableBase }
ent-FoodPizzaMargherita = пицца маргарита
ent-FoodPizzaMargheritaSlice = кусок пиццы маргарита
ent-FoodPizzaMeat = мясная пицца
ent-FoodPizzaMeatSlice = кусок мясной пиццы
ent-FoodPizzaMushroom = грибная пицца
ent-FoodPizzaMushroomSlice = кусок грибной пиццы
ent-FoodPizzaVegetable = овощная пицца
ent-FoodPizzaVegetableSlice = кусок овощной пиццы
ent-FoodPizzaDonkpocket = пицца донк-покет
ent-FoodPizzaDonkpocketSlice = кусок пиццы донк-покет
ent-FoodPizzaDank = расслабляющая пицца
ent-FoodPizzaDankSlice = кусок расслабляющей пиццы
ent-FoodPizzaSassysage = дерзкалбасная пицца
ent-FoodPizzaSassysageSlice = кусок дерзкалбасной пиццы
ent-FoodPizzaPineapple = Гавайская пицца
ent-FoodPizzaPineappleSlice = кусок ананасовой пиццы
ent-FoodPizzaArnold = пицца Арнольда
ent-FoodPizzaArnoldSlice = кусок пиццы Арнольда
ent-FoodPizzaMoldySlice = кусок заплесневелой пиццы
