ent-SignalSwitchDirectional = сигнальный переключатель
    .suffix = направленный
    .desc = { ent-SignalSwitch.desc }
ent-SignalButtonDirectional = сигнальная кнопка
    .suffix = направленный
    .desc = { ent-SignalButton.desc }
ent-ApcNetSwitchDirectional = переключатель сети ЛКП
    .suffix = направленный
    .desc = { ent-ApcNetSwitch.desc }
