ent-BaseWeaponBattery = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-BaseWeaponBatterySmall = { ent-BaseWeaponBattery }
ent-WeaponLaserGun = старомодный лазерный пистолет
ent-WeaponLaserCarbine = лазерный карабин
ent-WeaponLaserCarbinePractice = тренировочный лазерный карабин
ent-WeaponPulsePistol = импульсный пистолет
ent-WeaponPulseCarbine = импульсный карабин
ent-WeaponPulseRifle = импульсная винтовка
ent-WeaponLaserCannon = лазерная пушка
ent-WeaponXrayCannon = рентгеновская пушка
ent-WeaponDisabler = дизейблер
ent-WeaponDisablerPractice = тренировочный дизейблер
ent-WeaponTaser = тазер
ent-WeaponAntiqueLaser = антикварный лазерный пистолет
ent-WeaponAdvancedLaser = продвинутый лазерный пистолет
