ent-PosterLegitDejaVu = Deja Vu
    .desc = Это твой первый раз здесь. Если эта станция кажется знакомой, немедленно сообщите сотруднику Нянотрайзен.
    .suffix = { "" }
ent-PosterLegitDontPanic = Без паники!
    .desc = Если все было достаточно спокойно, чтобы у меня нету паники. Это зеленый сгусток слизи с руками? Светящийся красный язык? Летающие зубы?
    .suffix = { "" }
ent-PosterContrabandSaucerNumberOne = Saucer #1!
    .desc = Out of every station in the NyanoTrasen jurisdiction, Saucer was rated #1 out of 5! Congratulations!
    .suffix = { "" }
ent-PosterLegitBarDrinks = Барный постер
    .desc = Бармен всегда готов выслушать и поддержать вас. Заходи!
    .suffix = { "" }
ent-PosterLegitBotanyFood = Фруктовая тарелка
    .desc = Ботаники всегда упорно трудятся! Остановись и попробуй что они предлагают!
    .suffix = { "" }
ent-PosterContrabandBreadLies = Хлеб врет!
    .desc = Вам врут. Нет никакого "Большого хлеба". ЕГО НЕТ! Перестаньте искать его.
    .suffix = { "" }
ent-PosterLegitHotDonkExplosion = Donk!
    .desc = Почувствуйте взрыв вкуса в каждом кусочке нашей продукции! DONK!
    .suffix = { "" }
ent-PosterLegitEatMeat = Ешь мясо!
    .desc = Кому нужны фрукты или овощи? ЕШЬ МЯСО! Отрасти мышцы, которыми можно свергнуть гиганта!
    .suffix = { "" }
ent-PosterLegitMoreBread = Больше хлеба!
    .desc = Никогда не достаточно хлеба! ДЕЛАЙ БОЛЬШЕ!
    .suffix = { "" }
ent-PosterLegitPieSlice = Пирог
    .desc = Пироги вкусные и полезные! Уговори повора сделать несколько.
    .suffix = { "" }
ent-PosterLegitPizzaHope = Надежда пиццы
    .desc = В темные времена есть лишь одна надежда, ПИЦЦА! Немедленно уговори квартермейстера заказать несколько коробок!
    .suffix = { "" }
ent-PosterLegitMedicate = Прими лекарства!
    .desc = Возможные побочные эффекты: амнезия, несварение желудка, анемия, зуд, температура, головные боли, тошнота и многие другие.
ent-PosterLegitNoTouching = Не трогать!
    .desc = Сказали же, не трогать!
    .suffix = { "" }
ent-PosterLegitChknDnnr = Winner Winner Chicken Dinner
    .desc = An advertisement for crispy fried chicken.
    .suffix = { "" }
ent-PosterMapArena = Arena Map
    .desc = A map of Arena station.
    .suffix = { "" }
ent-PosterMapGlacier = Glacier Map
    .desc = A map of Glacier outpost.
    .suffix = { "" }
ent-PosterMapShoukou = Shōkō Map
    .desc = Shōkō no mappu desu.
    .suffix = { "" }
ent-PosterMapNorthway = Northway Map
    .desc = A map of Northway spaceship.
    .suffix = { "" }
ent-PosterLegitShoukou = Shōkō poster
    .desc = Funny symbols that can be read as Shōkō or Xiaogang, depending on who you ask.
    .suffix = { "" }
ent-PosterContrabandSMSyndie = Syndie Moth - Nuclear Operation
    .desc = Syndie Moth™ tells the viewer to keep the nuclear authentication disk unsecured. "Peace was never an option!"
    .suffix = { "" }
ent-PosterLegitSMPoisoning = Safety Moth - Poisoning
    .desc = Safety Moth™ tells the viewer not to poison the station donuts.
    .suffix = { "" }
ent-PosterLegitSMBoH = Safety Moth - Bag of Holding
    .desc = Safety Moth™ informs the viewer of the dangers of Bags of Holding. "Remember! Bags of Holding may be pretty, but they're also pretty dangerous! Never put one inside another!"
    .suffix = { "" }
ent-PosterLegitSMHardhats = Safety Moth - Hard hats
    .desc = Safety Moth™ tells the viewer to wear hard hats in cautious areas. "It's like a lamp on your head!"
    .suffix = { "" }
ent-PosterLegitSMFires = Safety Moth - Fires
    .desc = Safety Moth™ promotes safe handling of plasma and to keep firefighting equipment within hand reach.
    .suffix = { "" }
ent-PosterLegitSMPiping = Safety Moth - Piping
    .desc = Safety Moth™ tells atmospheric technicians the correct types of piping to be used. "Pipes, not Pumps! Proper pipe placement prevents poor performance!"
    .suffix = { "" }
ent-PosterLegitSMMeth = Safety Moth - Methamphetamine
    .desc = Safety Moth™ tells the viewer to seek CMO approval before cooking methamphetamine. "Stay close to the target temperature, and never go over!"
    .suffix = { "" }
ent-PosterLegitSMEpi = Safety Moth - Epinephrine
    .desc = Safety Moth™ informs the viewer to help injured/deceased crewmen with their epinephrine injectors. "Epipen a pal when they're in peril! Prevent organ rot with this one simple trick!"
    .suffix = { "" }
ent-PosterLegitSMPills = Safety Moth - Pill Bottles
    .desc = Safety Moth™ informs the viewer that leaving pills unsupervised on tables could lead to unforeseen consequences. "Hungry critters love to eat everything! Keep your pills safe in crates and pill bottles!"
    .suffix = { "" }
ent-PosterLegitSMAnomalies = Safety Moth - Anomalies
    .desc = Safety Moth™ promotes proper safety equipment when working around anomalies. "Every good Moths wears protection when working with anomalies, but don't get too close! Not everything that glows is a friend!"
    .suffix = { "" }
ent-PosterLegitSMGlimmer = Safety Moth - Glimmer Safety Precautions
    .desc = Safety Moth™ tells the viewer to wear insulative equipments and hide in lockers when the glimmer gets within critical levels. Evacuating might be a better strategy.
    .suffix = { "" }
