ent-AsteroidRock = астероидная порода
    .desc = Каменистый астероид.
    .suffix = Низкое содержание руды
ent-AsteroidRockMining = астероидная порода
    .desc = Это астероид.
    .suffix = Высокое содержание руды
ent-WallRock = порода
    .desc = { ent-BaseStructure.desc }
    .suffix = { "" }
ent-WallRockGold = { ent-WallRock }
    .desc = Рудная жила, богатая золотом.
    .suffix = Золото
ent-WallRockPlasma = { ent-WallRock }
    .desc = Рудная жила, богатая плазмой.
    .suffix = Плазма
ent-WallRockQuartz = { ent-WallRock }
    .desc = Рудная жила, богатая кварцем.
    .suffix = Кварц
ent-WallRockSilver = { ent-WallRock }
    .desc = Рудная жила, богатая серебром.
    .suffix = Серебро
ent-WallRockTin = { ent-WallRock }
    .desc = Рудная жила, богатая сталью.
    .suffix = Сталь
ent-WallRockUranium = { ent-WallRock }
    .desc = Рудная жила, богатая ураном.
    .suffix = Уран
ent-WallRockArtifactFragment = { ent-WallRock }
    .desc = Обыкновенная порода. Погодите, что это торчит из нее?
    .suffix = Фрагмент Артефакта
ent-WallRockBasalt = { ent-WallRock }
    .desc = { ent-WallRock.desc }
    .suffix = { "" }
ent-WallRockBasaltGold = { ent-WallRockBasalt }
    .desc = { ent-WallRockGold.desc }
    .suffix = Золото
ent-WallRockBasaltPlasma = { ent-WallRockBasalt }
    .desc = { ent-WallRockPlasma.desc }
    .suffix = Плазма
ent-WallRockBasaltQuartz = { ent-WallRockBasalt }
    .desc = { ent-WallRockQuartz.desc }
    .suffix = Кварц
ent-WallRockBasaltSilver = { ent-WallRockBasalt }
    .desc = { ent-WallRockSilver.desc }
    .suffix = Серебро
ent-WallRockBasaltTin = { ent-WallRockBasalt }
    .desc = { ent-WallRockTin.desc }
    .suffix = Сталь
ent-WallRockBasaltUranium = { ent-WallRockBasalt }
    .desc = { ent-WallRockUranium.desc }
    .suffix = Уран
ent-WallRockBasaltArtifactFragment = { ent-WallRockBasalt }
    .desc = { ent-WallRockArtifactFragment.desc }
    .suffix = Фрагмент Артефакта
ent-WallRockSnow = { ent-WallRock }
    .desc = { ent-WallRock.desc }
    .suffix = { "" }
ent-WallRockSnowGold = { ent-WallRockSnow }
    .desc = { ent-WallRockGold.desc }
    .suffix = Золото
ent-WallRockSnowPlasma = { ent-WallRockSnow }
    .desc = { ent-WallRockPlasma.desc }
    .suffix = Плазма
ent-WallRockSnowQuartz = { ent-WallRockSnow }
    .desc = { ent-WallRockQuartz.desc }
    .suffix = Кварц
ent-WallRockSnowSilver = { ent-WallRockSnow }
    .desc = { ent-WallRockSilver.desc }
    .suffix = Серебро
ent-WallRockSnowTin = { ent-WallRockSnow }
    .desc = { ent-WallRockTin.desc }
    .suffix = Сталь
ent-WallRockSnowUranium = { ent-WallRockSnow }
    .desc = { ent-WallRockUranium.desc }
    .suffix = Уран
ent-WallRockSnowArtifactFragment = { ent-WallRockSnow }
    .desc = { ent-WallRockArtifactFragment.desc }
    .suffix = Фрагмент Артефакта
