ent-PuddleBase = { "" }
    .desc = { "" }
    .suffix = { "" }
ent-EvaporatingPuddle = { ent-PuddleBase }
    .desc = { ent-PuddleBase.desc }
    .suffix = { "" }
ent-PuddleGibblet = потроха
    .desc = Грубо.
    .suffix = { "" }
ent-PuddleSplatter = лужа
    .desc = Лужа.
    .suffix = { "" }
ent-PuddleBlood = кровь
    .desc = Плохой знак.
    .suffix = { "" }
ent-PuddleVomitToxin = токсичная рвота
    .desc = Вы скорее всего не хотите находиться близко к этому.
    .suffix = { "" }
ent-PuddleWriting = надпись
    .desc = Немного жидкости.
    .suffix = { "" }
