ent-ClothingHeadHatFedoraBlack = black fedora
    .desc = A black fedora. Lookin' classy.
    .suffix = { "" }
ent-ClothingHeadHatFedoraChoc = brown fedora
    .desc = A brown fedora. Lookin' snazzy.
    .suffix = { "" }
ent-ClothingHeadHatFedoraWhite = white fedora
    .desc = A white fedora. Lookin' ritzy.
    .suffix = { "" }
ent-ClothingHeadHatFlatBlack = black flat cap
    .desc = A black flat cap, for driving cabs and delivering the papers.
    .suffix = { "" }
ent-ClothingHeadHatFlatBrown = brown flat cap
    .desc = A brown flat cap, for driving cabs and delivering the papers.
    .suffix = { "" }
ent-ClothingHeadHatFlatSyndie = black flat cap
    .desc = A black flat cap, for sending a message.
    .suffix = Weapon
