ent-ClothingHeadHatFedoraBlack = черная федора
    .desc = Черная федора. Выглядишь классно.
    .suffix = { "" }
ent-ClothingHeadHatFedoraChoc = коричневая федора
    .desc = Коричневая федора. Шикарно выглядишь.
    .suffix = { "" }
ent-ClothingHeadHatFedoraWhite = белая федора
    .desc = Белая федора. Шикарно выглядишь.
    .suffix = { "" }
ent-ClothingHeadHatFlatBlack = черная кепка
    .desc = Черная плоская кепка для вождения такси и доставки бумаг.
    .suffix = { "" }
ent-ClothingHeadHatFlatBrown = коричневая кепка
    .desc = Коричневая плоская кепка для вождения такси и доставки бумаг.
    .suffix = { "" }
ent-ClothingHeadHatFlatSyndie = чёрная кепка
    .desc = Черная плоская кепка, для того что-бы отправить сообщение.
    .suffix = Weapon
