ent-BoxMagazinePistolCaselessRifle = коробка магазинов с .25 безгильзовыми
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-BoxMagazinePistolCaselessRifleHighVelocity = коробка магазинов с .25 безгильзовыми (высокоскоростными)
ent-BoxMagazinePistolCaselessRiflePractice = коробка магазинов с .25 безгильзовыми (учебными)
ent-BoxMagazineCaselessRifleRubber = коробка магазинов с .25 безгильзовыми (резиновыми)
ent-BoxMagazineLightRifle = коробка магазинов с .30 винтовочными
ent-BoxMagazineLightRifleHighVelocity = коробка магазинов с .30 винтовочными (высокоскоростными)
ent-BoxMagazineLightRiflePractice = коробка магазинов с .30 винтовочными (учебными)
ent-BoxMagazineLightRifleRubber = коробка магазинов с .30 винтовочными (резиновыми)
ent-BoxMagazineMagnumSubMachineGun = коробка магазинов для Вектор
ent-BoxMagazineMagnumSubMachineGunHighVelocity = коробка магазинов для Вектор (высокоскоростными)
ent-BoxMagazineMagnumSubMachineGunPractice = коробка магазинов для Вектор (учебными)
ent-BoxMagazineMagnumSubMachineGunRubber = коробка магазинов для Вектор (резиновыми)
ent-BoxMagazinePistolSubMachineGunTopMounted = коробка магазинов WT550 .35 авто
ent-BoxMagazinePistol = коробка магазинов пистолетных .35 авто
ent-BoxMagazinePistolHighVelocity = коробка магазинов пистолетных .35 авто (высокоскоростные)
ent-BoxMagazinePistolPractice = коробка магазинов пистолетных .35 авто (учебные)
ent-BoxMagazinePistolRubber = коробка магазинов пистолетных .35 авто (резиновые)
ent-BoxMagazinePistolHighCapacity = коробка магазинов автопистолетных .35 авто
ent-BoxMagazinePistolHighCapacityHighVelocity = коробка магазинов автопистолетных .35 авто (высокоскоростные)
ent-BoxMagazinePistolHighCapacityPractice = коробка магазинов автопистолетных .35 авто (учебные)
ent-BoxMagazinePistolHighCapacityRubber = коробка магазинов автопистолетных .35 авто (резиновые)
ent-BoxMagazinePistolSubMachineGun = коробка магазинов для ПП .35 авто
ent-BoxMagazinePistolSubMachineGunHighVelocity = коробка магазинов для ПП .35 авто (высокоскоростные)
ent-BoxMagazinePistolSubMachineGunPractice = коробка магазинов для ПП .35 авто (учебные)
ent-BoxMagazinePistolSubMachineGunRubber = коробка магазинов для ПП .35 авто (резиновые)
ent-BoxMagazineShotgun = коробка барабанов (.50 дробь)
ent-BoxMagazineShotgunBeanbag = коробка барабанов (.50 травматические)
ent-BoxMagazineShotgunSlug = коробка барабанов (.50 пуля)
ent-BoxMagazineShotgunIncendiary = коробка барабанов (.50 зажигательные)
ent-BoxAmmoProvider = { ent-BoxCardboard }
ent-BoxBeanbag = коробка ружейных патронов (травматических)
ent-BoxLethalshot = коробка ружейных патронов (летальных)
ent-BoxShotgunSlug = коробка ружейных патронов (пули)
ent-BoxShotgunFlare = коробка ружейных патронов (фальшфейеры)
ent-BoxShotgunIncendiary = коробка ружейных патронов (зажигательные)
ent-BoxShotgunPractice = коробка ружейных патронов (учебные)
ent-BoxShellTranquilizer = коробка ружейных патронов (транквилизаторы)
ent-BoxMagazineRifle = коробка магазинов с .20 винтовочными
ent-BoxMagazineRifleHighVelocity = коробка магазинов с .20 винтовочными (высокоскоростные)
ent-BoxMagazineRiflePractice = коробка магазинов с .20 винтовочными (учебные)
ent-BoxMagazineRifleRubber = коробка магазинов с .20 винтовочными (резиновые)
