ent-BoxCardboard = картонная коробка
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-BoxMousetrap = коробка мышеловок
ent-BoxLightbulb = коробка лампочек
ent-BoxLighttube = коробка лампочек-трубок
ent-BoxLightMixed = коробка смешанных лампочек
ent-BoxPDA = коробка КПК
ent-BoxID = коробка ID карт
ent-BoxHeadset = коробка гарнитур
ent-BoxMesonScanners = коробка инженерных очков
ent-BoxMRE = И.Р.П.
ent-BoxHugHealing = коробка обнимашек
ent-BoxInflatable = коробка надувных стен
ent-BoxPerformer = коробка в честь дня Хацунэ Мику
ent-BoxFlare = коробка фальшфейеров
ent-BoxTrashbag = коробка мусорных пакетов
ent-BoxEncryptionKeyPassenger = ящик с ключами шифрования для ассистентов
ent-BoxEncryptionKeyCargo = ящик для ключей шифрования карго
ent-BoxEncryptionKeyEngineering = ящик для ключей шифрования инженернии
ent-BoxEncryptionKeyMedicalScience = ящик для ключей шифрования науч-мед отдела
ent-BoxEncryptionKeyMedical = ящик для ключей шифрования медицинского отдела
ent-BoxEncryptionKeyRobo = ящик для ключей шифрования робототехники
ent-BoxEncryptionKeyScience = ящик для ключей шифрования научного отдела
ent-BoxEncryptionKeySecurity = ящик для ключей шифрования службы безопасности
ent-BoxEncryptionKeyService = ящик для ключей шифрования сервисного отдела
