ent-FoodBreadCorn = кукурузный хлеб
    .desc = Немного добротного, домашнего, в кантри-стиле знаменитого, револьверо-палящего, треклятого, ииихааа кукурузного хлеба.
    .suffix = { "" }
ent-FoodBreadCornSlice = ломтик кукурузного хлеба
    .desc = Кусочек кукурузного хлеба.
    .suffix = { "" }
ent-FoodBreadSausage = сосисочный хлеб
    .desc = Не думайте слишком много об этом.
    .suffix = { "" }
ent-FoodBreadSausageSlice = ломтик сосичоного хлеба
    .desc = Не думайте слишком много об этом.
    .suffix = { "" }
ent-FoodBreadFrenchToast = ф тост
    .desc = Ломтик хлеба, смочённый во взбитой яичной смеси.
    .suffix = { "" }
ent-FoodBreadJellySlice = тост с желе
    .desc = Как если бы наука собиралась пустить своих слаймов на тосты!
    .suffix = { "" }
ent-FoodBreadTwoSlice = два ломтика
    .desc = Первоклассно.
    .suffix = { "" }
