ent-ClothingCostumeNaota = turquoise hoodie and shorts
    .desc = A hoodie with a small kangaroo pouch.
    .suffix = { "" }
ent-ClothingUniformRat = rat king fan outfit
    .desc = Declare your allegiance to the rodent monarch, as well as your desire to see the station burn *at the same time!*
    .suffix = { "" }
ent-ClothingUniformDressRed = red dress
    .desc = A voluminous, fancy red dress.
    .suffix = { "" }
ent-ClothingUniformSwimsuitBlue = blue swimsuit
    .desc = A form-fitting, hydrodynamic blue swimsuit.
    .suffix = { "" }
ent-ClothingUniformSchoolGakuranBlack = gakuran uniform
    .desc = A sleek school uniform.
    .suffix = { "" }
