ent-ClothingHandsGlovesBoxingRed = красные боксёрские перчатки
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingHandsGlovesBoxingBlue = синие боксёрские перчатки
ent-ClothingHandsGlovesBoxingGreen = зелёные боксёрские перчатки
ent-ClothingHandsGlovesBoxingYellow = жёлтые боксёрские перчатки
ent-ClothingHandsGlovesCaptain = капитанские перчатки
ent-ClothingHandsGlovesIhscombat = боевые перчатки IHS
ent-ClothingHandsGlovesLatex = латексные перчатки
ent-ClothingHandsGlovesNitrile = нитриловые перчатки
ent-ClothingHandsGlovesLeather = кожаные перчатки ботаника
ent-ClothingHandsGlovesPowerglove = силовые перчатки
ent-ClothingHandsGlovesRobohands = роборукие перчатки
ent-ClothingHandsGlovesSpaceNinja = перчатки космического ниндзя
ent-ClothingHandsGlovesCombat = боевые перчатки
ent-ClothingHandsGlovesFingerless = беспалые перчатки
ent-ThievingGloves = чёрные перчатки
