ent-BaseGenerator = генератор
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-BaseGeneratorWallmount = настенный генератор
ent-BaseGeneratorWallmountFrame = каркас настенного генератора
ent-GeneratorBasic = { ent-BaseGenerator }
ent-GeneratorPlasma = { ent-BaseGenerator }
ent-GeneratorUranium = { ent-BaseGenerator }
ent-GeneratorWallmountBasic = { ent-BaseGeneratorWallmount }
ent-GeneratorWallmountAPU = ВСУ шаттла
ent-GeneratorRTG = РИТЭГ
ent-GeneratorRTGDamaged = повреждённый РИТЭГ
