ent-BaseShield = базовый щит
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-RiotShield = противоударный щит
ent-RiotLaserShield = противолазерный щит
ent-RiotBulletShield = противопульный щит
ent-WoodenBuckler = деревянный баклер
ent-MakeshiftShield = импровизированный щит
ent-ClockworkShield = часовой щит
ent-MirrorShield = зеркальный щит
