ent-filingCabinet = картотечный шкаф
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-filingCabinetTall = высокий шкаф
ent-filingCabinetDrawer = комод
ent-BaseBureaucraticStorageFill = { "" }
ent-filingCabinetRandom = { ent-filingCabinet }
ent-filingCabinetTallRandom = { ent-filingCabinetTall }
ent-filingCabinetDrawerRandom = { ent-filingCabinetDrawer }
