ent-DoorElectronics = микросхема шлюза
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-DoorElectronicsService = { ent-DoorElectronics }
    .suffix = Service
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsTheatre = { ent-DoorElectronics }
    .suffix = Theatre
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsChapel = { ent-DoorElectronics }
    .suffix = Chapel
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsJanitor = { ent-DoorElectronics }
    .suffix = Janitor
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsKitchen = { ent-DoorElectronics }
    .suffix = Kitchen
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsBar = { ent-DoorElectronics }
    .suffix = Bar
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsBarKitchen = { ent-DoorElectronics }
    .suffix = Bar
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsHydroponics = { ent-DoorElectronics }
    .suffix = Hydroponics
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsExternal = { ent-DoorElectronics }
    .suffix = External
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsCargo = { ent-DoorElectronics }
    .suffix = Cargo
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsExternalEngineering = { ent-DoorElectronics }
    .suffix = External, Engineering
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsExternalAtmospherics = { ent-DoorElectronics }
    .suffix = External, Atmospherics
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsKitchenHydroponics = { ent-DoorElectronics }
    .suffix = Kitchen/Hydroponics
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsEngineering = { ent-DoorElectronics }
    .suffix = Engineering
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsAtmospherics = { ent-DoorElectronics }
    .suffix = Atmospherics
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsSalvage = { ent-DoorElectronics }
    .suffix = Salvage
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsQuartermaster = { ent-DoorElectronics }
    .suffix = Quartermaster
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsMedical = { ent-DoorElectronics }
    .suffix = Medical
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsVirology = { ent-DoorElectronics }
    .suffix = Virology
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsScience = { ent-DoorElectronics }
    .suffix = Science
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsMedicalScience = { ent-DoorElectronics }
    .suffix = Medical/Science
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsCommand = { ent-DoorElectronics }
    .suffix = Command
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsCaptain = { ent-DoorElectronics }
    .suffix = Captain
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsChiefMedicalOfficer = { ent-DoorElectronics }
    .suffix = ChiefMedicalOfficer
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsChiefEngineer = { ent-DoorElectronics }
    .suffix = ChiefEngineer
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsHeadOfSecurity = { ent-DoorElectronics }
    .suffix = HeadOfSecurity
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsResearchDirector = { ent-DoorElectronics }
    .suffix = ResearchDirector
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsHeadOfPersonnel = { ent-DoorElectronics }
    .suffix = HeadOfPersonnel
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsSecurity = { ent-DoorElectronics }
    .suffix = Security
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsSecurityCommand = { ent-DoorElectronics }
    .suffix = SecurityCommand
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsBrig = { ent-DoorElectronics }
    .suffix = Brig
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsArmory = { ent-DoorElectronics }
    .suffix = Armory
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsEVA = { ent-DoorElectronics }
    .suffix = EVA
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsMaintenance = { ent-DoorElectronics }
    .suffix = HeadOfSecurity
    .desc = { ent-DoorElectronics.desc }
ent-DoorElectronicsChemistry = { ent-DoorElectronics }
    .suffix = Chemistry
    .desc = { ent-DoorElectronics.desc }
