ent-SheetGlassBase = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-SheetGlass = стекло
ent-SheetGlass1 = стекло
ent-SheetRGlass = бронестекло
ent-SheetRGlass1 = бронестекло
ent-SheetPGlass = плазменное стекло
ent-SheetPGlass1 = плазменное стекло
ent-SheetRPGlass = плазменное бронестекло
ent-SheetRPGlass1 = плазменное бронестекло
