ent-SheetOtherBase = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-SheetPaper = бумага
ent-SheetPaper1 = бумага
ent-SheetPlasma = плазма
ent-SheetPlasma1 = плазма
ent-SheetPlastic = пластик
ent-SheetPlastic1 = пластик
ent-SheetUranium = уран
ent-SheetUranium1 = уран
