ent-MobBat = летучая мышь
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-MobBee = пчела
ent-MobAngryBee = пчела
ent-MobChicken = курица
ent-MobDuckMallard = кряква
ent-MobDuckWhite = белая утка
ent-MobDuckBrown = коричневая утка
ent-MobButterfly = бабочка
ent-MobCow = корова
ent-MobCrab = краб
ent-MobGoat = коза
ent-MobGoose = гусь
ent-MobKangaroo = кенгуру
ent-MobKangarooBoxer = кенгуру-боксёр
ent-MobGuidebookMonkey = обезьяна-путеводитель
ent-MobMouse = мышь
ent-MobMouse1 = { ent-MobMouse }
ent-MobMouse2 = { ent-MobMouse }
ent-MobLizard = ящерица
ent-MobSlug = слизняк
ent-MobFrog = лягушка
ent-MobParrot = попугай
ent-MobPenguin = пингвин
ent-MobGrenadePenguin = пингвин гренадёр
ent-MobSnake = змея
ent-MobGiantSpider = тарантул
ent-MobGiantSpiderAngry = тарантул
ent-MobPossum = поссум
ent-MobRaccoon = енот
ent-MobFox = лиса
ent-MobCorgi = корги
ent-MobCorgiNarsi = порченный корги
ent-MobCorgiPuppy = щенок корги
ent-MobCat = кошка
ent-MobCatCalico = трёхцветная кошка
ent-MobCatSpace = космическая кошка
ent-MobCatCaracal = каракаловая кошка
ent-MobSloth = ленивец
ent-MobFerret = хорёк
ent-MobHamster = хомяк
ent-MobPig = свинья
