ent-MobCorgiIan = Иан
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-MobCorgiIanOld = Старый Иан
ent-MobCorgiLisa = Лиза
ent-MobCatRuntime = Рантайм
ent-MobCatException = Исключение
ent-MobCatFloppa = Шлёпа
ent-MobBandito = Бандито
ent-MobBingus = бингус
ent-MobMcGriff = МакГрифф
ent-MobPaperwork = Пэйперворк
ent-MobWalter = Уолтер
ent-MobPossumMorty = Морти
ent-MobRaccoonMorticia = Мортиша
ent-MobAlexander = Саня
ent-MobFoxRenault = Алиса
ent-MobHamsterHamlet = Гамлет
