ent-BoxShellSoulbreaker = коробка патронов душегуба
    .desc = Коробка, полная антипсионических патронов для дробовика.
    .suffix = { "" }
ent-BoxMagazineUniversalCaselessRifle = коробка магазинов .25 безгильзовых универсальных
    .desc = Коробка, полная магазинов .25 безгильзовых.
    .suffix = { "" }
ent-BoxMagazineUniversalCaselessRifleHighVelocity = коробка магазинов .25 безгильзовых универсальных (высокоскоростные) 
    .desc = Коробка, полная магазинов .25 безгильзовых высокоскоростных.
    .suffix = { "" }
ent-BoxMagazineUniversalCaselessRiflePractice = коробка магазинов .25 безгильзовых универсальных (учебные)
    .desc = Коробка, полная магазинов .25 безгильзовых учебных.
    .suffix = { "" }
ent-BoxMagazineUniversalCaselessRifleRubber = коробка магазинов .25 безгильзовых универсальных (резина)
    .desc = Коробка, полная магазинов .25 безгильзовых резиновых.
    .suffix = { "" }
ent-BoxSpeedLoaderLightRifle = коробка спидлоадеров .30 винтовочный
    .desc = Коробка, полная спидлоадеров .30 винтовочный
    .suffix = { "" }
