guide-entry-chemistry = Химия
guide-entry-shogi = Сёги
guide-entry-chef = Шеф-повар
guide-entry-cookbook = Поваренная книга
guide-entry-burgers = Бургеры
guide-entry-cakes = Торты
guide-entry-pastries = Выпечка
guide-entry-pizzas = Пицца
guide-entry-kebabs = Шашлыки
guide-entry-sandwiches = Хлеб и бутерброды
guide-entry-snacks = Закуски
guide-entry-pasta = Макаронны и рис
guide-entry-soups = Супы
guide-entry-salads = Салаты
guide-entry-sauces = Приправы
guide-entry-cargo = Поставки
