guide-entry-reverse-engineering = Reverse Engineering
guide-entry-epistemics = Epistemics
guide-entry-psionics = Psionics
guide-entry-altars-golemancy = Altars and Golemancy
guide-entry-space-law = Space Law
guide-entry-jurisdiction = Jurisdiction
guide-entry-trial-prodedure = Trial Procedure
guide-entry-charges-and-times = Charges & Sentencing
guide-entry-chemistry = Chemistry
guide-entry-shogi = Shogi
guide-entry-chef = Chef
guide-entry-cookbook = The Cookbook
guide-entry-burgers = Burgers
guide-entry-cakes = Cakes
guide-entry-pastries = Pastry
guide-entry-pizzas = Pizza
guide-entry-kebabs = Kebabs
guide-entry-sandwiches = Bread & Sandwiches
guide-entry-snacks = Snacks
guide-entry-pasta = Pasta & Rice
guide-entry-soups = Soups
guide-entry-salads = Salads
guide-entry-sauces = Condiments
guide-entry-cargo = Cargo
