ent-BlueLightTube = синяя лампочка-трубка
    .desc = Высокоэнергетическая лампа средней мощности которая напоминает вам о космосе. Может содержать ртуть.
    .suffix = { "" }
ent-ColoredLightTubeRed = красная лампочка-трубка
    .desc = Красочная лампочка-трубка. Излучает красный свет.
    .suffix = { "" }
ent-ColoredLightTubeFrostyBlue = синяя лампочка-трубка
    .desc = Красочная лампочка-трубка. Излучает холодный синий свет.
    .suffix = { "" }
ent-ColoredLightTubeBlackLight = чёрная лампочка-трубка
    .desc = Красочная лампочка-трубка. Излучает "чёрный" цвет.
    .suffix = { "" }
ent-LightBulbMaintenance = лампа накаливания
    .desc = Тусклая лампочка.
    .suffix = Maintenance
ent-LightBulbMaintenanceRed = красная лампа накаливания
    .desc = Тусклая лампочка. Они излучают красный свет.
    .suffix = Maintenance, Red
