ent-ClothingHeadBandBlack = чёрная бандана
    .desc = Чёрная бандана, чтобы выглядеть круто.
    .suffix = { "" }
ent-ClothingHeadBandBlue = синяя бандана
    .desc = Синяя бандана, чтобы выглядеть круто.
    .suffix = { "" }
ent-ClothingHeadBandBotany = бандана ботаника
    .desc = Ботаническая бандана из натуральных волокон, чтобы выглядеть круто.
    .suffix = { "" }
ent-ClothingHeadBandGold = золотая бандана
    .desc = Золотая бандана, чтобы выглядеть круто.
    .suffix = { "" }
ent-ClothingHeadBandGreen = зелёная бандана
    .desc = Зеленая бандана, чтобы выглядеть круто.
    .suffix = { "" }
ent-ClothingHeadBandGrey = серая бандана
    .desc = Серая бандана, чтобы выглядеть круто.
    .suffix = { "" }
ent-ClothingHeadBandRed = красная бандана
    .desc = Красная бандана, чтобы выглядеть круто.
    .suffix = { "" }
ent-ClothingHeadBandSkull = бандана с черепом
    .desc = Бандана с черепом, чтобы выглядеть еще круче.
    .suffix = { "" }
ent-ClothingHeadBandBrown = коричневая бандана
    .desc = Коричневая бандана, чтобы выглядеть круто.
    .suffix = { "" }
	