ent-SpawnMobMouse = спавнер мышь
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-SpawnMobCorgi = спавнер корги
ent-SpawnMobPossumMorty = спавнер опоссум Морти
ent-SpawnMobRaccoonMorticia = спавнер енот Мортиша
ent-SpawnMobDrone = спавнер дрон
ent-SpawnMobFoxRenault = спавнер лиса Алиса
ent-SpawnMobCatRuntime = спавнер Рантайм
ent-SpawnMobCatException = спавнер Исключение
ent-SpawnMobCatFloppa = спавнер Шлёпа
ent-SpawnMobCat = спавнер кот
ent-SpawnMobCatGeneric = спавнер случайный кот
ent-SpawnMobBandito = спавнер Бандито
ent-SpawnMobMcGriff = спавнер МакГрифф
ent-SpawnMobSlothPaperwork = спавнер ленивец Пэйперворк
ent-SpawnMobWalter = спавнер Уолтер
ent-SpawnMobBear = спавнер космический медведь
ent-SpawnMobHamsterHamlet = спавнер хомяк Гамлет
ent-SpawnMobAlexander = спавнер Саня
