ent-CrateEngineeringAMEShielding = ящик компонентов ДАМ
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
ent-CrateEngineeringAMEJar = ящик антиматериевого топлива
ent-CrateEngineeringAMEControl = ящик с контроллером управления ДАМ
ent-CrateEngineeringSingularityEmitter = ящик с эмиттером
ent-CrateEngineeringSingularityCollector = ящик с коллектором радиации
ent-CrateEngineeringSingularityContainment = ящик с генератором сдерживающего поля
ent-CrateEngineeringSingularityGenerator = ящик с генератором сингулярности
ent-CrateEngineeringParticleAccelerator = ящик с ускорителем частиц
ent-CrateEngineeringGenerator = ящик с генератором
ent-CrateEngineeringSolar = ящик сборных солнечных панелей
ent-CrateEngineeringShuttle = ящик электропитания шаттла
