ent-CrateNPCBee = ящик с пчёлами
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
ent-CrateNPCButterflies = ящик с бабочками
ent-CrateNPCCat = ящик с кошкой
ent-CrateNPCChicken = ящик кур
ent-CrateNPCDuck = ящик уток
ent-CrateNPCCorgi = ящик корги
ent-CrateNPCCow = ящик с коровой
ent-CrateNPCGoat = ящик с козой
ent-CrateNPCGoose = ящик гусей
ent-CrateNPCGorilla = ящик с гориллой
ent-CrateNPCMonkeyCube = ящик обезьяньих кубиков
ent-CrateNPCMouse = ящик мышей
ent-CrateNPCParrot = ящик попугаев
ent-CrateNPCPenguin = ящик пингвинов
ent-CrateNPCPig = ящик с паросёнком
ent-CrateNPCSnake = ящик змей
