ent-CrateVendingMachineRestockBoozeFilled = ящик пополнения АлкоМат
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
ent-CrateVendingMachineRestockClothesFilled = ящик пополнения одежды
ent-CrateVendingMachineRestockDinnerwareFilled = ящик пополнения Кухонно-пластальная поварская утварь
ent-CrateVendingMachineRestockEngineeringFilled = ящик пополнения ИнжеШкаф
ent-CrateVendingMachineRestockGamesFilled = ящик пополнения Безобидные развлечения
ent-CrateVendingMachineRestockHotDrinksFilled = ящик пополнения Лучшие горячие напитки Солнечной
ent-CrateVendingMachineRestockMedicalFilled = ящик пополнения НаноМед
ent-CrateVendingMachineRestockNutriMaxFilled = ящик пополнения БотаМакс
ent-CrateVendingMachineRestockPTechFilled = ящик пополнения ПТех
ent-CrateVendingMachineRestockRobustSoftdrinksFilled = ящик пополнения Прохладительные напитки Робаст
ent-CrateVendingMachineRestockSalvageEquipmentFilled = ящик пополнения Утильмаг
ent-CrateVendingMachineRestockSecTechFilled = ящик пополнения СБТех
ent-CrateVendingMachineRestockSeedsFilled = ящик пополнения МегаРаздатчик Семян
ent-CrateVendingMachineRestockSmokesFilled = ящик пополнения ШейдиСиг Делюкс
ent-CrateVendingMachineRestockSnacksFilled = ящик пополнения закусок
ent-CrateVendingMachineRestockVendomatFilled = ящик пополнения Торгомат
ent-CrateVendingMachineRestockTankDispenserFilled = ящик пополнения газовых баллонов
ent-CrateVendingMachineRestockHappyHonkFilled = ящик пополнения Счастливый Хонк
