ent-ClothingMaskOniBase = { ent-ClothingMaskPullableBase }
    .desc = Маска с изображением свирепого существа из японского мифа.
    .suffix = { "" }
ent-ClothingMaskOniBlue = синяя маска они
    .desc = { ent-ClothingMaskOniBase.desc }
    .suffix = { "" }
ent-ClothingMaskOniRed = красная маска они
    .desc = { ent-ClothingMaskOniBase.desc }
    .suffix = { "" }
