ent-MailCarrierPDA = mail carrier PDA
ent-SalvageTechPDA = { ent-EngineerPDA }
ent-ForensicMantisPDA = forensic mantis PDA
ent-EpistemicsPDA = acolyte PDA
ent-MystaPDA = mystagogue PDA
ent-ParamedicPDA = paramedic PDA
ent-PrisonerPDA = prisoner PDA
ent-GladiatorPDA = gladiator PDA
ent-ValetPDA = valet PDA
ent-CataloguerPDA = cataloguer PDA
ent-GuardPDA = guard PDA
ent-MartialArtistPDA = martial artist PDA
