ent-ShogiBoard = доска для сёги
    .desc = Доска для игры в сёги, японские шахматы.
    .suffix = { "" }
ent-ShogiBoardTabletop = доска для сёги
    .desc = { "" }
    .suffix = { "" }
ent-BaseShogiPiece = { ent-BaseItem }
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-ShogiBishop = слон
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiGold = золотой генерал
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiKing = король
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiKingJeweled = король
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiKnight = конь
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiLance = копейщик
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiPawn = пешка
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiRook = ладья
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiSilver = серебрянный генерал
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiBishopPromoted = слон
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiKnightPromoted = конь
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiLancePromoted = копейщик
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiPawnPromoted = пешка
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiRookPromoted = ладья
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
ent-ShogiSilverPromoted = серебрянный генерал
    .desc = { ent-BaseShogiPiece.desc }
    .suffix = { "" }
