ent-BasePlushieMoff = { ent-BasePlushie }
    .desc = { ent-BasePlushie.desc }
    .suffix = { "" }
ent-PlushieMoffRandom = плюшевая моль
    .desc = Симпатичная маленькая мафф, которую можно держать в руке. У этой марки много вариантов!
    .suffix = Random
ent-PlushieMoffsician = плюшевая моль музыкант
    .desc = Плюшевая игрушка очаровательнй мофф с крошечным синтезатором и крошечными очками.
    .suffix = { "" }
ent-PlushieMoffbar = плюшевая моль бармен
    .desc = Плюшевая игрушка очаровательнй мофф с крошечным цилиндром и крошечным кевларовым жилетом. Пахнет сигаретами.
    .suffix = { "" }
