ent-WeaponTetherGun = tether gun
    .desc = Manipulates gravity around objects to fling them at high velocities.
    .suffix = { "" }
ent-WeaponForceGun = force gun
    .desc = Manipulates gravity around objects to fling them at high velocities.
    .suffix = { "" }
ent-WeaponGrapplingGun = grappling gun
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-WeaponTetherGunAdmin = tether gun
    .desc = Manipulates gravity around objects to fling them at high velocities.
    .suffix = admin
ent-WeaponForceGunAdmin = force gun
    .desc = Manipulates gravity around objects to fling them at high velocities.
    .suffix = Admin
