ent-AMEController = Контроллер ДАМ
    .desc = Это контроллер для двигателя антиматерии.
    .suffix = { "" }
ent-AMEControllerUnanchored = { ent-AMEController }
    .desc = { ent-AMEController.desc }
    .suffix = Не закреплено
ent-AMEShielding = экранирование ДАМ
    .desc = Впускает антиматерию и выпускает материю.
    .suffix = { "" }
ent-AmeController = Контроллер ДАМ
    .desc = Это контроллер для двигателя антиматерии.
    .suffix = { "" }
ent-AmeControllerUnanchored = { ent-AMEController }
    .desc = { ent-AMEController.desc }
    .suffix = Не закреплено
ent-AmeShielding = экранирование ДАМ
    .desc = Впускает антиматерию и выпускает материю.
    .suffix = { "" }
