ent-LockerQuarterMasterFilled = { ent-LockerQuarterMaster }
.suffix = { "" }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
ent-LockerCaptainFilled = { ent-LockerCaptain }
ent-LockerHeadOfPersonnelFilled = { ent-LockerHeadOfPersonnel }
ent-LockerChiefEngineerFilled = { ent-LockerChiefEngineer }
ent-LockerChiefMedicalOfficerFilled = { ent-LockerChiefMedicalOfficer }
ent-LockerResearchDirectorFilled = { ent-LockerResearchDirector }
ent-LockerHeadOfSecurityFilled = { ent-LockerHeadOfSecurity }
