marking-PawSocks-pawsocks = Носки с лапками
marking-PawSocks = Носки с лапками
marking-FoxTail-vulp_tail = Лисий хвостик
marking-FoxTail = Лисий хвостик
marking-FoxEar-vulp_ear = Лисьи ушки (внешний)
marking-FoxEar-vulp_ear_inner = Лисьи ушки (внутренний)
marking-FoxEar = Лисьи ушки (внутренний)
marking-WolfTail-wolf_tail = Волчий хвостик (стандартный)
marking-WolfTail-wolf_tail_inner = Волчий хвостик (кончик)
marking-WolfTail = Волчий хвостик (кончик)
marking-FoxBelly-vulp_belly-torso = Лисий животик
marking-FoxBelly = Лисий животик
marking-FoxSnout-vulp_face = Лисья мордочка
marking-FoxSnout = Лисья мордочка
marking-VulpEar-vulp = Уши вульпикана (основание)
marking-VulpEar-vulp-inner = Уши вульпикана (внутренние) 
marking-VulpEar = Уши вульпикана 
marking-VulpEarFade-vulp = Уши вульпикана (основание) 
marking-VulpEarFade-vulp-fade = Уши вульпикана (внутренние (тусклые)) 
marking-VulpEarFade = Уши вульпикана (тусклые)
marking-VulpEarSharp-vulp = Уши вульпикана (острые)
marking-VulpEarSharp-vulp-sharp = Уши вульпикана (острые) 
marking-VulpEarSharp = Уши вульпикана (острые)
marking-VulpEarJackal-jackal = Шакальи уши 
marking-VulpEarJackal-jackal-inner = Шакальи уши (острые (внутренние))
marking-VulpEarJackal = Шакальи уши вульпикана 
marking-VulpEarTerrier-terrier = Уши терьера
marking-VulpEarTerrier-terrier-inner = Уши терьера (внутренние)
marking-VulpEarTerrier = Уши вульпикана-терьера 
marking-VulpEarWolf-wolf = Уши волка
marking-VulpEarWolf-wolf-inner = Уши волка (внутренние)
marking-VulpEarWolf = Уши волка-вульпикана
marking-VulpEarFennec-fennec = Уши финька (основание) 
marking-VulpEarFennec-fennec-inner = Уши финька (внутренние) 
marking-VulpEarFennec = Уши финька-вульпикана 
marking-VulpEarFox-fox = Лисьи уши 
marking-VulpEarFox = Уши вульпикана-лисы 
marking-VulpEarOtie-otie = Уши сурка (основание)
marking-VulpEarOtie-otie-inner = Уши сурка (внутренние)
marking-VulpEarOtie = Уши сурка-вульпикана
marking-VulpEarTajaran-msai = Уши таяра (основание)
marking-VulpEarTajaran-msai-inner = Уши таяра (внутренние)
marking-VulpEarTajaran = Уши таяра-вульпикана
marking-VulpEarShock-shock = Уши шоке
marking-VulpEarShock = Уши вульпикан-шоке
marking-VulpEarCoyote-coyote = Уши кайота
marking-VulpEarCoyote = Уши вульпикан-кайота 
marking-VulpEarDalmatian-dalmatian = Уши далматинца
marking-VulpEarDalmatian = Уши вульпикан-долматинца 
marking-VulpSnoutAlt-muzzle_alt = Морда вульпикана (альтернативный) 
marking-VulpSnoutAlt-nose = Нос вульпикана (альтернативный) 
marking-VulpSnoutAlt = Морда вульпикана 2 (альтернативный)
marking-VulpSnout-muzzle = Морда вульпикана 
marking-VulpSnout-nose = Нос вульпикана 
marking-VulpSnout = Морда вульпикана 2 
marking-VulpSnoutSharp-muzzle_sharp = Морда вульпикана (острый) 
marking-VulpSnoutSharp-nose = Нос вульпикана (острый) 
marking-VulpSnoutSharp = Морда вульпикана (острый)
marking-VulpSnoutFade-muzzle_fade = Морда вульпикана (исчезающий) 
marking-VulpSnoutFade-nose = Нос вульпикана (исчезающий) 
marking-VulpSnoutFade = Морда вульпикана (исчезающий)
marking-VulpSnoutNose-nose = Нос вульпикана (исчезающий) 
marking-VulpSnoutNose = Нос вульпикана (исчезающий) 
marking-VulpSnoutMask-mask = Маска вульпикана 
marking-VulpSnoutMask-nose = Носовая маска вульпикана 
marking-VulpSnoutMask = Маска вульпикана 
marking-VulpSnoutVulpine-vulpine = Хищная морда вульпикана (основание)
marking-VulpSnoutVulpine-vulpine-lines = Хищная морда вульпикана (линейная)
marking-VulpSnoutVulpine = Хищная морда мульпикана 
marking-VulpSnoutSwift-vulpine-lines = Морда быстрого вульпикана (линейная) 
marking-VulpSnoutSwift = Морда быстрого вульпикана (линейная)
marking-VulpSnoutBlaze-blaze = Блестящая морда вульпикана 
marking-VulpSnoutBlaze = Блестящая морда вульпикана 
marking-VulpSnoutPatch-patch = Пятнистая морда вульпикана 
marking-VulpSnoutPatch = Пятнистая морда вульпикана 
marking-VulpHeadTiger-tiger_head = Голова тигра 
marking-VulpHeadTiger = Голова тигра
marking-VulpHeadTigerFace-tiger_face = Лицо тигра
marking-VulpHeadTigerFace = Лицо тигра
marking-VulpHeadSlash-slash = Косое лицо вульпикана 
marking-VulpHeadSlash = Косое лицо вульпикана
marking-VulpTail-vulp = Хвост вульпикана (основание) 
marking-VulpTail-vulp-fade = Хвост вульпикана (исчезающий)
marking-VulpTail = Хвост вульпикана 
marking-VulpTailTip-vulp = Хвост вульпикана (основание)
marking-VulpTailTip-vulp-tip = Хвост вульпикана (конец)
marking-VulpTailTip = Хвост вульпикана (конец)
marking-VulpTailWag-vulp_wag = Хвост вульпикана (динамический(основание))
marking-VulpTailWag-vulp_wag-fade = Хвост вульпикана (динамический(исчезающий))
marking-VulpTailWag = Хвост вульпикана (динамический)
marking-VulpTailWagTip-vulp_wag = Хвост вульпикана (динамический(основание))
marking-VulpTailWagTip-vulp_wag-tip = Хвост вульпикана (динамический(конец)) 
marking-VulpTailWagTip = Хвост вульпикана (динамический,конец)
marking-VulpTailAlt-vulp_alt = Хвост вульпикана (динамический, альтернативный, основание)
marking-VulpTailAlt-vulp_alt-fade = Хвост вульпикана (динамический, альтернативный, исчезающий)
marking-VulpTailAlt = Хвост вульпикана (динамический, альтернативный)
marking-VulpTailAltTip-vulp_alt = Хвост вульпикана (альтернативный, основание)
marking-VulpTailAltTip-vulp_alt-tip = Хвост вульпикана (дальтернативный, конец)
marking-VulpTailAltTip = Хвост вульпикана (альтернативный, конец) 
marking-VulpTailLong-long = Длинный хвост (основание)
marking-VulpTailLong-long-tip = Длинный хвост (конец)
marking-VulpTailLong = Длинный хвост вульпикана
marking-VulpTailFox-fox = Лисий хвост (основание) 
marking-VulpTailFox-fox-fade = Лисий хвост (исчезающий)
marking-VulpTailFox = Лисий хвост вульпикана
marking-VulpTailFoxTip-fox = Лисий хвост (основание)
marking-VulpTailFoxTip-fox-tip = Лисий хвост (конец, исчезающий)
marking-VulpTailFoxTip = Лисий хвост (конец)
marking-VulpTailFoxWag-fox_wag = Лисий хвост (динамический)
marking-VulpTailFoxWag-fox_wag-fade = Лисий хвост (динамический, исчезающий)
marking-VulpTailFoxWag = Лисий хвост вульпикана
marking-VulpTailFoxWagTip-fox_wag = Лисий хвост (основание, динамический)
marking-VulpTailFoxWagTip-fox_wag-tip = Лисий хвост (конец, динамический)
marking-VulpTailFoxWagTip = Лисий хвост вульпикана (динамический, конец) 
marking-VulpTailBushy-bushfluff = Кустарный хвост
marking-VulpTailBushy = Кустарный хвост вульпикана
marking-VulpTailBushyWag-bushfluff_wag = Кустарный хвост вульпикана (динамический)
marking-VulpTailBushyWag = Кустарный хвост вульпикана (динамический)
marking-VulpTailCoyote-coyote = Хвост кайота 
marking-VulpTailCoyote = Хвост кайота-вульпикана 
marking-VulpTailCoyoteWag-coyote_wag = Хвост кайота-вульпикана (динамический) 
marking-VulpTailCoyoteWag = Хвост кайота-вульпикана (динамический) 
marking-VulpTailCorgiWag-corgi_wag = Хвост корги 
marking-VulpTailCorgiWag = Хвост вульпикана-корги (динамический)
marking-VulpTailHusky-husky-inner = Хвост хаски (внутренний)
marking-VulpTailHusky-husky-outer = Хвост хаски (внешний)
marking-VulpTailHusky = Хвост вульпикана-хаски
marking-VulpTailHuskyAlt-husky = Хвост хаски (альтернативный)
marking-VulpTailHuskyAlt = Хвост хаски (альтернативный) 
marking-VulpTailFox2-fox2 = Лисий хвост 2
marking-VulpTailFox2 = Лисий хвост вульпикана 2
marking-VulpTailFox3-fox3 = Лисий хвост 3 (основание) 
marking-VulpTailFox3-fox3-tip = Лисий хвост 3 (конец)
marking-VulpTailFox3 = Vulpkanin Лисий хвост вульпикана 3 
marking-VulpTailFennec-fennec = Хвост финника
marking-VulpTailFennec = Хвост финника вульпикана 
marking-VulpTailOtie-otie = Хвост отти
marking-VulpTailOtie = Хвост отти вульпикана
marking-VulpTailFluffy-fluffy = Пушистый хвост
marking-VulpTailFluffy = Пушистый хвост вульпикана 
marking-VulpTailDalmatianWag-dalmatian_wag = Хвост далматинца
marking-VulpTailDalmatianWag = Хвост далматинца (динамический)
marking-VulpBellyCrest-belly_crest = Живот 
marking-VulpBellyCrest = Vulpkanin Живот вульпикана 
marking-VulpBellyFull-belly_full = Полный живот
marking-VulpBellyFull = Vulpkanin Полный живот вульпикана
marking-VulpBellyFox-belly_fox = Живот лисы 
marking-VulpBellyFox = Живот вульпикано-лисы
marking-VulpBodyPointsCrest-points_crest = Точки (холка) 
marking-VulpBodyPointsCrest = Точки вульпикана (холка) 
marking-VulpBodyPointsFade-points_fade = Точки вульпикана (исчезающие)
marking-VulpBodyPointsFade = Точки вульпикана (исчезающие)
marking-VulpBodyPointsSharp-points_sharp = Точки вульпикана (острые) 
marking-VulpBodyPointsSharp = Точки вульпикана (острые) 
marking-VulpPointsFeet-points_feet = Точки ног
marking-VulpPointsFeet = Вульпиканские точки ног
marking-VulpPointsCrestLegs-points_crest-legs = Точки (холка)
marking-VulpPointsCrestLegs = Вульпиканские точки ног (холка)
marking-VulpPointsFadeLegs-points_fade-legs = Точки (исчезающие)
marking-VulpPointsFadeLegs = Вульпиканские точки ног (исчезающие)
marking-VulpPointsSharpLegs-points_sharp-legs = Точки (Острые)
marking-VulpPointsSharpLegs = Вульпиканские точки ног (острые)
marking-VulpPointsHands-points_hands = Точки рук
marking-VulpPointsHands = Вульпиканские точки рук
marking-VulpPointsCrestArms-points_crest-arms = Точки (холка)
marking-VulpPointsCrestArms = Вульпиканские точки рук (холка)
marking-VulpPointsFadeArms-points_fade-arms = Точки (исчезающие)
marking-VulpPointsFadeArms = Вульпиканские точки рук (исчезающие)
marking-VulpPointsSharpArms-points_sharp-arms = Точки (острые)
marking-VulpPointsSharpArms = Вульпиканские точки рук (острые)
marking-VulpHairAdhara = Адхара 
marking-VulpHairAnita = Анита 
marking-VulpHairApollo = Аполло 
marking-VulpHairBelle = Белли 
marking-VulpHairBraided = Заплетенные в косу волосы 
marking-VulpHairBun = Бун 
marking-VulpHairCleanCut = Чистый срез 
marking-VulpHairCurl = Локоны 
marking-VulpHairHawk = Ястреб 
marking-VulpHairJagged = Зазубренный 
marking-VulpHairJeremy = Джереми 
marking-VulpHairKajam = Каджам 
marking-VulpHairKeid = Каид 
marking-VulpHairKleeia = Клея 
marking-VulpHairMizar = Мизар 
marking-VulpHairPunkBraided = Реальный панк 
marking-VulpHairRaine = Рейн
marking-VulpHairRough = Роуг 
marking-VulpHairShort = Короткие волосы 
marking-VulpHairShort2 = Короткие волосы 2 
marking-VulpHairSpike = Спайк 
marking-VulpFacialHairRuff = Рафф 
marking-VulpFacialHairElder = Древний 
marking-VulpFacialHairElderChin = Древний Чин 
marking-VulpFacialHairKita = Каита 
