ent-BaseChemistryEmptyBottle = бутылочка
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ChemistryEmptyBottle01 = бутылочка
ent-ChemistryEmptyBottle02 = бутылочка
ent-ChemistryEmptyBottle03 = бутылочка
ent-ChemistryEmptyBottle04 = бутылочка
ent-EpinephrineChemistryBottle = бутылочка эпинефрина
ent-RobustHarvestChemistryBottle = бутылочка robust harvest
ent-UnstableMutagenChemistryBottle = бутылочка нестабильного мутагена
ent-NocturineChemistryBottle = бутылочка ноктюрина
ent-EphedrineChemistryBottle = бутылочка эфедрина
ent-OmnizineChemistryBottle = бутылочка омнизина
