ent-BaseBeaker = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-Beaker = мензурка
ent-LargeBeaker = большая мензурка
ent-CryostasisBeaker = криостазисная мензурка
ent-BluespaceBeaker = блюспейс мензурка
ent-Dropper = пипетка
ent-BaseSyringe = шприц
ent-Syringe = { ent-BaseSyringe }
ent-Pill = таблетка
ent-PillCanister = баночка для таблеток
