ent-Telecrystal = телекристалл
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-Telecrystal1 = { ent-Telecrystal }
ent-Telecrystal5 = { ent-Telecrystal }
ent-Telecrystal10 = { ent-Telecrystal }
ent-BaseUplinkRadio = аплинк синдиката
ent-BaseUplinkRadio20TC = { ent-BaseUplinkRadio }
ent-BaseUplinkRadio25TC = { ent-BaseUplinkRadio }
ent-BaseUplinkRadioDebug = { ent-BaseUplinkRadio }
