ent-SalvagePartsT2Spawner = спавнер частей машин 2 уровня на обломке
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SalvagePartsT3T4Spawner = спавнер детали 3/4 уровня
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SalvagePartsT3Spawner = спавнер частей машин 3/4 уровня на обломке
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SalvagePartsT4Spawner = спавнер детали 4 уровня
    .suffix = { "" }
    .desc = { ent-MarkerBase.desc }
