reagent-name-soju = соджу
reagent-desc-soju = Алкогольный напиток, приготовленный путем перегонки полированного риса.
reagent-name-orange-creamcicle = апельсиновый крем
reagent-desc-orange-creamcicle = Оранжевое, сливочное совершенство.
reagent-name-silverjack = Сильверджек
reagent-desc-silverjack = Напоминает вам о семье.
reagent-name-brainbomb = мозговая бомба
reagent-desc-brainbomb = Токсично для всего живого, особенно для вашей печени.
reagent-name-clownblood = кровь клоуна
reagent-desc-clownblood = Любимый напиток сотрудников службы безопасности после долгого дня.
reagent-name-circusjuice = цирковой сок
reagent-desc-circusjuice = Хонкмать будет рада.
reagent-name-sapopicante = Сапо Пиканте
reagent-desc-sapopicante = Вкус никак не похож на жабу.
reagent-name-graveyard = кладбище
reagent-desc-graveyard = Для тех смен, которые никогда не заканчиваются.
reagent-name-gunmetal = бронза
reagent-desc-gunmetal = Спорный напиток, созданный печально известным Solus Cream, первым барменом, который подал сварочное топливо, не потеряв лицензию на продажу спиртных напитков.
reagent-name-lemondrop = лимонный леденец
reagent-desc-lemondrop = Простой, острый и вкусный напиток, состоящий из лимона, водки и сахарного сиропа. Освежающий!
reagent-name-greengrass = зеленая трава
reagent-desc-greengrass = Зеленая трава, или grüne wiese, — своеобразный зеленый коктейль родом из ныне распавшейся ГДР. Популярен как среди разочарованных, так и простодушных.
reagent-name-daiquiri = классический дайкири
reagent-desc-daiquiri = Сладкая смесь рома и лайма, любимая писателями и политиками.
reagent-name-arsonistsbrew = отвар поджигателя
reagent-desc-arsonistsbrew = Сделайте глоток и смейтесь, пока вы смотрите, как горит ваш мир.
reagent-name-dulleavene = унылость
reagent-desc-dulleavene = Якобы это коктейль. Мотив предупреждающего конуса кажется уместным.
