ent-BoxMagazineUniversalCaselessRifle = box of .25 caseless Universal magazines
    .desc = A box full of .25 caseless magazines.
    .suffix = { "" }
ent-BoxMagazineUniversalCaselessRifleHighVelocity = box of .25 caseless Universal (high-velocity) magazines
    .desc = A box full of .25 caseless high-velocity magazines.
    .suffix = { "" }
ent-BoxMagazineUniversalCaselessRiflePractice = box of .25 caseless Universal (practice) magazines
    .desc = A box full of .25 caseless practice magazines.
    .suffix = { "" }
ent-BoxMagazineUniversalCaselessRifleRubber = box of .25 caseless Universal (rubber) magazines
    .desc = A box full of .25 caseless rubber magazines.
    .suffix = { "" }
ent-BoxSpeedLoaderLightRifle = box of .30 rifle speed loaders
    .desc = A box full of .30 rifle speed loaders.
    .suffix = { "" }
