ent-ClothingUniformJumpsuitSuitBlack = чёрный костюм
    .desc = Накрахмаленная белая рубашка и темно-серые брюки. Напоминает о былых временах.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitBlackAlt = тёмный костюм
    .desc = Накрахмаленная серая рубашка и темно-серые брюки. Напоминает о пасмурных днях.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitBlackMob = одежда бандита
    .desc = Накрахмаленная красная рубашка и темно-серые брюки. Напоминает о ваших долгах.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitBrown = коричневый костюм
    .desc = Накрахмаленная белая рубашка и шоколадные брюки. Напоминает пыльные офисы.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitBrownAlt = подозрительный костюм
    .desc = Накрахмаленная серая рубашка и шоколадные брюки. Напоминает скрытых оперативников.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitBrownMob = наряд гангстера
    .desc = Накрахмаленная красная рубашка и шоколадные брюки. Напоминает о поездках.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitWhite = белый костюм
    .desc = Накрахмаленная белая рубашка и брюки цвета слоновой кости. Напоминает лебедей.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitWhiteAlt = костюм в негативе
    .desc = Накрахмаленная серая рубашка и брюки цвета слоновой кости. Напоминает дагерротипы.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitWhiteMob = наряд мафиози
    .desc = Накрахмаленная красная рубашка и брюки цвета слоновой кости. Напоминает о семье.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSecFormal = формальный костюм сб
    .desc = Костюм для особых случаев.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSober = трезвый свитер
    .desc = Для более светлых моментов.
    .suffix = { "" }
