ent-ClothingUniformJumpsuitSuitBlack = black suit
    .desc = A crisp white shirt and charcoal slacks. Reminds you of the old times.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitBlackAlt = dark suit
    .desc = A crisp grey shirt and charcoal slacks. Reminds you of overcast days.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitBlackMob = mobster's attire
    .desc = A crisp red shirt and charcoal slacks. Reminds you of your debts.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitBrown = brown suit
    .desc = A crisp white shirt and chocolate slacks. Reminds you of dusty offices.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitBrownAlt = suspicious suit
    .desc = A crisp grey shirt and chocolate slacks. Reminds you of clandestine operators.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitBrownMob = gangster's attire
    .desc = A crisp red shirt and chocolate slacks. Reminds you of drivebys.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitWhite = white suit
    .desc = A crisp white shirt and ivory slacks. Reminds you of swans.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitWhiteAlt = negative suit
    .desc = A crisp grey shirt and ivory slacks. Reminds you of daguerreotypes.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSuitWhiteMob = mafioso's attire
    .desc = A crisp red shirt and ivory slacks. Reminds you of family.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSecFormal = security formal suit
    .desc = A suit for special occasions.
    .suffix = { "" }
ent-ClothingUniformJumpsuitSober = sober sweater
    .desc = For the more lucid moments.
    .suffix = { "" }
