ent-ClothingHeadsetEpistemics = epistemics headset
    .desc = Faithfully recreates the true essence of remote sound waves.
    .suffix = { "" }
ent-ClothingHeadsetMystagogue = mystagogue headset
    .desc = Still useful to someone with psychic powers.
    .suffix = { "" }
ent-ClothingHeadsetAltMystagogue = epistemics over-ear headset
    .desc = { ent-ClothingHeadsetAlt.desc }
    .suffix = { "" }
ent-ClothingHeadsetMantis = mantis headset
    .desc = { ent-ClothingHeadsetAlt.desc }
    .suffix = { "" }
