ent-ClothingOuterCoatBomber = куртка-бомбер
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingOuterCoatDetective = тренч детектива
ent-ClothingOuterCoatGentle = аккуратное пальто
ent-ClothingOuterCoatHoSTrench = тренч главы службы безопасности
ent-ClothingOuterCoatInspector = пальто инспектора
ent-ClothingOuterCoatJensen = пальто Дженсена
ent-ClothingOuterCoatLab = лабораторный халат
ent-ClothingOuterCoatLabChem = лабораторный халат (химия)
ent-ClothingOuterCoatLabViro = лабораторный халат (вирусология)
ent-ClothingOuterCoatLabCmo = лабораторный халат главного врача
ent-ClothingOuterCoatPirate = одежда пирата
ent-ClothingOuterCoatWarden = бронированная куртка смотрителя
ent-ClothingOuterDameDane = якудза пальто
ent-ClothingOuterClownPriest = мантия хонкоматери
ent-ClothingOuterCoatParamedicWB = ветровка парамедика
