ent-MachineParticleAcceleratorEmitterStarboardCircuitboard = правый эмиттер УЧ (машинная плата)
    .desc = Машинная плата для правого эмиттера ускорителя частиц
    .suffix = { "" }
ent-MachineParticleAcceleratorEmitterForeCircuitboard = центральный эмиттер УЧ (машинная плата)
    .desc = Машинная плата для центрального эмиттера ускорителя частиц
    .suffix = { "" }
ent-MachineParticleAcceleratorEmitterPortCircuitboard = левый эмиттер УЧ (машинная плата)
    .desc = Машинная плата для левого эмиттера ускорителя частиц
    .suffix = { "" }
