ent-PoweredlightColoredRed = { ent-Poweredlight }
    .desc = Источник света. Потребляет энергию и производит свет с помощью лампочки-трубки.
    .suffix = Красный
ent-PoweredlightColoredFrostyBlue = { ent-Poweredlight }
    .desc = Источник света. Потребляет энергию и производит свет с помощью лампочки-трубки.
    .suffix = Морозный
ent-PoweredlightColoredBlack = { ent-Poweredlight }
    .desc = Источник света. Потребляет энергию и производит свет с помощью лампочки-трубки.
    .suffix = Черный
ent-PoweredLightPostSmallRed = почтовый фонарь
    .desc = Источник света. Потребляет энергию и производит свет с помощью лампочки-трубки.
    .suffix = Красный
