ent-FoodPizzaCorncob = corncob crust pizza
ent-FoodPizzaCorncobSlice = slice of corncob crust pizza
ent-FoodMothPizzaFirecracker = firecracker pizza
ent-FoodMothPizzaFirecrackerSlice = slice of firecracker pizza
ent-FoodMothPizzaFiveCheese = quattro formaggi pizza
ent-FoodMothPizzaFiveCheeseSlice = slice of quattro formaggi pizza
ent-FoodMothPizzaPesto = pesto pizza
ent-FoodMothPizzaPestoSlice = slice of pesto pizza
ent-FoodMothPizzaCotton = cotton pizza
ent-FoodMothPizzaCottonSlice = slice of cotton pizza
