job-name-mystagogue = мистагог
job-name-mantis = детектив
job-name-epistemologist = аколит
job-name-mail-carrier = почтальон
job-name-cataloguer = каталогизатор
job-name-cyborg = киборг
job-name-medical-cyborg = медицинский киборг
job-name-salvage-technician = утилизатор
job-name-gladiator = гладиатор
job-name-fugitive = беглец
job-name-prisoner = заключенный
job-name-valet = сервисный работник
job-name-paramedic = парамедик
job-name-guard = охранник тюрьмы
# Role timers - Make these alphabetical or I cut you
JobCataloguer = каталогизатор
JobCyborg = киборг
JobEpistemologist = аколит
JobForensicMantis = детектив
JobMailCarrier = почтальон
JobMystagogue = мистагог
JobPrisoner = заключенный
JobSalvageTechnician = утилизатор
JobValet = сервисный работник
