ent-FoodBreadCorn = cornbread
    .desc = Some good down-home country-style, rootin'-tootin', revolver-shootin', dad-gum yeehaw cornbread.
    .suffix = { "" }
ent-FoodBreadCornSlice = cornbread slice
    .desc = A slice of cornbread.
    .suffix = { "" }
ent-FoodBreadSausage = sausage bread
    .desc = Dont think too much about it.
    .suffix = { "" }
ent-FoodBreadSausageSlice = sausage bread slice
    .desc = Dont think too much about it.
    .suffix = { "" }
ent-FoodBreadFrenchToast = f toast
    .desc = A slice of bread soaked in a beaten egg mixture.
    .suffix = { "" }
ent-FoodBreadJellySlice = jelly toast
    .desc = As if science are gonna give up their slimes for toast!
    .suffix = { "" }
ent-FoodBreadTwoSlice = two slice
    .desc = Classy.
    .suffix = { "" }
