ent-BaseWeaponCrusher = дробитель
    .desc = Ранний дизайн протокинетического ускорителя.
    .suffix = { "" }
ent-WeaponCrusher = дробитель
    .desc = { ent-BaseWeaponCrusher.desc }
    .suffix = { "" }
ent-WeaponCrusherDagger = кинжал-дробитель
    .desc = Уменьшенная версия протокинетического дробителя, обычно используется в крайнем случае.
    .suffix = { "" }
ent-WeaponCrusherGlaive = глефа-дробитель
    .desc = Ранний дизайн протокинетического ускорителя, в форме глефы.
    .suffix = { "" }
