ent-CrateGenericSteel = стальной ящик
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-CratePlastic = пластиковый ящик
ent-CrateFreezer = холодильник
ent-CrateHydroponics = гидропонный ящик
ent-CrateMedical = медицинский ящик
ent-CrateRadiation = ящик противорадиационного снаряжения
ent-CrateInternals = ящик аварийного кислородного снаряжения
ent-CrateElectrical = электротехнический ящик
ent-CrateEngineering = инженерный ящик
ent-CrateScience = научный ящик
ent-CrateSurgery = хирургический ящик
ent-CrateSecgear = ящик оборудования службы безопасности
ent-CrateEngineeringSecure = защищённый инженерный ящик
ent-CrateMedicalSecure = защищённый медицинский ящик
ent-CratePrivateSecure = специальный ящик
ent-CrateScienceSecure = защищённый научный ящик
ent-CratePlasma = плазменный ящик
ent-CrateSecure = защищённый ящик
ent-CrateHydroSecure = защищённый гидропонный ящик
ent-CrateWeaponSecure = защищённый оружейный ящик
ent-CrateCommandSecure = командный ящик
ent-CrateLivestock = ящик для скота
ent-CrateRodentCage = клетка для хомяка
