ent-MobTomatoKiller = помидор убийца
    .desc = Это действительно позволит вам привлечь веганов к следующим онлайн-дебатам.
    .suffix = { "" }
ent-MobGiantSpiderVampire = онейрофаг
    .desc = По слухам, паук 'пожиратель снов' является одним из потенциальных генетических источников арахны.
    .suffix = { "" }
ent-MobGiantSpiderVampireAngry = онейрофаг
    .suffix = Злой
    .desc = { ent-MobGiantSpiderVampire.desc }
ent-MobMouseCancer = Раковая Мышь
    .desc = Ой, привет, гражданский...
    .suffix = { "" }
