ent-SpawnPointGhostRatKing = спавнер роли призрак
    .suffix = крысиный король
    .desc = { ent-MarkerBase.desc }
ent-SpawnPointGhostRemilia = спавнер роли призрак
    .suffix = Ремилия
    .desc = { ent-MarkerBase.desc }
ent-SpawnPointGhostCerberus = спавнер роли призрак
    .suffix = Цербер
    .desc = { ent-MarkerBase.desc }
ent-SpawnPointGhostNukeOperative = спавнер роли призрак
    .suffix = Ядерный Оперативник
    .desc = { ent-MarkerBase.desc }
