ent-UniformJabroni = jabroni outfit
    .desc = For artists, perfomance artists.
    .suffix = { "" }
ent-UniformSchoolgirlRed = красная школьная форма
    .desc = Готовься к школе!
    .suffix = { "" }
ent-UniformSchoolgirlBlack = чёрная школьная форма
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlBlue = синяя школьная форма
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlCyan = голубая школьная форма
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlGreen = зеленая школьная форма
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlOrange = ораньжевая школьная форма
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlPink = розовая школьная форма
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlPurple = фиолетовая школьная форма
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformMaid = униформа горничной
    .desc = Аутентичная, из космической франции!
    .suffix = { "" }
ent-UniformGeisha = платье гейши
    .desc = Для хорошей хозяйки.
    .suffix = { "" }
ent-ClothingUniformJumpskirtNurse = юбка медсестры
    .desc = Многие захотят под нее заглянуть.
    .suffix = { "" }
ent-ClothingUniformKendoHakama = хакама
    .desc = Элегантная черно-синяя хакама, которую можно носить для кендо или официальных мероприятий.
    .suffix = { "" }
ent-ClothingUniformMartialGi = ги
    .desc = Белый верх и низ, традиционно используемые в боевых искусствах, часто сочетаются с поясом.
    .suffix = { "" }
ent-ClothingKimonoBlue = синее кимоно
    .desc = Я синий да ба ди да ба да-и!
    .suffix = { "" }
ent-ClothingKimonoPink = розовое кимоно
    .desc = Красотка в розовом, не так ли?
    .suffix = { "" }
ent-ClothingKimonoPurple = фиолетовое кимоно
    .desc = В этом ты точно не будешь выглядеть темно-бордовой.
    .suffix = { "" }
ent-ClothingKimonoSky = кимоно небесно-голубого цвета
    .desc = Напоминает Нацу Мацури.
    .suffix = { "" }
ent-ClothingCostumeArcDress = белая рубашка и фиолетовая юбка
    .desc = Вы чувствуете сверхъестественное желание надеть их. Должно быть, это судьба.
    .suffix = { "" }
