ent-BaseShellShotgun = ружейный патрон (.50)
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ShellShotgunBeanbag = ружейный патрон (.50 травматический)
ent-ShellShotgunSlug = ружейный патрон (.50 пуля)
ent-ShellShotgunFlare = ружейный патрон (.50 фальшфейер)
ent-ShellShotgun = ружейный патрон (.50 дробь)
ent-ShellShotgunIncendiary = ружейный патрон (.50 зажигательный)
ent-ShellShotgunPractice = ружейный патрон (.50 учебный)
ent-ShellTranquilizer = ружейный патрон (.50 транквилизатор)
