ent-GrenadeBase = { ent-BaseItem }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ExGrenade = разрывная граната
ent-GrenadeFlashBang = светошумовая граната
ent-SyndieMiniBomb = минибомба синдиката
ent-NuclearGrenade = критическая масса
ent-ModularGrenade = модульная граната
ent-EmpGrenade = эми-граната
