ent-BookSalvageEpistemics = epistemics book
    .desc = A metallic hardcover book.
    .suffix = { "" }
ent-BookSalvageEpistemicsRandom = epistemics book
    .desc = { ent-BookSalvageEpistemics.desc }
    .suffix = { "" }
ent-BookSalvageEpistemics1 = { ent-BookSalvageEpistemics }
    .suffix = 1
    .desc = { ent-BookSalvageEpistemics.desc }
