cage-resist-second-person = Вы начинаете снимать { $cage }.
cage-resist-third-person = { CAPITALIZE(THE($user)) } начинает снимать { POSS-ADJ($user) } { $cage }.
cage-uncage-verb = Освободить из клетки
action-name-metapsionic = Метапсионический импульс
action-description-metapsionic = Создать псионический импульс для выявления псиоников поблизости.
metapsionic-pulse-success = Вы обнаруживаете рядом псионическое присутствие.
metapsionic-pulse-failure = Вы не обнаруживаете рядом псионическое присутствие .
metapsionic-pulse-power = Вы обнаружаете что { $power } было использовано рядом.
action-name-dispel = Развеять
action-description-dispel = Развеять призванную сущность или невидимую стену.
action-name-mass-sleep = Сон
action-description-mass-sleep = Заставляет цель и окружающих рядом с ней заснуть.
accept-psionics-window-title = Псионик!
accept-psionics-window-prompt-text-part =
    Вы чувствуете пробуждение силы!
    Возможно что вы станете целью анти-псионических сил,
    так что, возможно, стоит держать это в секрете.
    Хотите ли вы укротить данную силу?
action-name-psionic-invisibility = Псионическая невидимость
action-description-psionic-invisibility = Сделайте себя невидимым для любых возможных псиоников. Борги, животные, и другие не подвержены данной способности.
action-name-psionic-invisibility = Псионическая невидимость
action-description-psionic-invisibility = Сделайте себя невидимым для любых возможных псиоников. Борги, животные, и другие не подвержены данной способности.
action-name-psionic-invisibility-off = Выключить псионическую невидимость
action-description-psionic-invisibility-off = Делает вас снова видимым и оглушает.
action-name-mind-swap = Обмен телами
action-description-mind-swap = Обменяться телами с целью. Можно вернуться обратно после 20 секунд.
action-name-mind-swap-return = Вернуть тела
action-description-mind-swap-return = Вернуться в свое тело.
action-name-telegnosis = Пси-взгляд
action-description-telegnosis = Создает пси-проекцию через которую вы можете наблюдать за пространством.
action-name-psionic-regeneration = Пси-лечение
action-description-psionic-regeneration = Доведите до предела свой метаболизм, чтобы увеличить ваши регинерационные способности.
glimmer-report = Нынешний уровень Глиммера: { $level }Ψ.
glimmer-event-report-generic = Обнаружен выброс в Ноосфере. Уровень Глиммера понижен с { $decrease } до { $level }Ψ.
glimmer-event-report-signatures = Обнаружены новые псионические силы. Уровень Глиммера понижен с { $decrease } до { $level }Ψ.
glimmer-event-awakened-prefix = { $entity } пробудился
noospheric-zap-seize = Вы захвачены!
noospheric-zap-seize-potential-regained = Вы захвачены! Ваши ментыльные блоки рассеялись.
mindswap-trapped = Похоже вы заперты в данной оболочке.
telegnostic-trapped-entity-name = пси-проекция.
telegnostic-trapped-entity-desc = Во множестве глаз данной сущности виднеется глубокая грусть.
psionic-burns-up = { CAPITALIZE(THE($item)) } горит со странными энергетическими вспышками!
psionic-burn-resist = Вокруг тонцуют странные искры { THE($item) }!
action-name-noospheric-zap = Ноосферический разряд
action-description-noospheric-zap = Шокирует сознание цели оглушая её.
action-name-pyrokinesis = Пирокинетика
action-description-pyrokinesis = Зажигает цель.
pyrokinesis-power-used = Огненный шар попадает в { THE($target) }, поджигая { OBJECT($target) }!
action-name-rf-sensitivity = Радиочувствительность
action-desc-rf-sensitivity = Возможность чувствовать и слышать радиоволны.
