ent-SpawnMobMonkeyPunpun = Pun Pun Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobMonkey = Monkey Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobPurpleSnake = Purple Snake Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobSmallPurpleSnake = Small Purple Snake Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobSlug = Slug Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobLizard = Lizard Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobCrab = Crab Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobGoat = Goat Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobFrog = Frog Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobBee = Bee Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobParrot = Parrot Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobButterfly = Butterfly Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobCow = Cow Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobGorilla = Gorilla Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobPenguin = Penguin Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
