ent-BaseBulletIncendiary = base bullet incendiary
    .desc = { ent-BaseBullet.desc }
    .suffix = { "" }
ent-BulletTaser = taser bolt
    .desc = { ent-BaseBullet.desc }
    .suffix = { "" }
ent-BulletCharge = charge bolt
    .desc = Marks a target for additional damage.
    .suffix = { "" }
ent-GrapplingHook = grappling hook
    .desc = { "" }
    .suffix = { "" }
