ent-FoodBurgerCat = котобургер
    .desc = Наконец-то эти кошки и кошколюди чего-то стоят!
    .suffix = { "" }
ent-FoodBurgerHuman = человекобургер
    .desc = Вы не можете сказать, из кого это сделано...
    .suffix = { "" }
ent-FoodBurgerPlain = простой бургер
    .desc = Скучный, сухой бургер.
    .suffix = { "" }
