ent-ReagentContainerCornmeal = мешок кукурузной муки
    .desc = Большой мешок кукурузной муки. Отлично подходит для выпечки!
    .suffix = { "" }
ent-ReagentContainerCornmealSmall = пачка кукурузной муки
    .desc = Пакет кукурузной муки. Отлично подходит для выпечки!
    .suffix = { "" }
ent-FoodDoughCornmeal = тесто из кукурузной муки
    .desc = Кусок теста из кукурузной муки.
    .suffix = { "" }
ent-FoodDoughCornmealSlice = кусочек теста из кукурузной муки
    .desc = Кусочек теста из кукурузной муки.
    .suffix = { "" }
