ent-BoxMagazineMagnum = коробка магазинов Lamia
    .desc = Коробка полная магазинов Lamia.
    .suffix = { "" }
ent-BoxMagazineMagnumHighVelocity = коробка магазинов Lamia (высокоскоростных)
    .desc = Коробка полная магазинов для Lamia (высокоскоростных).
    .suffix = { "" }
ent-BoxMagazineMagnumPractice = коробка магазинов Lamia (учебных)
    .desc = Коробка полная магазинов Lamia (учебных).
    .suffix = { "" }
ent-BoxMagazinePistolCalicoTopMounted = коробка магазинов Calico .35 auto
    .desc = Коробка полная магазинов Calico .35 auto.
    .suffix = { "" }
