ent-ResearchAndDevelopmentServerMachineCircuitboard = R&D server machine board
    .desc = A machine printed circuit board for the R&D server.
    .suffix = { "" }
ent-CellRechargerCircuitboard = cell recharger machine board
    .desc = A machine printed circuit board for a cell recharger.
    .suffix = { "" }
ent-WeaponCapacitorRechargerCircuitboard = recharger machine board
    .desc = A machine printed circuit board for a recharger.
    .suffix = { "" }
ent-CargoTelepadMachineCircuitboard = cargo telepad machine board
    .desc = A machine printed circuit board for a cargo telepad.
    .suffix = { "" }
ent-SalvageMagnetMachineCircuitboard = salvage magnet machine board
    .desc = A machine printed circuit board for a salvage magnet.
    .suffix = { "" }
