ent-ClothingOuterCoatOvercoat = пальто
    .desc = Теплое темное пальто, подходящее для официальных мероприятий.
    .suffix = { "" }
ent-ClothingOuterCoatGreatcoat = шинель
    .desc = Серая и грубая шинель с подкладкой для защиты от непогоды.
    .suffix = { "" }
ent-ClothingOuterCoatLeatherJacket = кожаный пиджак
    .desc = Прочная кожаная куртка для моды или для удобства.
    .suffix = { "" }
