ent-BoxMagazineMagnum = box of Lamia magazines
    .desc = A box full of Lamia magazines.
    .suffix = { "" }
ent-BoxMagazineMagnumHighVelocity = box of Lamia (high-velocity) magazines
    .desc = A box full of Lamia (high-velocity) magazines.
    .suffix = { "" }
ent-BoxMagazineMagnumPractice = box of Lamia (practice) magazines
    .desc = A box full of Lamia (practice) magazines.
    .suffix = { "" }
ent-BoxMagazinePistolCalicoTopMounted = box of Calico .35 auto magazines
    .desc = A box full of Calico .35 auto magazines.
    .suffix = { "" }
