ent-CrateVendingMachineRestockChefvendFilled = коробка пополнения ШефВенд
    .desc = { ent-CratePlastic.desc }
    .suffix = { "" }
ent-CrateVendingMachineRestockCondimentStationFilled = коробка пополнения станции приправ
    .desc = { ent-CratePlastic.desc }
    .suffix = { "" }
ent-CrateVendingMachineRestockGetmoreChocolateCorpFilled = { ent-CratePlastic }
    .desc = { ent-CratePlastic.desc }
    .suffix = { "" }
ent-CrateVendingMachineRestockChangFilled = { ent-CratePlastic }
    .desc = { ent-CratePlastic.desc }
    .suffix = { "" }
ent-CrateVendingMachineRestockDiscountDansFilled = { ent-CratePlastic }
    .desc = { ent-CratePlastic.desc }
    .suffix = { "" }
ent-CrateVendingMachineRestockDonutFilled = { ent-CratePlastic }
    .desc = { ent-CratePlastic.desc }
    .suffix = { "" }
