ent-FloorTileItemGrassDark = dark grass tile
    .desc = { ent-FloorTileItemBase.desc }
    .suffix = { "" }
ent-FloorTileItemGrassLight = light grass tile
    .desc = { ent-FloorTileItemBase.desc }
    .suffix = { "" }
ent-FloorTileItemDirt = dirt tile
    .desc = { ent-FloorTileItemBase.desc }
    .suffix = { "" }
ent-FloorTileItemBedrock = bedrock tile
    .desc = { ent-FloorTileItemBase.desc }
    .suffix = { "" }
