ent-ClothingMaskClownBase = clown wig and mask
    .desc = A true prankster's facial attire. A clown is incomplete without his wig and mask.
    .suffix = { "" }
ent-ClothingMaskGasMerc = mercenary gas mask
    .desc = Slightly outdated, but reliable military-style gas mask.
    .suffix = { "" }
ent-ClothingMaskRat = rat mask
    .desc = A mask of a rat that looks like a rat. Perhaps they will take you for a fellow rat.
    .suffix = { "" }
ent-ClothingMaskFox = fox mask
    .desc = What does the fox say?
    .suffix = { "" }
ent-ClothingMaskBee = bee mask
    .desc = For the queen!
    .suffix = { "" }
ent-ClothingMaskBear = bear mask
    .desc = I'm a cloudy, cloudy, cloudy, I'm not a bear at all.
    .suffix = { "" }
ent-ClothingMaskRaven = raven mask
    .desc = Where I am, death... or glitter.
    .suffix = { "" }
ent-ClothingMaskJackal = jackal mask
    .desc = It is better not to turn your back to the owner of the mask, it may bite.
    .suffix = { "" }
ent-ClothingMaskBat = bat mask
    .desc = A bloodsucker by night, and a cute, blinded beast by day.
    .suffix = { "" }
ent-ClothingMaskNeckGaiter = neck gaiter
    .desc = Stylish neck gaiter for your neck, can protect from the cosmic wind?...
    .suffix = { "" }
