ent-AltarBase = алтарь
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-AltarNanotrasen = алтарь нанотрейзен
ent-AltarChaos = алтарь хаоса
ent-AltarDruid = алтарь друидов
ent-AltarToolbox = алтарь ящика для инструментов
ent-AltarSpaceChristian = космо-Христианский алтарь
ent-AltarSatana = сатанинский алтарь
ent-AltarTechnology = алтарь технологий
ent-AltarConvertFestival = праздничный алтарь
ent-AltarConvertMaint = алтарь техтуннелей
ent-AltarConvertBlue = синий алтарь
ent-AltarConvertBurden = алтарь бремени
ent-AltarConvert = алтарь обращения
ent-AltarConvertOrange = оранжевый алтарь
ent-AltarConvertRed = красный алтарь
ent-AltarConvertWhite = белый алтарь
ent-AltarConvertYellow = жёлтый алтарь
ent-AltarHeaven = небесный алтарь
ent-AltarFangs = клыкастый алтарь
