ent-SeatBase = стул
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-Chair = стул
ent-Stool = табурет
ent-StoolBar = барный стул
ent-ChairOfficeLight = белое офисное кресло
ent-ChairOfficeDark = тёмное офисное кресло
ent-ComfyChair = удобное кресло
ent-ChairPilotSeat = кресло пилота
ent-ChairWood = деревянный стул
ent-ChairRitual = ритуальный стул
ent-ChairCursed = проклятый стул
ent-ChairFolding = раскладной стул
ent-ChairFoldingSpawnFolded = { ent-ChairFolding }
