ent-EmpImplanter = шприц имплантата ЭМИ
    .desc = { ent-BaseImplantOnlyImplanter.desc }
    .suffix = { "" }
ent-DnaScramblerImplanter = шприц имплантата искажателя ДНК
    .desc = { ent-BaseImplantOnlyImplanter.desc }
    .suffix = { "" }
ent-DeathRattleImplanter = шприц имплантата предсмертнохрип
    .desc = { ent-BaseImplantOnlyImplanter.desc }
    .suffix = { "" }
