ent-ClothingHeadset = гарнитура
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingHeadsetGrey = гарнитура ассистента
ent-ClothingHeadsetCargo = гарнитура карго
ent-ClothingHeadsetMining = шахтёрская гарнитура
ent-ClothingHeadsetQM = гарнитура КМ
ent-ClothingHeadsetCentCom = гарнитура Центком
ent-ClothingHeadsetCommand = командная гарнитура
ent-ClothingHeadsetEngineering = инженерная гарнитура
ent-ClothingHeadsetCE = гарнитура СИ
ent-ClothingHeadsetMedical = медицинская гарнитура
ent-ClothingHeadsetScience = научная гарнитура
ent-ClothingHeadsetMedicalScience = медико-научная гарнитура
ent-ClothingHeadsetRobotics = робототехническая гарнитура
ent-ClothingHeadsetRD = гарнитура НР
ent-ClothingHeadsetSecurity = охранная гарнитура
ent-ClothingHeadsetService = сервисная гарнитура
