ent-ColoredLightTubeRed = красная лампочка-трубка
    .desc = Красочная лампочка-трубка. Излучает красный свет.
    .suffix = { "" }
ent-ColoredLightTubeFrostyBlue = синяя лампочка-трубка
    .desc = Красочная лампочка-трубка. Излучает холодный синий свет.
    .suffix = { "" }
ent-ColoredLightTubeBlackLight = чёрная лампочка-трубка
    .desc = Красочная лампочка-трубка. Излучает "чёрный" цвет.
    .suffix = { "" }
