ent-FoodEggBase = { ent-FoodInjectableBase }
    .desc = Яйцо!
    .suffix = { "" }
ent-PuddleEgg = { ent-PuddleTemporary }
    .desc = { ent-PuddleTemporary.desc }
    .suffix = { "" }
ent-Eggshells = скорлупа
    .desc = Ты ходишь по ней, приятель.
    .suffix = { "" }
ent-FoodEgg = яйцо
    .desc = { ent-FoodEggBase.desc }
    .suffix = { "" }
