ent-BaseWall = базовая стена
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-WallBrick = кирпичная стена
ent-WallClock = часовая стена
ent-WallClown = клоунская стена
ent-WallCult = стена культа
ent-WallDebug = debug wall
ent-WallDiamond = бриллиантовая стена
ent-WallGold = золотая стена
ent-WallIce = ледяная стена
ent-WallPlasma = плазменная стена
ent-WallPlastic = пластиковая стена
ent-WallPlastitaniumIndestructible = пластитановая стена
ent-WallPlastitanium = пластитановая стена
ent-WallReinforced = укреплённая стена
ent-WallRiveted = клёпаная стена
ent-WallSandstone = песчаниковая стена
ent-WallSilver = серебряная стена
ent-WallShuttleDiagonal = стена шаттла
ent-WallShuttle = стена шаттла
ent-WallSolid = обычная стена
ent-WallSolidRust = обычная стена
ent-WallUranium = урановая стена
ent-WallWood = деревянная стена
ent-WallVaultAlien = инопланетная стена хранилища
ent-WallVaultRock = каменная стена хранилища
ent-WallVaultSandstone = песчаниковая каменная стена
ent-WallInvisible = невидимая стена
ent-WallForce = силовой барьер
