ent-ClothingMaskGas = противогаз
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-ClothingMaskGasSecurity = противогаз СБ
ent-ClothingMaskGasSyndicate = противогаз синдиката
ent-ClothingMaskGasAtmos = атмос-противогаз
ent-ClothingMaskGasCaptain = противогаз капитана
ent-ClothingMaskGasCentcom = противогаз Центком
ent-ClothingMaskGasExplorer = противогаз исследователя
ent-ClothingMaskBreathMedical = медицинская маска
ent-ClothingMaskBreath = дыхательная маска
ent-ClothingMaskClown = маска и парик клоуна
ent-ClothingMaskJoy = маска радости
ent-ClothingMaskMime = маска мима
ent-ClothingMaskSterile = стерильная маска
ent-ClothingMaskMuzzle = намордник
ent-ClothingMaskPlague = маска чумного доктора
