ent-RegenerativeMesh = regenerative mesh
    .desc = Used to treat even the nastiest burns. Also effective against caustic burns.
    .suffix = { "" }
ent-OintmentAdvanced1 = { ent-RegenerativeMesh }
    .desc = { ent-RegenerativeMesh.desc }
    .suffix = { "" }
ent-MedicatedSuture = medicated suture
    .desc = A suture soaked in medicine, treats blunt-force trauma effectively and closes wounds.
    .suffix = { "" }
ent-BrutepackAdvanced1 = { ent-MedicatedSuture }
    .desc = { ent-MedicatedSuture.desc }
    .suffix = { "" }
ent-PillBicaridine = bicaridine pill (10u)
    .desc = { ent-Pill.desc }
    .suffix = { "" }
ent-PillAmbuzol = ambuzol pill
    .desc = { ent-Pill.desc }
    .suffix = { "" }
ent-SyringeBicaridine = bicaridine syringe
    .desc = { ent-BaseSyringe.desc }
    .suffix = { "" }
ent-SyringeDermaline = dermaline syringe
    .desc = { ent-BaseSyringe.desc }
    .suffix = { "" }
ent-SyringeHyronalin = hyronalin syringe
    .desc = { ent-BaseSyringe.desc }
    .suffix = { "" }
ent-SyringeAmbuzol = ambuzol syringe
    .desc = { ent-BaseSyringe.desc }
    .suffix = { "" }
ent-SyringeRomerol = romerol syringe
    .desc = { ent-BaseSyringe.desc }
    .suffix = { "" }
