ent-HyposprayBorgStandard = гипоспрей с эпинефрином 
    .desc = Борг-версия гипоспрея, который автоматически регенерирует эпинефрин.
    .suffix = { "" }
ent-HyposprayBorgMedical = гипоспрей медицинского киборга
    .desc = Гипоспрей с возможностью переключаться между несколькими реагентами.
    .suffix = { "" }
ent-StackHolderSteel = держатель стальных листов
    .desc = Удерживает стальные листы внутри этого борга.
    .suffix = { "" }
ent-StackHolderHealingItem = держатель лечебного предмета
    .desc = Удерживает лечебные предметы внутри этого борга
    .suffix = { "" }
ent-StackHolderFloorTile = держатель плиток пола
    .desc = Удерживает плитки пола внутри этого борга.
    .suffix = { "" }
ent-StackHolderCable = держатель кабеля
    .desc = Удерживает кабели внутри этого борга.
    .suffix = { "" }
ent-PartRodMetalInfinite = { ent-PartRodMetal }
    .desc = { ent-PartRodMetal.desc }
    .suffix = { "" }
ent-BorgToolStandard = инструмент киборга
    .desc = Alternates between prying and anchoring.
    .suffix = { "" }
ent-ClothingHeadsetBorg = { ent-ClothingHeadsetAltCommand }
    .desc = { ent-ClothingHeadsetAltCommand.desc }
    .suffix = { "" }
ent-FloorTileItemSteelFull = { ent-FloorTileItemSteel }
    .suffix = Полон
    .desc = { ent-FloorTileItemSteel.desc }
ent-BorgHealthAnalyzer = анализатор здоровья медицинского робота
    .desc = Ручной сканер тела, способный различать жизненные показатели субъекта.
    .suffix = { "" }
ent-HandheldHealthAnalyzerBorg = анализатор здоровья
    .desc = Ручной сканер тела, работающий от ваших собственных силовых ячеек, способный различать жизненные признаки субъекта.
    .suffix = { "" }
ent-HandheldCrewMonitorBorg = портативный монитор экипажа
    .desc = Ручной монитор экипажа, который работает от ваших собственных силовых элементов и отображает состояние датчиков скафандра.
    .suffix = { "" }
