ent-DrinkDulleaveneGlass = dulleavene glass
    .desc = Allegedly it's a cocktail. The warning cone motif seems apt.
    .suffix = { "" }
ent-DrinkGunmetalGlass = gunmetal glass
    .desc = A cloudy mix of rum, cream, and... is that welding fuel? Probably tasty.
    .suffix = { "" }
ent-DrinkLemonDropGlass = lemon drop
    .desc = A martini glass filled with a translucent mix of refreshing lemony goodness.
    .suffix = { "" }
ent-DrinkGreenGrassGlass = green grass
    .desc = An odd green cocktail, topped with oranges, ice, and a plastic straw. Curious.
    .suffix = { "" }
ent-DrinkDaiquiriGlass = classic daiquiri
    .desc = Rum, lime, and simple syrup. Such class, such refinement.
    .suffix = { "" }
ent-DrinkArsonistsBrewGlass = arsonist's brew
    .desc = It's probably not concerning that it's glowing faintly. Or bubbling. Or smoking. No, not at all.
    .suffix = { "" }
