ent-WindoorSecureArmoryLocked = { ent-WindoorSecureSecurityLocked }
    .suffix = Оружейная, Закрыто
    .desc = { ent-WindoorSecureSecurityLocked.desc }
ent-WindoorSecureBrigLocked = { ent-WindoorSecureSecurityLocked }
    .suffix = Бриг, Закрыто
    .desc = { ent-WindoorSecureSecurityLocked.desc }
ent-WindoorSecureChemistryLocked = { ent-WindoorSecure }
    .suffix = Химия, Закрыто
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureCommandLocked = { ent-WindoorSecure }
    .suffix = Командный, Закрыто
ent-WindoorSecureEngineeringLocked = { ent-WindoorSecure }
    .suffix = Инженерный, Закрыто
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureExternalLocked = { ent-WindoorSecure }
    .suffix = Внешний, Закрыто
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureMedicalLocked = { ent-WindoorSecure }
    .suffix = Медицинский, Закрыто
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureSecurityLocked = { ent-WindoorSecure }
    .suffix = Охранный, Закрыто
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureScienceLocked = { ent-WindoorSecure }
    .suffix = Научный, Закрыто
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureHeadOfPersonnelLocked = { ent-WindoorSecure }
    .suffix = Глава Персонала, Закрыто
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureAtmosphericsLocked = { ent-WindoorSecure }
    .suffix = Атмос, Закрыто
    .desc = { ent-WindoorSecure.desc }
ent-WindoorSecureParamedicLocked = { ent-WindoorSecure }
    .suffix = Парамедик, Закрыто
    .desc = { ent-WindoorSecure.desc }
