ent-SpawnMobShiva = Shiva Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobKangarooWillow = Willow Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobKangaroo = Space Kangaroo Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobBoxingKangaroo = Boxing Kangaroo Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobSpaceSpider = Space Spider Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesBlue = Slimes Spawner Blue
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesBlueAngry = Slimes Spawner Blue Angry
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesGreen = Slimes Spawner Green
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesGreenAngry = Slimes Spawner Green Angry
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesYellow = Slimes Spawner Yellow
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobAdultSlimesYellowAngry = Slimes Spawner Yellow Angry
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
ent-SpawnMobSmile = Smile Spawner
    .desc = { ent-MarkerBase.desc }
    .suffix = { "" }
