ent-WallPlastitaniumDiagonal = пластитановая стена
    .suffix = diagonal
    .desc = { ent-WallShuttleDiagonal.desc }
ent-WallShuttleInterior = стена шаттла
    .suffix = Interior
    .desc = { ent-WallSolid.desc }
ent-WallSolidDiagonal = сплошная стена
    .suffix = diagonal
    .desc = { ent-WallShuttleDiagonal.desc }
ent-WallPaper = бумажная стена
    .desc = Помогает сдерживать постоянные крики мастеров боевых искусств.
    .suffix = { "" }
