vaccine-name = { $disease } вакцина
vaccine-desc = Ее введене не позволит вам заразиться { $disease } если вы уже не заражены.
vaccine-inject-start-agent = Вы начинаете вводить { ($vaccine) } в { ($target) }.
vaccine-inject-start-patient = { CAPITALIZE(($user)) } начинает вводить вам { INDEFINITE($vaccine) } { $vaccine }.
vaccine-machine-menu-title = Вакцинатор
vaccine-machine-menu-known-diseases-label = Известные заболевания
vaccine-machine-menu-create-vaccine-button = Создать вакцину
vaccine-machine-menu-biomass-cost = Стоимость в биомассе: { $value }
vaccine-machine-menu-biomass-current = Текущее: { $value }
vaccine-machine-menu-none-selected = Выберете болезнь!
vaccine-machine-cost-upgrade = Стоимость в биомассе
