ent-AlwaysPoweredlightColoredRed = { ent-AlwaysPoweredWallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении световой трубкой.
    .suffix = Всегда запитан, красный
ent-AlwaysPoweredlightColoredFrostyBlue = { ent-AlwaysPoweredWallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении световой трубкой.
    .suffix = Всегда запитан, морозный
ent-AlwaysPoweredlightColoredBlack = { ent-AlwaysPoweredWallLight }
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении световой трубкой.
    .suffix = Всегда запитан, чёрный
ent-AlwaysPoweredLightPostSmallRed = почтовый светильник
    .desc = Светильник. Потребляет энергию и излучает свет при оснащении световой трубкой.
    .suffix = Всегда запитан, красный
