ent-ClothingHeadHatBeretMerc = берет наёмника
    .desc = Оливковый берет, на значке изображён шакал на скале.
    .suffix = { "" }
ent-ClothingHeadHatSyndie = шляпа синдиката
    .desc = Сувенирная шапка от "Синдилэнда", производство которой уже закрыто.
    .suffix = { "" }
ent-ClothingHeadHatSyndieMAA = шляпа мастера по оружию
    .desc = Шляпа мастера по оружию, выглядит устрашающе, вряд ли вам захочется общаться с её обладателем...
    .suffix = { "" }
ent-ClothingHeadHatTacticalMaidHeadband = тактическая повязка горничной
    .desc = Красная повязка - не воображайте себя Рэмбо и не берите в руки несколько пулемётов.
    .suffix = { "" }
ent-ClothingHeadHatMagician = шляпа фокусника.
    .desc = Шляпа фокусника.
    .suffix = { "" }
ent-ClothingHeadHatCapcap = капитанская фуражка
    .desc = Торжественная, стильная капитанская фуражка.
    .suffix = { "" }
