ent-ClothingHeadHelmetBasic = шлем
    .desc = Стандартное средство защиты. Защищает голову от воздействий.
    .suffix = { "" }
ent-ClothingHeadHelmetMerc = шлем наёмника
    .desc = Боевой шлем обычно используется наёмниками, он прочный, лёгкий и пахнет порохом и джунглями.
    .suffix = { "" }
ent-ClothingHeadHelmetSwat = шлем спецназа
    .desc = Очень устойчивый шлем, обычно используемый военными организациями. На верхней части шлема выгравирован логотип Nanotrasen.
    .suffix = { "" }
ent-ClothingHeadHelmetSwatSyndicate = шлем спецназа
    .desc = Очень устойчивый шлем, обычно используемый военными организациями. Он украшен гнусным узором из красных и чёрных полос.
    .suffix = Syndicate
ent-ClothingHeadHelmetERTLeader = шлем лидера ОБР
    .desc = Открытый шлем, который носит лидер Отряда Быстрого Реагирования Nanotrasen. Имеет синюю подсветку.
    .suffix = { "" }
ent-ClothingHeadHelmetERTSecurity = шлем офицера ОБР
    .desc = Открытый шлем, который носят офицеры Отряда Быстрого Реагирования Nanotrasen. Имеет красную подсветку.
    .suffix = { "" }
ent-ClothingHeadHelmetERTMedic = шлем медика ОБР
    .desc = Открытый шлем, который носят медики Отряда Быстрого Реагирования Nanotrasen. Имеет белую подсветку.
    .suffix = { "" }
ent-ClothingHeadHelmetERTEngineer = шлем инженера ОБР
    .desc = Открытый шлем, который носят инженеры Отряда Быстрого Реагирования Nanotrasen. Имеет оранжевую подсветку.
    .suffix = { "" }
ent-ClothingHeadHelmetERTJanitor = шлем уборщика ОБР
    .desc = Открытый шлем, который носят уборщики Отряда Быстрого Реагирования Nanotrasen. Имеет фиолетовую подсветку.
    .suffix = { "" }
