ent-ClothingOuterRobeWhite = белая роба
    .desc = Это совсем не выглядит жутко.
    .suffix = { "" }
ent-ClothingOuterRobeBrown = коричневая роба
    .desc = Это совсем не выглядит жутко.
    .suffix = { "" }
ent-ClothingOuterRobeMystic = роба мистика
    .desc = Яркое одеяние мистагога.
    .suffix = { "" }
ent-ClothingOuterRobeTechPriest = роба автоматурга
    .desc = Роботы по сути быки, если подумать, поэтому лучше носить красное.
    .suffix = { "" }
