ent-EngineeringTechFabCircuitboard = engineering techfab machine board
    .desc = A machine printed circuit board for a engineering techfab
    .suffix = { "" }
ent-ServiceTechFabCircuitboard = service techfab machine board
    .desc = A machine printed circuit board for a service techfab
    .suffix = { "" }
ent-ScienceTechFabCircuitboard = epistemics techfab machine board
    .desc = A machine printed circuit board for an epistemics techfab
    .suffix = { "" }
ent-MetempsychoticMachineCircuitboard = metempsychotic machine machine board
    .desc = A machine printed circuit board for a cloning pod
    .suffix = { "" }
ent-ReverseEngineeringMachineCircuitboard = reverse engineering machine machine board
    .desc = A machine printed circuit board for a reverse engineering machine
    .suffix = { "" }
