ent-ScanningModuleStockPart = scanning module
    .desc = A compact, high resolution scanning module used in the construction of certain devices.
    .suffix = { "" }
ent-MicroLaserStockPart = micro-laser
    .desc = A tiny laser used in certain devices.
    .suffix = { "" }
ent-AdvancedScanningModuleStockPart = advanced scanning module
    .desc = A compact, high resolution scanning module used in the construction of certain devices.
    .suffix = { "" }
ent-HighPowerMicroLaserStockPart = high-power micro-laser
    .desc = A tiny laser used in certain devices.
    .suffix = { "" }
ent-PhasicScanningModuleStockPart = phasic scanning module
    .desc = A compact, high resolution phasic scanning module used in the construction of certain devices.
    .suffix = { "" }
ent-UltraHighPowerMicroLaserStockPart = ultra-high-power micro-laser
    .desc = A tiny laser used in certain devices.
    .suffix = { "" }
ent-TriphasicScanningModuleStockPart = triphasic scanning module
    .desc = A compact, ultra resolution triphasic scanning module used in the construction of certain devices.
    .suffix = { "" }
ent-QuadUltraMicroLaserStockPart = quad-ultra micro-laser
    .desc = A tiny laser used in certain devices.
    .suffix = { "" }
