ent-LockerMystagogueFilled = mystagogue's locker
    .suffix = Filled
    .desc = { ent-LockerResearchDirector.desc }
ent-LockerEpistemicsFilled = acolyte's locker
    .suffix = Filled
    .desc = { ent-LockerScientist.desc }
ent-LockerForensicMantisFilled = { ent-LockerForensicMantis }
    .suffix = Filled
    .desc = { ent-LockerForensicMantis.desc }
