ent-PartSpider = spider body part
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-ThoraxSpider = spider thorax
    .desc = { ent-PartSpider.desc }
    .suffix = { "" }
ent-RightLegSpider = right spider leg
    .desc = { ent-PartSpider.desc }
    .suffix = { "" }
ent-LeftLegSpider = left spider leg
    .desc = { ent-PartSpider.desc }
    .suffix = { "" }
