ent-GasMinerBase = добытчик газа
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-GasMinerOxygen = газодобытчик O2
ent-GasMinerNitrogen = газодобытчик N2
ent-GasMinerCarbonDioxide = газодобытчик CO2
ent-GasMinerPlasma = газодобытчик плазмы
ent-GasMinerTritium = газодобытчик трития
ent-GasMinerWaterVapor = газодобытчик водяного пара
ent-GasMinerMiasma = газодобытчик миазм
ent-GasMinerNitrousOxide = газодобытчик оксида азота N2O
