ent-GasUnaryBase = { ent-GasPipeBase }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-GasVentPump = вентиляция
ent-GasPassiveVent = пассивная вентиляция
ent-GasVentScrubber = скруббер
ent-GasOutletInjector = инжектор
ent-BaseGasThermoMachine = термомашина
ent-GasThermoMachineFreezer = охладитель
ent-GasThermoMachineHeater = нагреватель
