marking-FelinidEarsBasic = Стандартные ушки
marking-FelinidEarsBasic-basic_outer = Внешнее ухо
marking-FelinidEarsBasic-basic_inner = Внутреннее ухо
marking-FelinidEarsCurled = Закрученные ушки
marking-FelinidEarsCurled-curled_outer = Внешнее ухо
marking-FelinidEarsCurled-curled_inner = Внутреннее ухо
marking-FelinidEarsDroopy = Висячие ушки
marking-FelinidEarsDroopy-droopy_outer = Внешнее ухо
marking-FelinidEarsDroopy-droopy_inner = Внутреннее ухо
marking-FelinidEarsFuzzy = Пушистые ушки
marking-FelinidEarsFuzzy-basic_outer = Внешнее ухо
marking-FelinidEarsFuzzy-fuzzy_inner = Ушной пушок
marking-FelinidEarsStubby = Короткие ушки
marking-FelinidEarsStubby-stubby_outer = Внешнее ухо
marking-FelinidEarsStubby-stubby_inner = Внутреннее ухо
marking-FelinidEarsTall = Длинные ушки
marking-FelinidEarsTall-tall_outer = Внешнее ухо
marking-FelinidEarsTall-tall_inner = Внутреннее ухо
marking-FelinidEarsTall-tall_fuzz = Ушной пушок
marking-FelinidEarsTorn = Порванные ушки
marking-FelinidEarsTorn-torn_outer = Внешнее ухо
marking-FelinidEarsTorn-torn_inner = Внутреннее ухо
marking-FelinidEarsWide = Широкие ушки
marking-FelinidEarsWide-wide_outer = Внешнее ухо
marking-FelinidEarsWide-wide_inner = Внутреннее ухо
marking-FelinidTailBasic = Стандартный хвост
marking-FelinidTailBasic-basic_tail_tip = Кончик хвоста
marking-FelinidTailBasic-basic_tail_stripes_even = Полоски на хвосте, четные
marking-FelinidTailBasic-basic_tail_stripes_odd = Полосы на хвосте, нечетные
marking-FelinidTailBasicWithBow = Стандартный хвост с бантом
marking-FelinidTailBasicWithBow-basic_tail_tip = Кончик хвоста
marking-FelinidTailBasicWithBow-basic_tail_stripes_even = Полоски на хвосте, четные
marking-FelinidTailBasicWithBow-basic_tail_stripes_odd = Полосы на хвосте, нечетные
marking-FelinidTailBasicWithBow-basic_bow = Бант
marking-FelinidTailBasicWithBell = Стандартный хвост с колокольчиком
marking-FelinidTailBasicWithBell-basic_tail_tip = Кончик хвоста
marking-FelinidTailBasicWithBell-basic_tail_stripes_even = Полоски на хвосте, четные
marking-FelinidTailBasicWithBell-basic_tail_stripes_odd = Полосы на хвосте, нечетные
marking-FelinidTailBasicWithBell-basic_bell = Колокольчик
marking-FelinidTailBasicWithBowAndBell = Стандартный хвост с бантом и колокольчиком
marking-FelinidTailBasicWithBowAndBell-basic_tail_tip = Кончик хвоста
marking-FelinidTailBasicWithBowAndBell-basic_tail_stripes_even = Полоски на хвосте, четные
marking-FelinidTailBasicWithBowAndBell-basic_tail_stripes_odd = Полосы на хвосте, нечетные
marking-FelinidTailBasicWithBowAndBell-basic_bow = Бант
marking-FelinidTailBasicWithBowAndBell-basic_bell = Колокольчик
