ent-DrinkOrangeCreamiceGlass = orange creamcicle glass
    .desc = Orangy, creamy goodness.
    .suffix = { "" }
ent-DrinkSilverjackGlass = silverjack glass
    .desc = Reminds you of family.
    .suffix = { "" }
ent-DrinkBrainbombGlass = brainbomb glass
    .desc = Toxic to about anything alive, especially your liver.
    .suffix = { "" }
ent-DrinkClownBloodGlass = clown blood glass
    .desc = Security Officers favorite drink after a long day.
    .suffix = { "" }
ent-DrinkCircusJuiceGlass = circus juice glass
    .desc = Honkmother would be proud.
    .suffix = { "" }
ent-DrinkSapoPicanteGlass = sapo picante glass
    .desc = Tastes nothing like a toad.
    .suffix = { "" }
ent-DrinkGraveyardGlass = graveyard glass
    .desc = For those shifts that never seem to end.
    .suffix = { "" }
ent-DrinkAtomicPunchGlass = atomic punch glass
    .desc = Will NOT make you immune to bullets; Isotopes included!
    .suffix = { "" }
ent-DrinkPinkDrinkGlass = pink drink glass
    .desc = Entire civilizations have crumbled trying to decide if this drink really tastes like pink...
    .suffix = { "" }
ent-DrinkBubbleTeaGlass = bubble tea glass
    .desc = Big straw not included.
    .suffix = { "" }
