ent-DrinkOrangeCreamiceGlass = стакан с апельсиновым кремом
    .desc = Оранжевое, сливочное совершенство.
    .suffix = { "" }
ent-DrinkSilverjackGlass = стакан сильверджека
    .desc = Напоминает вам о семье.
    .suffix = { "" }
ent-DrinkBrainbombGlass = стакан мозговой бомбы
    .desc = Токсично для всего живого, особенно для печени.
    .suffix = { "" }
ent-DrinkClownBloodGlass = стакан крови клоуна
    .desc = Любимый напиток сотрудников службы безопасности после долгого дня.
    .suffix = { "" }
ent-DrinkCircusJuiceGlass = стакан циркового сока
    .desc = Хонкмать бы гордилась.
    .suffix = { "" }
ent-DrinkSapoPicanteGlass = стакан сапо пиканте
    .desc = На вкус не похож на жабу.
    .suffix = { "" }
ent-DrinkGraveyardGlass = стакан кладбища
    .desc = Для тех смен, которые никогда не заканчиваются.
    .suffix = { "" }
ent-DrinkAtomicPunchGlass = стакан атомного удара
    .desc = НЕ сделает вас невосприимчивым к пулям; Изотопы включены!
    .suffix = { "" }
ent-DrinkPinkDrinkGlass = стакан розового напитока
    .desc = Целые цивилизации рухнули, пытаясь решить, действительно ли этот напиток на вкус розовый...
    .suffix = { "" }
ent-DrinkBubbleTeaGlass = стакан пузырькового чая
    .desc = Большая соломинка в комплект не входит.
    .suffix = { "" }
