ent-BaseWall = basewall
    .desc = Keeps the air in and the greytide out.
    .suffix = { "" }
ent-WallBrick = brick wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallClock = clock wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallClown = clown wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallCult = cult wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallDebug = debug wall
    .suffix = DEBUG
    .desc = { ent-BaseWall.desc }
ent-WallDiamond = diamond wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallGold = gold wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallIce = ice wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallPlasma = plasma wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallPlastic = plastic wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallPlastitaniumIndestructible = plastitanium wall
    .suffix = indestructible
    .desc = { ent-BaseWall.desc }
ent-WallPlastitanium = plastitanium wall
    .desc = { ent-WallPlastitaniumIndestructible.desc }
    .suffix = { "" }
ent-WallReinforced = reinforced wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallRiveted = riveted wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallSandstone = sandstone wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallSilver = silver wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallShuttleDiagonal = shuttle wall
    .desc = Keeps the air in and the greytide out.
    .suffix = diagonal
ent-WallShuttle = shuttle wall
    .desc = { ent-WallReinforced.desc }
    .suffix = { "" }
ent-WallShuttleInterior = shuttle wall
    .suffix = Interior
    .desc = { ent-WallSolid.desc }
ent-WallSolid = solid wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallSolidRust = solid wall
    .suffix = rusted
    .desc = { ent-BaseWall.desc }
ent-WallUranium = uranium wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallWood = wood wall
    .desc = { ent-BaseWall.desc }
    .suffix = { "" }
ent-WallPaper = paper wall
    .desc = Helps to contain the repeated screams of martial artists.
    .suffix = { "" }
ent-WallVaultAlien = alien vault wall
    .desc = A mysterious ornate looking wall. There may be ancient dangers inside.
    .suffix = { "" }
ent-WallVaultRock = rock vault wall
    .desc = { ent-WallVaultAlien.desc }
    .suffix = { "" }
ent-WallVaultSandstone = sandstone vault wall
    .desc = { ent-WallVaultAlien.desc }
    .suffix = { "" }
ent-WallInvisible = Invisible Wall
    .desc = { "" }
    .suffix = { "" }
ent-WallForce = force wall
    .desc = { "" }
    .suffix = { "" }
