ent-UniformJabroni = jabroni outfit
    .desc = For artists, perfomance artists.
    .suffix = { "" }
ent-UniformSchoolgirlRed = red schoolgirl uniform
    .desc = Ready for school!
    .suffix = { "" }
ent-UniformSchoolgirlBlack = black schoolgirl uniform
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlBlue = blue schoolgirl uniform
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlCyan = cyan schoolgirl uniform
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlGreen = green schoolgirl uniform
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlOrange = orange schoolgirl uniform
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlPink = pink schoolgirl uniform
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformSchoolgirlPurple = purple schoolgirl uniform
    .desc = { ent-UniformSchoolgirlRed.desc }
    .suffix = { "" }
ent-UniformMaid = maid uniform
    .desc = Authentic, from Space France!
    .suffix = { "" }
ent-UniformGeisha = geisha dress
    .desc = For a good hostess.
    .suffix = { "" }
ent-ClothingUniformJumpskirtNurse = nurse skirt
    .desc = Time to carry the medical department.
    .suffix = { "" }
ent-ClothingCostumeArcDress = white shirt and purple skirt
    .desc = You feel a supernatural urge to put these on. It must be fate.
    .suffix = { "" }
