ent-ClothingUniformMailCarrier = mail carrier's uniform
    .desc = Enemy of dogs everywhere.
    .suffix = { "" }
ent-ClothingUniformSkirtMailCarrier = mail carrier's jumpskirt
    .desc = Enemy of dogs everywhere.
    .suffix = { "" }
ent-ClothingUniformJumpsuitMystagogue = mystagogue's turtleneck
    .desc = It's a turtleneck worn by those with the holy aura to achieve the role of Mystagogue. You can practically feel the psychic energies radiating from this thing, not to mention the actual radiation.
    .suffix = { "" }
ent-ClothingUniformJumpsuitTshirtJeans = white t-shirt and jeans
    .desc = Even in space, this combo is still in style.
    .suffix = { "" }
ent-ClothingUniformJumpsuitTshirtJeansGray = gray t-shirt and jeans
    .desc = Even though there are no forests in space, this combo is still practical.
    .suffix = { "" }
ent-ClothingUniformJumpsuitTshirtJeansPeach = peach t-shirt and jeans
    .desc = Even though your favorite emo clothing store is back at home, this combo is still edgy.
    .suffix = { "" }
ent-ClothingUniformJumpsuitMantis = forensic mantis' uniform
    .desc = Modeled after an ancient infantry uniform, this uniform has superior mobility for tense situations.
    .suffix = { "" }
ent-ClothingUniformSkirtMantis = forensic mantis' jumpskirt
    .desc = Adapted from an ancient infantry uniform, this jumpskirt has superior mobility for tense situations.
    .suffix = { "" }
ent-ClothingUniformJumpsuitPrisonGuard = prison guard's uniform
    .desc = A comfortable, durable, waterproof uniform made to keep prison staff comfortable and safe.
    .suffix = { "" }
