research-discipline-none = Нет
research-discipline-industrial = Промышленная
research-discipline-biochemical = Биохимическая
research-discipline-arsenal = Оружейная
research-discipline-experimental = Экспериментальная
research-discipline-civilian-services = Сервисная
research-technology-salvage-equipment = Экипировка для утилизаторов
research-technology-advanced-powercells = Продвинутые батареи
research-technology-compact-power = Компактное энергопитание
research-technology-industrial-engineering = Промышленная инженерия
research-technology-power-generation = Выработка электроэнергии
research-technology-atmospheric-tech = Атмосферика
research-technology-rapid-construction = Быстрое строительство
research-technology-shuttlecraft = Шаттлостроение
research-technology-ripley-aplu = Рипли АТМЕ
research-technology-advanced-atmospherics = Продвинутая атмосферика
research-technology-advanced-tools = Продвинутые инструменты
research-technology-super-powercells = Супер батареи
research-technology-bluespace-storage = Блюспейс хранилище
research-technology-chemistry = Химия
research-technology-surgical-tools = Хирургические инструменты
research-technology-biochemical-stasis = Биохимический стазис
research-technology-virology = Вирусология
research-technology-cryogenics = Криогеника
research-technology-chemical-dispensary = Химическое оборудование
research-technology-crew-monitoring = Мониторинг экипажа
research-technology-cloning = Клонирование
research-technology-salvage-weapons = Оружия утилизаторов
research-technology-draconic-munitions = Драконовые боеприпасы
research-technology-explosive-technology = Технология взрывчаток
research-technology-advanced-laser-manipulation = Продвинутое лазерное оружие
research-technology-nonlethal-ammunition = Нелетальная аммуниция
research-technology-optimized-ballistics = Улучшенная баллистика
research-technology-concentrated-laser-weaponry = Кучное лазерное оружие
research-technology-wave-particle-harnessing = Использование рентген-частиц
research-technology-handheld-electrical-propulsion = Ручная электро-индукция
research-technology-basic-robotics = Базовая робототехника
research-technology-basic-anomalous-research = Базовая технология аномалий
research-technology-basic-xenoarcheology = Базовая ксеноархеология
research-technology-alternative-research = Альтернативное исследование
research-technology-magnets-tech = Локальный магнетизм
research-technology-advanced-parts = Продвинутые детали
research-technology-grappling = Цепляющие приспособления
research-technology-abnormal-artifact-manipulation = Иное управление артефактами
research-technology-gravity-manipulation = Управление гравитацией
research-technology-mobile-anomaly-tech = Технология порт-аномалий
research-technology-rped = Быстрая замена деталей
research-technology-super-parts = Супер детали
research-technology-janitorial-equipment = Уборочное снаряжение
research-technology-laundry-tech = Технология прачечной
research-technology-basic-hydroponics = Базовая гидропоника
research-technology-food-service = Общественное питание
research-technology-advanced-entertainment = Продвинутые развлечения
research-technology-audio-visual-communication = А/В Связь
research-technology-advanced-cleaning = Продвинутая уборка
research-technology-meat-manipulation = Манипуляции с мясом
research-technology-honk-mech = Х.О.Н.К. Меха
research-technology-advanced-spray = Продвинутый спрей
research-technology-bluespace-cargo-transport = Блюспейс грузовой транспорт
