guide-entry-singularity = Singularity
guide-entry-radio = Radio
guide-entry-cargo-bounties = Cargo Bounties
guide-entry-salvage = Salvage
guide-entry-chemicals = Chemicals
guide-entry-bartender = Bartender
guide-entry-foodrecipes = Food Recipes
guide-entry-medical = Medical
guide-entry-medicaldoctor = Medical Doctor
guide-entry-chemist = Chemist
guide-entry-medicine = Medicine
guide-entry-botanicals = Botanicals
guide-entry-cloning = Cloning
guide-entry-cryogenics = Cryogenics
guide-entry-science = Science
guide-entry-robotics = Robotics
guide-entry-antagonists = Antagonists
guide-entry-nuclear-operatives = Nuclear Operatives
