ent-LockerBooze = шкафчик со спиртным
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-LockerQuarterMaster = шкаф квартирмейстера
ent-LockerSalvageSpecialist = снаряжение специалиста по утилизации
ent-LockerCaptain = шкаф капитана
ent-LockerHeadOfPersonnel = шкаф главы персонала
ent-LockerChiefEngineer = шкаф старшего инженера
ent-LockerElectricalSupplies = шкаф электромонтажного оборудования
ent-LockerWeldingSupplies = шкаф сварочного оборудования
ent-LockerAtmospherics = шкаф атмосферного техника
ent-LockerEngineer = шкаф инженера
ent-LockerFreezer = холодильник
ent-LockerBotanist = шкаф ботаника
ent-LockerMedicine = шкаф для медикаментов
ent-LockerMedical = шкаф врача
ent-LockerChemistry = шкаф химика
ent-LockerChiefMedicalOfficer = шкаф главного врача
ent-LockerResearchDirector = шкаф научного руководителя
ent-LockerScientist = шкаф учёного
ent-LockerHeadOfSecurity = шкаф главы службы безопасности
ent-LockerWarden = шкаф смотрителя
ent-LockerSecurity = шкаф офицера службы безопасности
ent-LockerDetective = шкаф детектива
ent-LockerEvidence = шкаф для улик
ent-LockerSyndicatePersonal = оружейный шкаф
ent-LockerBluespaceStation = блюспейс шкаф
