mopping-system-tool-full = { CAPITALIZE(($used)) } полон!
mopping-system-puddle-diluted = Вы разбавляете лужу.
mopping-system-puddle-success = Вы смачиваете лужу.
mopping-system-release-to-floor = Вы выдавливаете часть жидкости на пол.
mopping-system-target-container-full = { CAPITALIZE(($target)) } полон!
mopping-system-target-container-too-small = { CAPITALIZE(($target)) } слишком мал для этого!
mopping-system-refillable-success = Вы выжимаете { ($used) } в { ($target) }.
mopping-system-drainable-success = Вы смачиваете { ($used) } из { ($target) }.
mopping-system-hand-squeeze-still-wet = Вы выжимаете { ($used) } руками. Она все еще влажная.
mopping-system-hand-squeeze-little-wet = Вы выжимаете { ($used) } руками. Она все еще немного влажная.
mopping-system-hand-squeeze-dry = Вы выжимаете { ($used) } руками. Она вполне суха.
