ent-PianoInstrument = рояль
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-UprightPianoInstrument = пианино
ent-VibraphoneInstrument = вибрафон
ent-MarimbaInstrument = маримба
ent-ChurchOrganInstrument = церковный орган
ent-TubaInstrument = туба
ent-HarpInstrument = арфа
ent-TimpaniInstrument = литавры
ent-TaikoInstrument = тайко
ent-ContrabassInstrument = контрабас
ent-MinimoogInstrument = минимуг
ent-TomDrumsInstrument = том-том
ent-DawInstrument = цифровая звуковая рабочая станция
