ent-StationMapBroken = карта станции
    .desc = Виртуальная карта окружающей станции.
    .suffix = Настенный, сломанный
ent-StationMap = карта станции
    .suffix = Настенный, сломанный
    .desc = { ent-StationMapBroken.desc }
ent-StationMapAssembly = каркас карты станции
    .desc = Каркас карты станции.
    .suffix = { "" }
