ent-BedsheetBase = базовое одеяло
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-BedsheetBlack = чёрное одеяло
ent-BedsheetBlue = синее одеяло
ent-BedsheetBrown = коричневое одеяло
ent-BedsheetCaptain = одеяло капитана
ent-BedsheetCE = одеяло старшего инженера
ent-BedsheetCentcom = одеяло Центком
ent-BedsheetClown = одеяло клоуна
ent-BedsheetCMO = одеяло главврача
ent-BedsheetCosmos = космическая одеяло
ent-BedsheetCult = одеяло культа
ent-BedsheetGreen = зелёное одеяло
ent-BedsheetGrey = серое одеяло
ent-BedsheetHOP = одеяло главы персонала
ent-BedsheetHOS = одеяло главы СБ
ent-BedsheetIan = одеяло Иана
ent-BedsheetMedical = медицинское одеяло
ent-BedsheetMime = одеяло мима
ent-BedsheetNT = одеяло NT
ent-BedsheetOrange = оранжевое одеяло
ent-BedsheetPurple = фиолетовое одеяло
ent-BedsheetQM = одеяло квартирмейстера
ent-BedsheetRainbow = радужное одеяло
ent-BedsheetRD = одеяло научрука
ent-BedsheetRed = красное одеяло
ent-BedsheetSyndie = одеяло cинди
ent-BedsheetUSA = одеяло США
ent-BedsheetWhite = белое одеяло
ent-BedsheetWiz = одеяло волшебника
ent-BedsheetYellow = жёлтое одеяло
