ent-IDCardStandard = идентификационная карта
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-PassengerIDCard = ID карта ассистента
ent-SecurityCadetIDCard = ID карта кадета СБ
ent-CaptainIDCard = ID карта капитана
ent-SecurityIDCard = ID карта службы безопасности
ent-WardenIDCard = ID карта смотрителя
ent-EngineeringIDCard = ID карта инженера
ent-MedicalIDCard = ID карта медика
ent-QuartermasterIDCard = ID карта квартирмейстера
ent-ClownIDCard = ID карта клоуна
ent-MimeIDCard = ID карта мима
ent-ChaplainIDCard = ID карта священика
ent-JanitorIDCard = ID карта уборщика
ent-BartenderIDCard = ID карта бармена
ent-ChefIDCard = ID карта шеф-повара
ent-BotanistIDCard = ID карта ботаника
ent-LawyerIDCard = ID карта адвоката
ent-HoPIDCard = ID карта главы персонала
ent-CEIDCard = ID карта старшего инженера
ent-CMOIDCard = ID карта главного врача
ent-HoSIDCard = ID карта главы службы безопасности
ent-CentcomIDCard = ID карта старшего офицера
ent-ERTLeaderIDCard = ID карта ОБР
ent-CentcomIDCardSyndie = ID карта представителя ЦентКом
ent-MusicianIDCard = ID карта музыканта
ent-CentcomIDCardDeathsquad = ID карта эскадрона смерти
ent-AgentIDCard = { ent-PassengerIDCard }
ent-AtmosIDCard = ID карта атмосферного техника
ent-SyndicateIDCard = ID карта Синдиката
ent-PsychologistIDCard = ID карта психолога
ent-ReporterIDCard = ID карта репортёра
ent-BoxerIDCard = ID карта боксёра
ent-CBURNIDcard = ID карта РХБЗЗ
