ent-BaseStockPart = stock part
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-CapacitorStockPart = конденсатор
ent-ScanningModuleStockPart = сканирующий модуль
ent-MicroManipulatorStockPart = микроманипулятор
ent-MicroLaserStockPart = микролазер
ent-MatterBinStockPart = ёмкость материи
ent-AdvancedCapacitorStockPart = улучшенный конденсатор
ent-AdvancedScanningModuleStockPart = улучшенный сканирующий модуль
ent-NanoManipulatorStockPart = наноманипулятор
ent-HighPowerMicroLaserStockPart = высокомощный микролазер
ent-AdvancedMatterBinStockPart = улучшенная ёмкость материи
ent-SuperCapacitorStockPart = суперконденсатор
ent-PhasicScanningModuleStockPart = фазовый сканирующий модуль
ent-PicoManipulatorStockPart = пико-манипулятор
ent-UltraHighPowerMicroLaserStockPart = ультрамощный микролазер
ent-SuperMatterBinStockPart = супер ёмкость материи
ent-QuadraticCapacitorStockPart = квадратичный конденсатор
ent-TriphasicScanningModuleStockPart = трёхфазовый сканирующий модуль
ent-FemtoManipulatorStockPart = фемто-манипулятор
ent-QuadUltraMicroLaserStockPart = квад-ультра микролазер
ent-BluespaceMatterBinStockPart = блюспейс ёмкость материи
ent-AnsibleSubspaceStockPart = подпространственный ансибл
ent-FilterSubspaceStockPart = гиперволновой фильтр
ent-AmplifierSubspaceStockPart = подпространственный усилитель
ent-TreatmentSubspaceStockPart = диск подпространственной обработки
ent-AnalyzerSubspaceStockPart = подпространственный анализатор длин волны
ent-CrystalSubspaceStockPart = ансибл кристалл
ent-TransmitterSubspaceStockPart = подпространственный трансмиттер
