ent-Paper = бумага
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-PaperOffice = офисная бумага
ent-PaperArtifactAnalyzer = распечатка анализатора артефактов
ent-PaperCaptainsThoughts = мысли капитана
ent-PaperCargoInvoice = накладная карго
ent-PaperWritten = { ent-Paper }
ent-NukeCodePaper = коды ядерной аутентификации
ent-Pen = ручка
ent-CyberPen = ручка Cybersun
ent-PenCap = перьевая ручка капитана
ent-PenHop = перьевая ручка главы персонала
ent-BoxFolderBase = папка
ent-BoxFolderRed = { ent-BoxFolderBase }
ent-BoxFolderBlue = { ent-BoxFolderBase }
ent-BoxFolderYellow = { ent-BoxFolderBase }
ent-BoxFolderWhite = { ent-BoxFolderBase }
ent-BoxFolderGrey = { ent-BoxFolderBase }
ent-BoxFolderBlack = { ent-BoxFolderBase }
ent-RubberStampMime = печать мима
ent-RubberStampCaptain = печать капитана
ent-RubberStampCentcom = печать Центкома
ent-RubberStampChaplain = печать священника
ent-RubberStampClown = печать клоуна
ent-RubberStampCMO = печать главврача
ent-RubberStampDenied = печать ОТКАЗАНО
ent-RubberStampApproved = печать ОДОБРЕНО
ent-RubberStampHop = печать главы персонала
ent-RubberStampHos = печать главы службы безопасности
ent-RubberStampQm = печать квартирмейстера
ent-RubberStampRd = печать научного руководителя
ent-RubberStampWarden = печать смотрителя
ent-RubberStampTrader = печать торговца
ent-RubberStampSyndicate = печать Синдиката
ent-RubberStampCE = печать старшего инженера
