ent-MailCarrierPDA = КПК почтальона
    .desc = Надеюсь, здесь нет... СПАМА.
    .suffix = { "" }
ent-SalvageTechPDA = { ent-EngineerPDA }
    .desc = { ent-EngineerPDA.desc }
    .suffix = { "" }
ent-ForensicMantisPDA = КПК детектива
    .desc = Пахнет табаком и справедливостью.
    .suffix = { "" }
ent-EpistemicsPDA = КПК аколита
    .desc = Предустановлено множество головоломок и буклетов для обращению в религию.
    .suffix = { "" }
ent-MystaPDA = КПК мистагога
    .desc = Практически излучают психическую энергию... У них на самом деле стоит Космический Папа на быстром наборе!
    .suffix = { "" }
ent-PrisonerPDA = КПК заключенного
    .desc = Чистый, так что вы можете убедиться, что внутри ничего не пронесено контрабандой.
    .suffix = { "" }
ent-GladiatorPDA = КПК гладиатора
    .desc = { ent-PrisonerPDA.desc }
    .suffix = { "" }
ent-ValetPDA = КПК сервисного работника
    .desc = Почему он не серый?
    .suffix = { "" }
ent-CataloguerPDA = КПК каталогизатора
    .desc = Вероятно его используют как антикварный записывающий девайс.
    .suffix = { "" }
ent-GuardPDA = КПК охранника
    .desc = Красный, чтобы скрыть пятна крови заключенных.
    .suffix = { "" }
