guide-entry-singularity = Сингулярный двигатель
guide-entry-radio = Радиосвязь
guide-entry-cargo-bounties = Задания Карго
guide-entry-salvage = Утилизатор
guide-entry-chemicals = Химикаты
guide-entry-bartender = Бармен
guide-entry-foodrecipes = Рецепты еды
guide-entry-medical = Медицинский
guide-entry-medicaldoctor = Врач
guide-entry-chemist = Химик
guide-entry-medicine = Медицина
guide-entry-botanicals = Ботанический
guide-entry-cloning = Клонирование
guide-entry-cryogenics = Криогеника
guide-entry-science = Наука
guide-entry-robotics = Робототехника
guide-entry-antagonists = Антагонисты
guide-entry-nuclear-operatives = Ядерные Оперативники
