ent-PosterLegitDejaVu = Deja Vu Area
    .desc = This is your first time here. If this station feels familiar, immediately alert a NanoTrasen employee.
    .suffix = { "" }
ent-PosterLegitDontPanic = Don't Panic
    .desc = If there was ever something so soothing enough to keep me from panicking, it was a green blob floating through space with a pair of hands, a shiny red tongue, and big round teeth.
    .suffix = { "" }
ent-PosterContrabandSaucerNumberOne = Saucer #1!
    .desc = Out of every station in the NyanoTrasen jurisdiction, Saucer was rated #1 out of 5! Congratulations!
    .suffix = { "" }
ent-PosterLegitBarDrinks = Bar Poster
    .desc = The Bartender is always there to hear your woes and get you plastered all at the same time. Go have a visit!
    .suffix = { "" }
ent-PosterLegitBotanyFood = Fruit Basket
    .desc = Botany is always hard at work! Stop by and enjoy the best they can offer!
    .suffix = { "" }
ent-PosterContrabandBreadLies = Bread Lies
    .desc = You have been lied to. There is no "Big Bread." It is not real. Please stop looking for it.
    .suffix = { "" }
ent-PosterLegitHotDonkExplosion = Donk!
    .desc = Bite into a blast of flavour with any of our #1 rated fattening and unhealthy products for your enjoyment! DONK!
    .suffix = { "" }
ent-PosterLegitEatMeat = Eat Meat!
    .desc = Who needs fruit or veggies? EAT MEAT! Build those muscles and go fight in the arena to show them gains!
    .suffix = { "" }
ent-PosterLegitMoreBread = More Bread!
    .desc = There is not enough bread! MAKE MORE!
    .suffix = { "" }
ent-PosterLegitPieSlice = Pie Poster
    .desc = Pies are healthy and delicious! Beg your chef to start making some.
    .suffix = { "" }
ent-PosterLegitPizzaHope = Pizza Hope
    .desc = In the darkest of times there is only one hope, PIZZA! Harass your local Quartermaster to order an emergency crate of pizza now!
    .suffix = { "" }
ent-PosterLegitMedicate = Take Your Meds
    .desc = Possible side effects may include: nausea, upset stomach, inflammation, swelling of the face/throat, rash, fever, headache, dizziness, vomiting and/or diarrhea, easy bruising, seizures, insuppressible yawning, general feeling of discomfort or illness, hives, loss of voice, bleeding gums and/or eyeballs, loss of appetite, increased appetite, sudden onset of explosive crying, x-ray vision, slurred speech, impromptu levitation, incontinence, abrupt uncontrollable outburst of yodeling, insomnia, narcolepsy, leprosy, spontaneous growth of new limbs/genitalia, unstoppable back hair growth, weight loss, weight gain, shrinkage, colorblindness, rectal numbness, acute ability to taste colors, unquenchable bloodlust, restless fingernails, light-sensitivity, compulsion to wear schoolgirl uniforms, scurvy, eagerness to pursue mercenary life, violent craving for goat's blood, insurgent desire to develop a gambling addiction, itchy bumhole. Call your doctor for medical advice about these or any other side effects you may experience.
    .suffix = { "" }
ent-PosterLegitNoTouching = No Touching
    .desc = No touching!
    .suffix = { "" }
ent-PosterMapArena = Arena Map
    .desc = A map of Arena station.
    .suffix = { "" }
ent-PosterMapGlacier = Glacier Map
    .desc = A map of Glacier outpost.
    .suffix = { "" }
ent-PosterMapShoukou = Shōkō Map
    .desc = Shōkō no mappu desu.
    .suffix = { "" }
ent-PosterLegitShoukou = Shōkō poster
    .desc = Funny symbols that can be read as Shōkō or Xiaogang, depending on who you ask.
    .suffix = { "" }
ent-PosterContrabandSMSyndie = Syndie Moth - Nuclear Operation
    .desc = Syndie Moth™ tells the viewer to keep the nuclear authentication disk unsecured. "Peace was never an option!"
    .suffix = { "" }
ent-PosterLegitSMPoisoning = Safety Moth - Poisoning
    .desc = Safety Moth™ tells the viewer not to poison the station donuts.
    .suffix = { "" }
ent-PosterLegitSMBoH = Safety Moth - Bag of Holding
    .desc = Safety Moth™ informs the viewer of the dangers of Bags of Holding. "Remember! Bags of Holding may be pretty, but they're also pretty dangerous! Never put one inside another!"
    .suffix = { "" }
ent-PosterLegitSMHardhats = Safety Moth - Hard hats
    .desc = Safety Moth™ tells the viewer to wear hard hats in cautious areas. "It's like a lamp on your head!"
    .suffix = { "" }
ent-PosterLegitSMFires = Safety Moth - Fires
    .desc = Safety Moth™ promotes safe handling of plasma and to keep firefighting equipment within hand reach.
    .suffix = { "" }
ent-PosterLegitSMPiping = Safety Moth - Piping
    .desc = Safety Moth™ tells atmospheric technicians the correct types of piping to be used. "Pipes, not Pumps! Proper pipe placement prevents poor performance!"
    .suffix = { "" }
ent-PosterLegitSMMeth = Safety Moth - Methamphetamine
    .desc = Safety Moth™ tells the viewer to seek CMO approval before cooking methamphetamine. "Stay close to the target temperature, and never go over!"
    .suffix = { "" }
ent-PosterLegitSMEpi = Safety Moth - Epinephrine
    .desc = Safety Moth™ informs the viewer to help injured/deceased crewmen with their epinephrine injectors. "Epipen a pal when they're in peril! Prevent organ rot with this one simple trick!"
    .suffix = { "" }
ent-PosterLegitSMPills = Safety Moth - Pill Bottles
    .desc = Safety Moth™ informs the viewer that leaving pills unsupervised on tables could lead to unforeseen consequences. "Hungry critters love to eat everything! Keep your pills safe in crates and pill bottles!"
    .suffix = { "" }
ent-PosterLegitSMAnomalies = Safety Moth - Anomalies
    .desc = Safety Moth™ promotes proper safety equipment when working around anomalies. "Every good Moths wears protection when working with anomalies, but don't get too close! Not everything that glows is a friend!"
    .suffix = { "" }
ent-PosterLegitSMGlimmer = Safety Moth - Glimmer Safety Precautions
    .desc = Safety Moth™ tells the viewer to wear insulative equipments and hide in lockers when the glimmer gets within critical levels. Evacuating might be a better strategy.
    .suffix = { "" }
