ent-ClothingUniformJumpsuitLostTourist = потерянная туристическая форма
    .desc = Форма тех, кто просто хочет отдохнуть на пляже... Где вообще пляж?
    .suffix = { "" }
ent-ClothingUniformJumpsuitJeansRed = красный свитер с джинсами
    .desc = Красный свитер с синими джинсами. У этого доминирующие джинсы.
    .suffix = { "" }
ent-ClothingUniformJumpsuitJeansGreen = зеленый свитер с джинсами
    .desc = Зеленый свитер и синие джинсы. У этого рецессивные джинсы.
    .suffix = { "" }
ent-ClothingUniformJumpsuitJeansBrown = коричневый свитер с джинсами
    .desc = Коричневый свитер и синие джинсы.
    .suffix = { "" }
