ent-Cigarette = сигарета
    .desc = Скрутка с табаком и никотином.
    .suffix = { "" }
ent-CigaretteSpent = { ent-Cigarette }
    .suffix = использована
    .desc = { ent-Cigarette.desc }
ent-CigaretteSyndicate = сигарета
    .suffix = синдикат
    .desc = { ent-Cigarette.desc }
