ent-PlayerRobotBase = robot
    .desc = { ent-PlayerSiliconBase.desc }
    .suffix = { "" }
ent-PlayerRobotStandard = standard robot
    .desc = { ent-PlayerRobotBase.desc }
    .suffix = { "" }
ent-PlayerRobotMedical = medical robot
    .desc = { ent-PlayerRobotBase.desc }
    .suffix = { "" }
