ent-MailAlcohol = { ent-BaseMail }
    .suffix = алкоголь
    .desc = { ent-BaseMail.desc }
ent-MailSake = { ent-BaseMail }
    .suffix = сакэ
    .desc = { ent-BaseMail.desc }
ent-MailAMEGuide = { ent-BaseMail }
    .suffix = руководство
    .desc = { ent-BaseMail.desc }
ent-MailBible = { ent-BaseMail }
    .suffix = библия
    .desc = { ent-BaseMail.desc }
ent-MailBikeHorn = { ent-BaseMail }
    .suffix = велосипедный гудок
    .desc = { ent-BaseMail.desc }
ent-MailBlockGameDIY = { ent-BaseMail }
    .suffix = блокгейм
    .desc = { ent-BaseMail.desc }
ent-MailBooks = { ent-BaseMail }
    .suffix = книги
    .desc = { ent-BaseMail.desc }
ent-MailCake = { ent-BaseMail }
    .suffix = пирог
    .desc = { ent-BaseMail.desc }
ent-MailCallForHelp = { ent-BaseMail }
    .suffix = call-for-help
    .desc = { ent-BaseMail.desc }
ent-MailCheese = { ent-BaseMail }
    .suffix = сыр
    .desc = { ent-BaseMail.desc }
ent-MailChocolate = { ent-BaseMail }
    .suffix = шоколад
    .desc = { ent-BaseMail.desc }
ent-MailCigarettes = { ent-BaseMail }
    .suffix = сигаретты
    .desc = { ent-BaseMail.desc }
ent-MailCigars = { ent-BaseMail }
    .suffix = сигары
    .desc = { ent-BaseMail.desc }
ent-MailCookies = { ent-BaseMail }
    .suffix = печенье
    .desc = { ent-BaseMail.desc }
ent-MailCosplayArc = { ent-BaseMail }
    .suffix = косплей-арк
    .desc = { ent-BaseMail.desc }
ent-MailCosplayGeisha = { ent-BaseMail }
    .suffix = косплей-гейша
    .desc = { ent-BaseMail.desc }
ent-MailCosplayMaid = { ent-BaseMail }
    .suffix = косплей-горничная
    .desc = { ent-BaseMail.desc }
ent-MailCosplayNurse = { ent-BaseMail }
    .suffix = косплей-медсестра
    .desc = { ent-BaseMail.desc }
ent-MailCosplaySchoolgirl = { ent-BaseMail }
    .suffix = косплей-школьная форма
    .desc = { ent-BaseMail.desc }
ent-MailCosplayWizard = { ent-BaseMail }
    .suffix = косплей-волшебник
    .desc = { ent-BaseMail.desc }
ent-MailCrayon = { ent-BaseMail }
    .suffix = карандаш
    .desc = { ent-BaseMail.desc }
ent-MailFigurine = { ent-BaseMail }
    .suffix = фигурка
    .desc = { ent-BaseMail.desc }
ent-MailFishingCap = { ent-BaseMail }
    .suffix = кепка рыбака
    .desc = { ent-BaseMail.desc }
ent-MailFlashlight = { ent-BaseMail }
    .suffix = фонарик
    .desc = { ent-BaseMail.desc }
ent-MailFlowers = { ent-BaseMail }
    .suffix = цветы
    .desc = { ent-BaseMail.desc }
ent-MailHighlander = { ent-BaseMail }
    .suffix = highlander
    .desc = { ent-BaseMail.desc }
ent-MailHighlanderDulled = { ent-BaseMail }
    .suffix = highlander, dulled
    .desc = { ent-BaseMail.desc }
ent-MailHoneyBuns = { ent-BaseMail }
    .suffix = медовая булочка
    .desc = { ent-BaseMail.desc }
ent-MailJunkFood = { ent-BaseMail }
    .suffix = фастфуд
    .desc = { ent-BaseMail.desc }
ent-MailKatana = { ent-BaseMail }
    .suffix = катана
    .desc = { ent-BaseMail.desc }
ent-MailKnife = { ent-BaseMail }
    .suffix = нож
    .desc = { ent-BaseMail.desc }
ent-MailMoney = { ent-BaseMail }
    .suffix = деньги
    .desc = { ent-BaseMail.desc }
ent-MailMuffins = { ent-BaseMail }
    .suffix = маффины
    .desc = { ent-BaseMail.desc }
ent-MailNoir = { ent-BaseMail }
    .suffix = noir
    .desc = { ent-BaseMail.desc }
ent-MailPAI = { ent-BaseMail }
    .suffix = PAI
    .desc = { ent-BaseMail.desc }
ent-MailPlushie = { ent-BaseMail }
    .suffix = плюшевая игрушка
    .desc = { ent-BaseMail.desc }
ent-MailRestraints = { ent-BaseMail }
    .suffix = наручники
    .desc = { ent-BaseMail.desc }
ent-MailSignallerKit = { ent-BaseMail }
    .suffix = signallerkit
    .desc = { ent-BaseMail.desc }
ent-MailSkub = { ent-BaseMail }
    .suffix = скаб
    .desc = { ent-BaseMail.desc }
ent-MailSoda = { ent-BaseMail }
    .suffix = газировка
    .desc = { ent-BaseMail.desc }
ent-MailSpaceVillainDIY = { ent-BaseMail }
    .suffix = spacevilliandiy
    .desc = { ent-BaseMail.desc }
ent-MailSunglasses = { ent-BaseMail }
    .suffix = солнечные очки
    .desc = { ent-BaseMail.desc }
ent-MailVagueThreat = { ent-BaseMail }
    .suffix = vague-threat
    .desc = { ent-BaseMail.desc }
ent-MailWinterCoat = { ent-BaseMail }
    .suffix = зимняя куртка
    .desc = { ent-BaseMail.desc }
ent-MailMoffins = { ent-BaseMail }
    .suffix = moffins
    .desc = { ent-BaseMail.desc }
