ent-TrashBag = trash bag
    .desc = { ent-BaseStorageItem.desc }
    .suffix = { "" }
ent-TrashBagBlue = trash bag
    .desc = { ent-TrashBag.desc }
    .suffix = { "" }
ent-BagOfSummoningGarbage = { ent-TrashBagBlue }
    .desc = { ent-TrashBagBlue.desc }
    .suffix = { "" }
