ent-BaseMagazineMagnum = Lamia magazine (.45 magnum)
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-MagazineMagnum = Lamia magazine (.45 magnum)
    .desc = { ent-BaseMagazineMagnum.desc }
    .suffix = { "" }
ent-MagazineMagnumHighVelocity = Lamia magazine (.45 magnum high-velocity)
    .desc = { ent-BaseMagazineMagnum.desc }
    .suffix = { "" }
ent-MagazineMagnumPractice = Lamia magazine (.45 magnum practice)
    .desc = { ent-BaseMagazineMagnum.desc }
    .suffix = { "" }
ent-MagazineMagnumRubber = Lamia magazine (.45 magnum rubber)
    .desc = { ent-BaseMagazineMagnum.desc }
    .suffix = { "" }
