ent-BaseMagazineMagnum = магазин Lamia (.45 magnum)
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-MagazineMagnum = магазин Lamia (.45 magnum)
    .desc = { ent-BaseMagazineMagnum.desc }
    .suffix = { "" }
ent-MagazineMagnumHighVelocity = магазин Lamia (.45 magnum высокоскоростные)
    .desc = { ent-BaseMagazineMagnum.desc }
    .suffix = { "" }
ent-MagazineMagnumPractice = магазин Lamia (.45 magnum учебные)
    .desc = { ent-BaseMagazineMagnum.desc }
    .suffix = { "" }
ent-MagazineMagnumRubber = магазин Lamia (.45 magnum резина)
    .desc = { ent-BaseMagazineMagnum.desc }
    .suffix = { "" }
