ent-SpawnPointParamedic = paramedic
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointGladiator = gladiator
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointMailCarrier = mailcarrier
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointForensicMantis = forensic mantis
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointCyborg = cyborg
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointMedicalCyborg = medical cyborg
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointMystagogue = mystagogue
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointEpistemologist = epistemologist
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointCataloguer = cataloguer
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointSalvageTechnician = salvagetechnician
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointPrisoner = prisoner
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointValet = valet
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
ent-SpawnPointPrisonGuard = prison guard
    .desc = { ent-SpawnPointJobBase.desc }
    .suffix = { "" }
