ent-ClothingHeadHelmetKendoMen = кендо шапка
    .desc = Квинтэссенция головного доспеха практикующего кендо.
    .suffix = { "" }
ent-ClothingHeadHatBeretCap = берет капитана
    .desc = Синий берет с эмблемой капитанского звания. Для капитанов, которые больше склонны к стилю, чем к безопасности.
    .suffix = { "" }
ent-ClothingHeadHatBeretCentcomm = берет ЦентКом
    .desc = Зеленый берет с эмблемой адмиральского звания.
    .suffix = { "" }
ent-ClothingHeadHatBeretMysta = берет мистагога
    .desc = Фиолетовый берет с синей эпистемологической эмблемой. Мистический и стильный.
    .suffix = { "" }
