ent-tatamibase = { ent-BaseStructure }
    .desc = { ent-BaseStructure.desc }
    .suffix = { "" }
ent-tatamisingle = tatami square
    .desc = It's tatami, but a square.
    .suffix = { "" }
ent-tatamimat = tatami mat
    .desc = It's a portion of a tatami mat.
    .suffix = { "" }
