ent-BaseMechPart = { "" }
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-BaseMechPartItem = { ent-BaseMechPart }
ent-BaseMechConstruct = { ent-BaseMechPart }
ent-RipleyHarness = упряжь рипли
ent-RipleyLArm = левая рука рипли
ent-RipleyLLeg = левая нога рипли
ent-RipleyRLeg = правая нога рипли
ent-RipleyRArm = правая рука рипли
ent-RipleyChassis = ходовая часть рипли
