ent-RandomHumanoidSpawnerERTLeader = ОБР лидер
.desc = Содержит 2 костюма биологической опасности, чтобы никакая болезнь не отвлекала вас от лечения экипажа. Для открытия требуется доступ врача.
.suffix = { "" }
ent-RandomHumanoidSpawnerERTLeaderEVA = ОБР лидер
ent-RandomHumanoidSpawnerERTJanitor = ОБР уборщик
ent-RandomHumanoidSpawnerERTJanitorEVA = ОБР уборщик
ent-RandomHumanoidSpawnerERTEngineer = ОБР инженер
ent-RandomHumanoidSpawnerERTEngineerEVA = ОБР инженер
ent-RandomHumanoidSpawnerERTSecurity = ОБР офицер безопасности
ent-RandomHumanoidSpawnerERTSecurityEVA = ОБР офицер безопасности
ent-RandomHumanoidSpawnerERTMedical = ОБР медик
ent-RandomHumanoidSpawnerERTMedicalEVA = ОБР медик
ent-RandomHumanoidSpawnerCBURNUnit = Агент РХБЗЗ
ent-RandomHumanoidSpawnerCentcomOfficial = представитель ЦентКом
ent-RandomHumanoidSpawnerSyndicateAgent = Агент Синдиката
ent-RandomHumanoidSpawnerNukeOp = Ядерный оперативник
