ent-BaseTreePalmLarge = { ent-BaseTree }
    .desc = { ent-BaseTree.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge01 = large palm tree
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge02 = large palm tree
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge03 = large palm tree
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge04 = large palm tree
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge05 = large palm tree
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-FloraTreePalmLarge06 = large palm tree
    .desc = { ent-BaseTreePalmLarge.desc }
    .suffix = { "" }
ent-BaseTreePalm = { ent-BaseTree }
    .desc = { ent-BaseTree.desc }
    .suffix = { "" }
ent-FloraTreePalm01 = palm tree
    .desc = { ent-BaseTreePalm.desc }
    .suffix = { "" }
ent-FloraTreePalm02 = palm tree
    .desc = { ent-BaseTreePalm.desc }
    .suffix = { "" }
ent-FloraTreePalm03 = palm tree
    .desc = { ent-BaseTreePalm.desc }
    .suffix = { "" }
ent-FloraTreePalm04 = palm tree
    .desc = { ent-BaseTreePalm.desc }
    .suffix = { "" }
