ent-BaseHyperlinkBook = { ent-BaseItem }
    .desc = { ent-BaseItem.desc }
    .suffix = { "" }
ent-HyperlinkBookSpaceLaw = space law
    .desc = A big book of laws for space courts.
    .suffix = { "" }
ent-HyperlinkBookSupernanny = book of unsanctioned space punishments
    .desc = The ravings of a madman.
    .suffix = { "" }
ent-HyperlinkBookGlimmer = guide to glimmer
    .desc = A guide to the phenomenon known as 'glimmer.'
    .suffix = { "" }
ent-HyperlinkBookChemistry = chemical recipe book
    .desc = A list of chemical recipes.
    .suffix = { "" }
ent-HyperlinkBookBartending = bartender's guide
    .desc = A list of drink recipes.
    .suffix = { "" }
ent-HyperlinkBookCooking = cookbook
    .desc = A list of food recipes.
    .suffix = { "" }
ent-HyperlinkBookBotany = botanical field guide
    .desc = A guide to plants.
    .suffix = { "" }
ent-HyperlinkBookShuttle = guide to shuttle construction
    .desc = A guide to building shuttles.
    .suffix = { "" }
ent-HyperlinkBookAlerts = alert procedure
    .desc = Procedure for when and why each alert should be put in effect, and what to do.
    .suffix = { "" }
ent-HyperlinkBookProcedure = standard operating procedure
    .desc = A guide to normal station function.
    .suffix = { "" }
ent-HyperlinkBookPower = guide to power
    .desc = A guide to powering the station.
    .suffix = { "" }
ent-HyperlinkBookMedical = guide to medical
    .desc = A guide to the medical department.
    .suffix = { "" }
ent-HyperlinkBookHacking = guide to hacking
    .desc = For emergency use only.
    .suffix = { "" }
ent-HyperlinkBookAtmos = guide to atmospherics
    .desc = How to make sure everyone has air to breathe.
    .suffix = { "" }
